Steps: <a id='back'></a>

+ LENDING: [LENDING](#LENDING)
+ FUNDING: [FUNDING](#FUNDING)
+ EXPORT: [EXPORT](#EXPORT)

In [1]:
import pandas as pd
import numpy as np
import time
import os
import xlrd

In [2]:
pd.reset_option('^display.', silent=True)
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:,}'.format

In [3]:
start_time = time.time()

In [4]:
os.chdir(r'D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline')

# LENDING

[back](#back)

## 1. Read data

### 1.1 Update Daily

In [5]:
## Global Variable
current_d_lending   = 20260326 #CHANGE
current_d2_lending = "2026-03-26" #CHANGE
current_d3_lending = 260326 #CHANGE

daily_crs = 260326 #CHANGE

#### CRS CL

In [10]:
read_crs_smer = f'D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\CRS_SME_CL\\CRS_SME_{daily_crs}.xlsx'
read_crs_smeplus = f'D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\CRS_SMEPLUS_CL\\CRS_SMEPLUS_{daily_crs}.xlsx'

#### XPOSE

In [7]:
read_xpose = f'D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\FASILITAS_XPOSE\\FASILITAS_260314.DAT'

In [8]:
#save_data
save_smeplus_baseline = f'Results\\BASELINE_SMEPlus_{current_d3_lending}.csv'
save_smeplus_upline = f'Results\\UPLINE_SMEPlus_{current_d3_lending}.csv'
save_smeplus_baseline_lending = f'Results\\BASELINE_LENDING_SMEPlus_{current_d3_lending}.csv'

save_rsme_baseline = f'Results\\BASELINE_RSME_{current_d3_lending}.csv'
save_rsme_upline = f'Results\\UPLINE_RSME_{current_d3_lending}.csv'
save_rsme_baseline_lending = f'Results\\BASELINE_LENDING_RSME_{current_d3_lending}.csv'

In [11]:
crs_smer = pd.read_excel(read_crs_smer, 
                        usecols = ['GCIF_NO','NPK_MAINT','NPK_REFF','REGION','AREA','BR_CD','RC_BR_CD','PRD_TP']
                        )
crs_smer['BRANCH'] = crs_smer['AREA']

crs_smeplus = pd.read_excel(read_crs_smeplus,
                        usecols = ['GCIF_NO','NPK_MAINT','NPK_REFF','REGION','AREA','BR_CD','RC_BR_CD','PRD_TP']
                        )                    
crs_smeplus['BRANCH'] = crs_smeplus['AREA']

xpose_header2=['BASE_DT','AGREE_ID','HIRARKI','TOP_AGREE_ID','GCIF_NO','CIF_NO','MBR_CD','MBR_NM','CUST_NM','BII_SIC','LVL4_DESC',
       'PRD_SEGMENT','HLT_CD','DT_ESTB','PREV_BRR','BRR','PRD_TP','PRD_NM','CURR_CD','CURR_LMT_AMT','BAL','INT_BAL','NOTE_DT',
       'CURR_MAT_DT','MID_XRT','NOTE_NO','CURR_INT_RT','SCORE_CARD','PROD_GRP_NM','ORG_BAL','TENOR','SEGMENTASI','REG_NM',
       'B2B_FLAG','BR_CD','INST_PRIN_BAL','INST_INT_BAL','INST_TOT_BAL','PASTDUE_SINCE_DT','PASTDUE_DAYS','NATURE_CD',
       'PURPOSE_CD','UNUSED_AMT','ACCT_NO','NPK_MAINT','LOBFIN','X1','X2','X3','X4','X5','X6','X7','LVL3_DESC','LVL2_DESC',
       'LVL1_DESC','PPAP_AMT','FIN_DT','BRR_CCRS','LVL_BRR','SCORECRD_TP','LAST_RENEWAL_DT','X8','X9','APPL_ID','X10','X11','WRITE_OFF_YN','X12']

xpose = pd.read_csv(read_xpose, sep='|', names=xpose_header2, parse_dates=['NOTE_DT'], low_memory=False)

### 1.2 Update Weekly

In [12]:
current_m_lending2 = "31 Juli'25" #For BB
current_m_lending3   = 250731  #For BB
current_m_lending4 = "2025-10-09" #For BB

read_bb = f"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\BB\\Account Handling BB Dec'24_Sent PDA.xlsx"

save_bb_baseline = f'Results\\BASELINE_BB_{current_m_lending3}.csv'
save_bb_upline = f'Results\\UPLINE_BB_{current_m_lending3}.csv'
save_bb_baseline_lending = f'Results\\BASELINE_LENDING_BB_{current_m_lending3}.csv'

### 1.2 Update Monthly

In [13]:
current_m_lending = 2603 #For NCL
current_m_lending1 = 260326 #For NCL

read_crs_smer_ncl = f"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\CRS_SME_NCL\\NON_CASH_SME {current_m_lending1}.xlsx"
read_crs_smeplus_ncl = f"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\CRS_SMEPLUS_NCL\\NON_CASH_SME+ {current_m_lending1}.xlsx"

crs_smer_ncl = pd.read_excel(read_crs_smer_ncl)
crs_smeplus_ncl = pd.read_excel(read_crs_smeplus_ncl)

#### HIERARCHY RSME & SME+

In [17]:
Month = 'Feb2026'

In [18]:
read_hierarchy = f'D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Monthly Update\Data Monthly\Hierarchy\Hierarchy as of {Month}.xlsx'

In [19]:
hierarchy_smer = pd.read_excel(read_hierarchy, sheet_name = 'RSME',skiprows=1,
                               usecols=['REGION', 'NPK RSH', 'RSH NAME','NPK ASH','ASH NAME', 'BRANCH', 
                                        'TL NPK', 'TL NAME','NPK', 'NAMA RO', 'BRANCH SALES'])
#hierarchy_smer = hierarchy_smer[hierarchy_smer['REGION CODE'] != 'Grand Total']

for col in ['REGION', 'NPK RSH', 'RSH NAME', 
            'NPK ASH','ASH NAME', 'BRANCH', 
            'TL NPK', 'TL NAME']:
    hierarchy_smer[col] = hierarchy_smer[col].ffill()

hierarchy_smeplus = pd.read_excel(read_hierarchy, sheet_name = 'SME+',skiprows=1,
                                  usecols=['REGION', 'NPK RSH', 'RSH NAME','AREA','NPK ASH','ASH NAME',
                                           'NPK', 'NAMA RO', 'BRANCH SALES'])
#hierarchy_smeplus = hierarchy_smeplus[hierarchy_smeplus['REGION CODE'] != 'Grand Total']
for col in ['REGION', 'NPK RSH', 'RSH NAME', 
            'AREA','NPK ASH','ASH NAME']:
    hierarchy_smeplus[col] = hierarchy_smeplus[col].ffill()

In [20]:
hierarchy_smer

,REGION,NPK RSH,RSH NAME,NPK ASH,ASH NAME,BRANCH,TL NPK,TL NAME,NPK,NAMA RO,BRANCH SALES
0,SUMATERA UTARA,"38,241.0",TOWATI SUJONO,"18,345.0",ANTON HARTONO,MEDAN BARAT,0.0,VACANT,"42,039.0",HARTA UTOMO,KCI MEDAN
1,SUMATERA UTARA,"38,241.0",TOWATI SUJONO,"18,345.0",ANTON HARTONO,MEDAN BARAT,0.0,VACANT,NaN,VACANT,KCI MEDAN
2,SUMATERA UTARA,"38,241.0",TOWATI SUJONO,"18,345.0",ANTON HARTONO,MEDAN BARAT,0.0,VACANT,NaN,VACANT,KCI MEDAN
3,SUMATERA UTARA,"38,241.0",TOWATI SUJONO,"18,345.0",ANTON HARTONO,MEDAN BARAT,0.0,VACANT,NaN,VACANT,KCI MEDAN
4,SUMATERA UTARA,"38,241.0",TOWATI SUJONO,"18,345.0",ANTON HARTONO,MEDAN BARAT,"18,680.0",SURYANDI,"38,872.0",SARAH DINA HARA SITOMPUL,KCI MEDAN
...,...,...,...,...,...,...,...,...,...,...,...
295,JAWA TENGAH,"20,157.0",HENDRO,0.0,VACANT,YOGYAKARTA,0.0,NO MANAGER,NaN,NaN,NaN
296,JAWA TENGAH,"20,157.0",HENDRO,0.0,VACANT,YOGYAKARTA,0.0,NO MANAGER,NaN,NaN,NaN
297,JAWA TENGAH,"20,157.0",HENDRO,0.0,VACANT,YOGYAKARTA,0.0,NO MANAGER,NaN,NaN,NaN
298,JAWA TENGAH,"20,157.0",HENDRO,0.0,VACANT,YOGYAKARTA,0.0,NO MANAGER,NaN,NaN,NaN
299,JAWA TENGAH,"20,157.0",HENDRO,0.0,VACANT,YOGYAKARTA,0.0,NO MANAGER,NaN,NaN,NaN

#### ACCOUNT HANDLING BB

In [21]:
acc_handling_bb = pd.read_excel(read_bb, sheet_name = 'Account Handling', skiprows=1)
acc_handling_bb['AREA'] = ''
acc_handling_bb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   GCIF_NO   1121 non-null   object
 1   REGION    1121 non-null   object
 2   NPK AO    1111 non-null   float64
 3   AO NAME   1113 non-null   object
 4   NPK TL    1113 non-null   float64
 5   TL NAME   1118 non-null   object
 6   NPK RBBH  1121 non-null   int64
 7   RBBH      1121 non-null   object
 8   AREA      1121 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 78.9+ KB

### 1.3 Update Quarterly

In [22]:
current_q = 2507
# current_q2 = "Oct'24"
# current_q4   = 20241031 #CHANGE
# current_q4 = "2024-10-31" #CHANGE

#upline_funding = f"Results\\Funding\\UPLINE_FUNDING_{current_q}.csv"
#baseline_funding = f"Results\\Funding\\BASELINE_FUNDING_{current_q}.csv"

upline_funding = pd.read_csv(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Upline & Baseline\Results\UPLINE_FUNDING_2602.csv")
baseline_funding = pd.read_csv(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Upline & Baseline\Results\BASELINE_FUNDING_2602.csv")

In [23]:
baseline_funding['LOB'].unique()

array(['SME', 'BB', 'SME+'], dtype=object)

### 1.4 Update Email (If Needed)

In [24]:
users = pd.read_excel(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\PDT NR Users.xlsx")

In [25]:
#Branch Mapping
branch_map = pd.read_excel(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Lending\01. List Branch Jan25 (inc Sya).xlsx",
                           sheet_name='Branch Sales ALL',
                           usecols= ['REGION CODE', 'REGION', 'AREA CODE', 'AREA', 'BRANCH CODE', 'BRANCH'])

In [26]:
product_map=pd.read_csv("D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Product_Map.csv",low_memory=False)
manual_mapping = pd.read_excel("D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Lending\Manual Mapping Baseline.xlsx", sheet_name = 'New')

## 2. Preprocessing Hierarchy

### 2.1 Hierarchy RSME

#### 2.1.1 Preprocessing AREA and REGION

In [28]:
hierarchy_smer.columns = ['REGION_RSH','NPK_RSH','NAME_RSH',
                    'NPK_ASH','NAME_ASH','AREA_ASH',
                    'NPK_SMEM','NAME_SMEM',
                    'NPK_RO','NAME_RO','BRANCH_RO']

#### 2.1.2 Align data types

In [29]:
hierarchy_smer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  300 non-null    object
 1   NPK_RSH     300 non-null    float64
 2   NAME_RSH    300 non-null    object
 3   NPK_ASH     300 non-null    float64
 4   NAME_ASH    300 non-null    object
 5   AREA_ASH    300 non-null    object
 6   NPK_SMEM    300 non-null    float64
 7   NAME_SMEM   300 non-null    object
 8   NPK_RO      226 non-null    float64
 9   NAME_RO     295 non-null    object
 10  BRANCH_RO   295 non-null    object
dtypes: float64(4), object(7)
memory usage: 25.9+ KB

In [30]:
hierarchy_smer['NPK_RO'] = np.where(hierarchy_smer['NAME_RO'].str.contains('VACANT'),0,hierarchy_smer['NPK_RO'])
hierarchy_smer['NPK_RO'] = np.where(hierarchy_smer['NAME_RO'].str.contains('NO MANAGER'),0,hierarchy_smer['NPK_RO'])
hierarchy_smer['NPK_RO'] = np.where(hierarchy_smer['NPK_RO'].isna(),0,hierarchy_smer['NPK_RO'])
hierarchy_smer['NPK_RO'] = hierarchy_smer['NPK_RO'].astype('int64')

hierarchy_smer['NPK_SMEM'] = np.where(hierarchy_smer['NAME_SMEM'].str.contains('VACANT'),0,hierarchy_smer['NPK_SMEM'])
hierarchy_smer['NPK_SMEM'] = np.where(hierarchy_smer['NAME_SMEM'].str.contains('NO MANAGER'),0,hierarchy_smer['NPK_SMEM'])
hierarchy_smer['NPK_SMEM'] = hierarchy_smer['NPK_SMEM'].astype('int64')

hierarchy_smer['NPK_ASH'] = np.where(hierarchy_smer['NAME_ASH'].str.contains('VACANT'),0,hierarchy_smer['NPK_ASH'])
hierarchy_smer['NPK_ASH'] = np.where(hierarchy_smer['NAME_ASH'].str.contains('NO MANAGER'),0,hierarchy_smer['NPK_ASH'])
hierarchy_smer['NPK_ASH'] = hierarchy_smer['NPK_ASH'].astype('int64')

hierarchy_smer['NPK_RSH'] = hierarchy_smer['NPK_RSH'].astype('float64')
hierarchy_smer['NPK_RSH'] = hierarchy_smer['NPK_RSH'].astype('str')

hierarchy_smer['NPK_RSH'] = np.where(hierarchy_smer['NPK_RSH'].str.contains('VACANT'),0,hierarchy_smer['NPK_RSH'])
hierarchy_smer['NPK_RSH'] = hierarchy_smer['NPK_RSH'].astype('str')
hierarchy_smer['NPK_RSH'] = hierarchy_smer['NPK_RSH'].str[:-2]
hierarchy_smer['NPK_RSH'] = np.where(hierarchy_smer['NPK_RSH']=='n','0',hierarchy_smer['NPK_RSH'])
hierarchy_smer['NPK_RSH'] = hierarchy_smer['NPK_RSH'].astype('int64')

hierarchy_smer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  300 non-null    object
 1   NPK_RSH     300 non-null    int64
 2   NAME_RSH    300 non-null    object
 3   NPK_ASH     300 non-null    int64
 4   NAME_ASH    300 non-null    object
 5   AREA_ASH    300 non-null    object
 6   NPK_SMEM    300 non-null    int64
 7   NAME_SMEM   300 non-null    object
 8   NPK_RO      300 non-null    int64
 9   NAME_RO     295 non-null    object
 10  BRANCH_RO   295 non-null    object
dtypes: int64(4), object(7)
memory usage: 25.9+ KB

#### 2.1.3 Remove VACANT names

In [31]:
hierarchy_smer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  300 non-null    object
 1   NPK_RSH     300 non-null    int64
 2   NAME_RSH    300 non-null    object
 3   NPK_ASH     300 non-null    int64
 4   NAME_ASH    300 non-null    object
 5   AREA_ASH    300 non-null    object
 6   NPK_SMEM    300 non-null    int64
 7   NAME_SMEM   300 non-null    object
 8   NPK_RO      300 non-null    int64
 9   NAME_RO     295 non-null    object
 10  BRANCH_RO   295 non-null    object
dtypes: int64(4), object(7)
memory usage: 25.9+ KB

In [32]:
remove = ['VACANT','NO MANAGER']

hierarchy_smer['NAME_RO'] = np.where(hierarchy_smer['NAME_RO'].str.contains('|'.join(remove)),
                                         "",hierarchy_smer['NAME_RO'])
hierarchy_smer['NAME_SMEM'] = np.where(hierarchy_smer['NAME_SMEM'].str.contains('|'.join(remove)),
                                         "",hierarchy_smer['NAME_SMEM'])
hierarchy_smer['NAME_ASH'] = np.where(hierarchy_smer['NAME_ASH'].str.contains('|'.join(remove)),
                                         "",hierarchy_smer['NAME_ASH'])
hierarchy_smer['NAME_RSH'] = np.where(hierarchy_smer['NAME_RSH'].str.contains('|'.join(remove)),
                                         "",hierarchy_smer['NAME_RSH'])

#### 2.1.4 Remove duplicates and make list of all NPKs in hierarchy

In [33]:
#Drop duplicates (due to Vacant RO roles)
hierarchy_smer_clean = hierarchy_smer.drop_duplicates()
hierarchy_smer_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 274 entries, 0 to 295
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  274 non-null    object
 1   NPK_RSH     274 non-null    int64
 2   NAME_RSH    274 non-null    object
 3   NPK_ASH     274 non-null    int64
 4   NAME_ASH    274 non-null    object
 5   AREA_ASH    274 non-null    object
 6   NPK_SMEM    274 non-null    int64
 7   NAME_SMEM   274 non-null    object
 8   NPK_RO      274 non-null    int64
 9   NAME_RO     274 non-null    object
 10  BRANCH_RO   273 non-null    object
dtypes: int64(4), object(7)
memory usage: 25.7+ KB

In [34]:
ro_list_rsme = hierarchy_smer[['NPK_RO','NAME_RO']]
ro_list_rsme['JABATAN'] = 'RELATIONSHIP OFFICER'
ro_list_rsme.columns = ['NPK','NAMA','JABATAN']
smem_list_rsme = hierarchy_smer[['NPK_SMEM','NAME_SMEM']]
smem_list_rsme['JABATAN'] = 'SME MANAGER'
smem_list_rsme.columns = ['NPK','NAMA','JABATAN']

rsme_npk_list = pd.concat([ro_list_rsme,smem_list_rsme],axis=0)
rsme_npk_list=rsme_npk_list[rsme_npk_list['NPK']!=0]
rsme_npk_list=rsme_npk_list.drop_duplicates(keep='first')
rsme_npk_list.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290 entries, 0 to 278
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NPK      290 non-null    int64
 1   NAMA     290 non-null    object
 2   JABATAN  290 non-null    object
dtypes: int64(1), object(2)
memory usage: 9.1+ KB

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2575962809.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ro_list_rsme['JABATAN'] = 'RELATIONSHIP OFFICER'
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2575962809.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smem_list_rsme['JABATAN'] = 'SME MANAGER'

In [35]:
hierarchy_smer[hierarchy_smer['NPK_SMEM']==43269]

,REGION_RSH,NPK_RSH,NAME_RSH,NPK_ASH,NAME_ASH,AREA_ASH,NPK_SMEM,NAME_SMEM,NPK_RO,NAME_RO,BRANCH_RO
80,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,43071,RIZSANIA HENDARWIN,KCI SUMMITMAS
81,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,40825,RICO SIMANUNGKALIT,KCI SUMMITMAS
82,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,44131,OLGA ANINDA RESTU,KCI SUMMITMAS

In [36]:
#Check
rsme_npk_list[rsme_npk_list['NPK'].duplicated(keep=False)]

Empty DataFrame
Columns: [NPK, NAMA, JABATAN]
Index: []

### 2.2 Hierarchy SME+

#### 2.2.1 Preprocessing AREA and REGION

In [37]:
hierarchy_smeplus.columns = ['REGION_RSH','NPK_RSH','NAME_RSH','AREA_ASH','NPK_ASH','NAME_ASH',
                             'NPK_RO','NAME_RO','BRANCH_RO']

In [38]:
hierarchy_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  76 non-null     object
 1   NPK_RSH     76 non-null     float64
 2   NAME_RSH    76 non-null     object
 3   AREA_ASH    76 non-null     object
 4   NPK_ASH     76 non-null     float64
 5   NAME_ASH    76 non-null     object
 6   NPK_RO      53 non-null     float64
 7   NAME_RO     63 non-null     object
 8   BRANCH_RO   63 non-null     object
dtypes: float64(3), object(6)
memory usage: 5.5+ KB

#### 2.2.2 Align data types

In [39]:
hierarchy_smeplus['NPK_RO'] = np.where(hierarchy_smeplus['NAME_RO'].isna(),0,hierarchy_smeplus['NPK_RO'])
hierarchy_smeplus['NPK_RO'] = np.where(hierarchy_smeplus['NPK_RO'].isna(),0,hierarchy_smeplus['NPK_RO'])
hierarchy_smeplus['NPK_RO'] = hierarchy_smeplus['NPK_RO'].astype('int64')

hierarchy_smeplus['NPK_ASH'] = np.where(hierarchy_smeplus['NAME_ASH'].str.contains('VACANT'),0,hierarchy_smeplus['NPK_ASH'])
hierarchy_smeplus['NPK_ASH'] = np.where(hierarchy_smeplus['NPK_ASH'].isna(),0,hierarchy_smeplus['NPK_ASH'])
hierarchy_smeplus['NPK_ASH'] = hierarchy_smeplus['NPK_ASH'].astype('int64')

hierarchy_smeplus['NPK_RSH'] = np.where(hierarchy_smeplus['NAME_RSH'].str.contains('VACANT'),0,hierarchy_smeplus['NPK_RSH'])
hierarchy_smeplus['NPK_RSH'] = np.where(hierarchy_smeplus['NAME_RSH'].str.contains('NO MANAGER'),0,hierarchy_smeplus['NPK_RSH'])
hierarchy_smeplus['NPK_RSH'] = np.where(hierarchy_smeplus['NPK_RSH'].isna(),0,hierarchy_smeplus['NPK_RSH'])
hierarchy_smeplus['NPK_RSH'] = hierarchy_smeplus['NPK_RSH'].astype('int64')

#### 2.2.3 Remove VACANT names

In [40]:
hierarchy_smeplus['NAME_RO'] = np.where(hierarchy_smeplus['NAME_RO'].str.contains('|'.join(remove)),
                                         "",hierarchy_smeplus['NAME_RO'])
hierarchy_smeplus['NAME_ASH'] = np.where(hierarchy_smeplus['NAME_ASH'].str.contains('|'.join(remove)),
                                         "",hierarchy_smeplus['NAME_ASH'])
hierarchy_smeplus['NAME_RSH'] = np.where(hierarchy_smeplus['NAME_RSH'].str.contains('|'.join(remove)),
                                         "",hierarchy_smeplus['NAME_RSH'])

#### 2.2.4 Remove duplicates and make list of all NPKs in hierarchy

In [41]:
#Drop duplicates (due to vacant RO roles)
hierarchy_smeplus_clean = hierarchy_smeplus.drop_duplicates()
hierarchy_smeplus_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 63
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   REGION_RSH  61 non-null     object
 1   NPK_RSH     61 non-null     int64
 2   NAME_RSH    61 non-null     object
 3   AREA_ASH    61 non-null     object
 4   NPK_ASH     61 non-null     int64
 5   NAME_ASH    61 non-null     object
 6   NPK_RO      61 non-null     int64
 7   NAME_RO     61 non-null     object
 8   BRANCH_RO   60 non-null     object
dtypes: int64(3), object(6)
memory usage: 4.8+ KB

In [42]:
ro_list_smeplus = hierarchy_smeplus[['NPK_RO','NAME_RO']]
ro_list_smeplus['JABATAN'] = 'RELATIONSHIP OFFICER'
ro_list_smeplus.columns = ['NPK','NAMA','JABATAN']

ro_list_smeplus=ro_list_smeplus[~ro_list_smeplus['NPK'].isna()]
ro_list_smeplus = ro_list_smeplus.drop_duplicates()
ro_list_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, 0 to 62
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NPK      54 non-null     int64
 1   NAMA     54 non-null     object
 2   JABATAN  54 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.7+ KB

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2523242801.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ro_list_smeplus['JABATAN'] = 'RELATIONSHIP OFFICER'

## 3. Preprocessing CL Lending - RSME

[back](#back)

In [43]:
crs_smer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8262 entries, 0 to 8261
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      8262 non-null   int64
 1   RC_BR_CD   8262 non-null   int64
 2   GCIF_NO    8262 non-null   object
 3   PRD_TP     8262 non-null   int64
 4   NPK_REFF   8262 non-null   int64
 5   NPK_MAINT  8262 non-null   int64
 6   AREA       8221 non-null   object
 7   REGION     8221 non-null   object
 8   BRANCH     8221 non-null   object
dtypes: int64(5), object(4)
memory usage: 581.1+ KB

In [44]:
#BR_CD as type STR untuk mapping AREA
crs_smer['BR_CD'] = crs_smer['BR_CD'].astype(str)
crs_smer['RC_BR_CD'] = crs_smer['RC_BR_CD'].astype(str)

crs_smer['NPK_MAINT'] = np.where(crs_smer['NPK_MAINT'].isna(),
                                0,
                                crs_smer['NPK_MAINT'])
crs_smer['NPK_MAINT'] = crs_smer['NPK_MAINT'].astype('int64')

crs_smer['NPK_REFF'] = np.where(crs_smer['NPK_REFF'].isna(),
                                0,
                                crs_smer['NPK_REFF'])
crs_smer['NPK_REFF'] = crs_smer['NPK_REFF'].astype('int64')

### 3.1 Multi NPK Handling

In [45]:
#PRIORITAS: PRK > PPB > PB

In [46]:
crs_smer[crs_smer['NPK_REFF']==43269].count()

BR_CD        122
RC_BR_CD     122
GCIF_NO      122
PRD_TP       122
NPK_REFF     122
NPK_MAINT    122
AREA         122
REGION       122
BRANCH       122
dtype: int64

In [47]:
product_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PRD_TP        128 non-null    int64
 1   FASILITAS     128 non-null    object
 2   CLASS         128 non-null    object
 3   STATUS        124 non-null    object
 4   Installments  41 non-null     object
dtypes: int64(1), object(4)
memory usage: 5.1+ KB

In [48]:
crs_smer = crs_smer.merge(product_map[['PRD_TP','CLASS']],on='PRD_TP', how='left')

crs_smer['FASILITAS'] = np.where(crs_smer['CLASS'].str.contains('PPB'),'PPB',
                                 np.where((crs_smer['CLASS']=='PB Syariah') | (crs_smer['CLASS']=='PB'), 'PB',
                                np.where(crs_smer['CLASS'].str.contains('PRK'),'PRK', crs_smer['CLASS'])))

crs_smer = crs_smer.drop_duplicates()
crs_smer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7366 entries, 0 to 8261
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      7366 non-null   object
 1   RC_BR_CD   7366 non-null   object
 2   GCIF_NO    7366 non-null   object
 3   PRD_TP     7366 non-null   int64
 4   NPK_REFF   7366 non-null   int64
 5   NPK_MAINT  7366 non-null   int64
 6   AREA       7329 non-null   object
 7   REGION     7329 non-null   object
 8   BRANCH     7329 non-null   object
 9   CLASS      3143 non-null   object
 10  FASILITAS  7366 non-null   object
dtypes: int64(3), object(8)
memory usage: 690.6+ KB

In [49]:
gcifs_have_0 = crs_smer[crs_smer['NPK_MAINT'] == 0][['GCIF_NO']].drop_duplicates()
gcifs_non0 = crs_smer[~(crs_smer['GCIF_NO'].isin(gcifs_have_0['GCIF_NO']))]

#Check
len(gcifs_have_0['GCIF_NO'].drop_duplicates())+len(gcifs_non0['GCIF_NO'].drop_duplicates()) == len(crs_smer['GCIF_NO'].drop_duplicates())

True

In [50]:
#crs_smer_non0[crs_smer_non0['NPK_REFF']==43269]

In [51]:
crs_smer_0 = crs_smer[crs_smer['GCIF_NO'].isin(gcifs_have_0['GCIF_NO'])]
crs_smer_non0 = crs_smer[crs_smer['GCIF_NO'].isin(gcifs_non0['GCIF_NO'])]

#Check
len(crs_smer_0)+len(crs_smer_non0) == len(crs_smer)

True

In [52]:
#TEST CASES
# 1. Multiple NPK, contains 0 : G009118761, G700797640
# 2. Multiple NPK, no 0 : G008665739,G001934074
# print(crs_smer_0[crs_smer_0['GCIF_NO']=='G008665739'])
# print(crs_smer_non0[crs_smer_non0['GCIF_NO']=='G008665739'])
# crs_smer_0[crs_smer_0['GCIF_NO']=='G310297858']

In [53]:
#CHECK: NO DUPLICATES BETWEEN 2 CASE HANDLING
# crs_smer_0[crs_smer_0.isin(crs_smer_non0)].value_counts(dropna=False)
crs_smer_non0[crs_smer_non0.isin(crs_smer_0)].value_counts(dropna=False)

BR_CD  RC_BR_CD  GCIF_NO  PRD_TP  NPK_REFF  NPK_MAINT  AREA  REGION  BRANCH  CLASS  FASILITAS
NaN    NaN       NaN      NaN     NaN       NaN        NaN   NaN     NaN     NaN    NaN          7317
Name: count, dtype: int64

In [54]:
test_non0_gcifs = crs_smer_0[crs_smer_0['NPK_MAINT'] != 0]['GCIF_NO'].drop_duplicates()
test_non0 = crs_smer_0[crs_smer_0['GCIF_NO'].isin(test_non0_gcifs)]
test_0 = crs_smer_0[~(crs_smer_0['GCIF_NO'].isin(test_non0['GCIF_NO']))]

print(len(test_non0['GCIF_NO'].drop_duplicates()))
print(len(test_non0))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(test_0))

print(len(test_non0['GCIF_NO'].drop_duplicates()) + len(test_0['GCIF_NO'].drop_duplicates()) == len(crs_smer_0['GCIF_NO'].drop_duplicates()))
print(len(test_non0)+ len(test_0) == len(crs_smer_0))

9
20
27
29
True
True

In [55]:
test_0[test_0['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

,BR_CD,RC_BR_CD,GCIF_NO,PRD_TP,NPK_REFF,NPK_MAINT,AREA,REGION,BRANCH,CLASS,FASILITAS
5987,731,7924731,G210992178,293,0,0,MEDAN UTARA,SUMATERA UTARA,MEDAN UTARA,NaN,PPB
5988,731,7924731,G210992178,892,0,0,MEDAN UTARA,SUMATERA UTARA,MEDAN UTARA,PB Syariah,PB
1201,38,123038,G802406025,20,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,NaN,PPB
7063,760,7925760,G802406025,892,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,PB Syariah,PB

In [56]:
test_0['NPK'] = test_0['NPK_REFF']
test_non0 = test_non0[(test_non0['NPK_MAINT'] != 0)]

#Check
print(len(crs_smer['GCIF_NO'].drop_duplicates()) == len(test_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(test_non0['GCIF_NO'].drop_duplicates()) +
                                                    len(crs_smer_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smer['GCIF_NO'].drop_duplicates()) == len(crs_smer_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(crs_smer_non0['GCIF_NO'].drop_duplicates()))

print(len(crs_smer['GCIF_NO'].drop_duplicates()))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(test_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smer_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smer_0['GCIF_NO'].drop_duplicates()))

True
True
5522
27
9
5486
36

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\4032202586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_0['NPK'] = test_0['NPK_REFF']

In [57]:
crs_smer_non0 = pd.concat([crs_smer_non0,test_non0],axis=0)
crs_smer_non0 = crs_smer_non0.sort_values(['GCIF_NO','FASILITAS'])
#CASES: G410127773,G009118761,G700797640,G001934074
#PRIORITAS: PRK > PPB > PB
crs_smer_non0[crs_smer_non0['GCIF_NO']=='G410127773']

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_REFF, NPK_MAINT, AREA, REGION, BRANCH, CLASS, FASILITAS]
Index: []

In [58]:
crs_smer_non0_final = crs_smer_non0.drop_duplicates('GCIF_NO',keep='last')
crs_smer_non0_final['NPK'] = crs_smer_non0_final['NPK_MAINT']

crs_smer_non0_final[crs_smer_non0_final['GCIF_NO']=='G410127773']

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3342981128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crs_smer_non0_final['NPK'] = crs_smer_non0_final['NPK_MAINT']

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_REFF, NPK_MAINT, AREA, REGION, BRANCH, CLASS, FASILITAS, NPK]
Index: []

In [59]:
print(len(crs_smer['GCIF_NO'].drop_duplicates()) == len(test_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(crs_smer_non0_final['GCIF_NO'].drop_duplicates()))

print(len(crs_smer['GCIF_NO'].drop_duplicates()))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(crs_smer_non0_final['GCIF_NO'].drop_duplicates()))

True
5522
27
5495

In [60]:
crs_smer_clean = pd.concat([test_0,crs_smer_non0_final],axis=0)
crs_smer_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5524 entries, 307 to 2408
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      5524 non-null   object
 1   RC_BR_CD   5524 non-null   object
 2   GCIF_NO    5524 non-null   object
 3   PRD_TP     5524 non-null   int64
 4   NPK_REFF   5524 non-null   int64
 5   NPK_MAINT  5524 non-null   int64
 6   AREA       5495 non-null   object
 7   REGION     5495 non-null   object
 8   BRANCH     5495 non-null   object
 9   CLASS      1794 non-null   object
 10  FASILITAS  5524 non-null   object
 11  NPK        5524 non-null   int64
dtypes: int64(4), object(8)
memory usage: 561.0+ KB

In [61]:
crs_smer_clean = crs_smer_clean[~crs_smer_clean['GCIF_NO'].isna()]

In [62]:
crs_smer_clean[crs_smer_clean['NPK_REFF']==43269]

,BR_CD,RC_BR_CD,GCIF_NO,PRD_TP,NPK_REFF,NPK_MAINT,AREA,REGION,BRANCH,CLASS,FASILITAS,NPK
939,26,405026,G006603542,20,43269,40825,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,40825
861,22,404022,G007653215,20,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,43706
862,22,404022,G008088569,20,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,43706
1125,36,404036,G008961062,107,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,PPB,PPB,43706
2951,145,405145,G009548165,20,43269,40825,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,40825
...,...,...,...,...,...,...,...,...,...,...,...,...
2934,145,405145,G901186015,20,43269,40825,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,40825
5170,596,405596,G907209050,112,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,PB,PB,43706
2945,145,405145,G908566128,102,43269,40825,SUMMITMAS,JAKARTA 1,SUMMITMAS,PPB,PPB,40825
7366,774,7902774,G909270027,892,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,PB Syariah,PB,43706
873,22,404022,G910618982,20,43269,43706,SUMMITMAS,JAKARTA 1,SUMMITMAS,NaN,PPB,43706

In [63]:
crs_smer_clean

,BR_CD,RC_BR_CD,GCIF_NO,PRD_TP,NPK_REFF,NPK_MAINT,AREA,REGION,BRANCH,CLASS,FASILITAS,NPK
307,4,101004,G806163010,112,0,0,MEDAN BARAT,SUMATERA UTARA,MEDAN BARAT,PB,PB,0
536,7,801007,G109043232,112,0,0,BALIKPAPAN & SAMARINDA,KALIMANTAN,BALIKPAPAN & SAMARINDA,PB,PB,0
1118,35,604035,G405792227,20,0,0,SEMARANG,JAWA TENGAH,SEMARANG,NaN,PPB,0
1142,38,123038,G805146529,112,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,PB,PB,0
1201,38,123038,G802406025,20,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,NaN,PPB,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2064,67,812067,G910788959,70,37887,42740,SULAWESI,SULAWESI & IBT,SULAWESI,NaN,PPB,42740
5009,577,604577,G910789387,112,43377,41690,SEMARANG,JAWA TENGAH,SEMARANG,PB,PB,41690
6519,741,7902741,G910796440,293,41863,38874,FATMAWATI,JAKARTA 1,FATMAWATI,NaN,PPB,38874
7603,781,7915781,G910809250,747,35088,42929,SURABAYA,"JATIM, BALI & NUSRA",SURABAYA,PPB Syariah,PPB,42929
2408,91,704091,G910970938,112,28396,37504,JEMUR ANDAYANI,"JATIM, BALI & NUSRA",JEMUR ANDAYANI,PB,PB,37504

In [64]:
crs_smer_clean['AREA'].unique()

array(['MEDAN BARAT', 'BALIKPAPAN & SAMARINDA', 'SEMARANG', 'PALEMBANG',
       'JAMBI', 'BANJARMASIN', 'KELAPA GADING', 'MEDAN UTARA',
       'YOGYAKARTA', 'KOTA', 'BANDAR LAMPUNG', nan, 'JAWA BARAT 3',
       'MT HARYONO', 'JAWA BARAT 4', 'BEKASI', 'SUMMITMAS', 'PONTIANAK',
       'BOGOR', 'SURABAYA', 'THAMRIN', 'PEKANBARU', 'EKAJIWA',
       'JAWA BARAT 1', 'BATAM', 'MALANG', 'SULAWESI',
       'INDONESIA BAG. TIMUR', 'BALI NUSRA', 'PLUIT', 'SIDOARJO',
       'PURI KENCANA', 'JEMUR ANDAYANI', 'FATMAWATI', 'ROXY',
       'LIPPO CIKARANG', 'JAWA BARAT 2', 'BUMI SERPONG DAMAI',
       'CEMPAKA MAS', 'KARAWANG', 'SOLO', 'TANGERANG'], dtype=object)

In [65]:
crs_smer_with_area = crs_smer_clean.rename(columns = {'Area_SME': 'AREA',
                                                         'BRANCH': 'BRANCH',
                                                         'REGION_2024': 'REGION',
                                                         'NPK': 'NPK_FINAL'})

In [66]:
#CHECK CRS CL: ~5800 rows
crs_smer_with_area.info()

#crs_smer_with_area[crs_smer_with_area['GCIF_NO']=='G002939841']

<class 'pandas.core.frame.DataFrame'>
Index: 5524 entries, 307 to 2408
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      5524 non-null   object
 1   RC_BR_CD   5524 non-null   object
 2   GCIF_NO    5524 non-null   object
 3   PRD_TP     5524 non-null   int64
 4   NPK_REFF   5524 non-null   int64
 5   NPK_MAINT  5524 non-null   int64
 6   AREA       5495 non-null   object
 7   REGION     5495 non-null   object
 8   BRANCH     5495 non-null   object
 9   CLASS      1794 non-null   object
 10  FASILITAS  5524 non-null   object
 11  NPK_FINAL  5524 non-null   int64
dtypes: int64(4), object(8)
memory usage: 561.0+ KB

In [67]:
#NO DUPLICATES CHECKPOINT
crs_smer_with_area[crs_smer_with_area['GCIF_NO'].duplicated(keep=False)]

,BR_CD,RC_BR_CD,GCIF_NO,PRD_TP,NPK_REFF,NPK_MAINT,AREA,REGION,BRANCH,CLASS,FASILITAS,NPK_FINAL
1201,38,123038,G802406025,20,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,NaN,PPB,0
5987,731,7924731,G210992178,293,0,0,MEDAN UTARA,SUMATERA UTARA,MEDAN UTARA,NaN,PPB,0
5988,731,7924731,G210992178,892,0,0,MEDAN UTARA,SUMATERA UTARA,MEDAN UTARA,PB Syariah,PB,0
7063,760,7925760,G802406025,892,0,0,PALEMBANG,SUMATERA SELATAN,PALEMBANG,PB Syariah,PB,0

In [68]:
crs_smer_with_area = crs_smer_with_area.drop_duplicates('GCIF_NO',keep='first')

In [69]:
crs_smer_with_area[crs_smer_with_area['NPK_REFF']==43269].count()

BR_CD        72
RC_BR_CD     72
GCIF_NO      72
PRD_TP       72
NPK_REFF     72
NPK_MAINT    72
AREA         72
REGION       72
BRANCH       72
CLASS        34
FASILITAS    72
NPK_FINAL    72
dtype: int64

## 4. Preprocessing CL Lending - SME+

In [70]:
crs_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      1250 non-null   int64
 1   RC_BR_CD   1250 non-null   int64
 2   GCIF_NO    1250 non-null   object
 3   PRD_TP     1250 non-null   int64
 4   NPK_MAINT  1250 non-null   int64
 5   NPK_REFF   1250 non-null   int64
 6   AREA       1221 non-null   object
 7   REGION     1221 non-null   object
 8   BRANCH     1221 non-null   object
dtypes: int64(5), object(4)
memory usage: 88.0+ KB

In [71]:
#BR_CD as type STR untuk mapping AREA nanti
crs_smeplus['BR_CD'] = crs_smeplus['BR_CD'].astype(str)
crs_smeplus['RC_BR_CD'] = crs_smeplus['RC_BR_CD'].astype(str)

crs_smeplus['NPK_MAINT'] = np.where(crs_smeplus['NPK_MAINT'].isna(),
                                0,
                                crs_smeplus['NPK_MAINT'])
crs_smeplus['NPK_MAINT'] = crs_smeplus['NPK_MAINT'].astype('int64')

crs_smeplus['NPK_REFF'] = np.where(crs_smeplus['NPK_REFF'].isna(),
                                0,
                                crs_smeplus['NPK_REFF'])
crs_smeplus['NPK_REFF'] = crs_smeplus['NPK_REFF'].astype('int64')

### 4.1 Multi NPK Handling

In [72]:
crs_smeplus = crs_smeplus.merge(product_map[['PRD_TP','CLASS']],on='PRD_TP',
                           how='left')
# crs_smeplus_1 = crs_smeplus_1.drop(columns = {'FASILITAS','FAC_TP'})
crs_smeplus['FASILITAS'] = np.where(crs_smeplus['CLASS'].str.contains('PPB'),'PPB',
                                  np.where((crs_smeplus['CLASS']=='PB Syariah') | (crs_smeplus['CLASS']=='PB'), 'PB',
                                  np.where(crs_smeplus['CLASS'].str.contains('PRK'),'PRK', crs_smeplus['CLASS'])))

crs_smeplus = crs_smeplus.drop_duplicates()
crs_smeplus = crs_smeplus[~crs_smeplus['GCIF_NO'].isna()]
crs_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      1000 non-null   object
 1   RC_BR_CD   1000 non-null   object
 2   GCIF_NO    1000 non-null   object
 3   PRD_TP     1000 non-null   int64
 4   NPK_MAINT  1000 non-null   int64
 5   NPK_REFF   1000 non-null   int64
 6   AREA       974 non-null    object
 7   REGION     974 non-null    object
 8   BRANCH     974 non-null    object
 9   CLASS      519 non-null    object
 10  FASILITAS  1000 non-null   object
dtypes: int64(3), object(8)
memory usage: 93.8+ KB

In [73]:
gcifs_have_0 = crs_smeplus[crs_smeplus['NPK_MAINT'] == 0][['GCIF_NO']].drop_duplicates()
gcifs_non0 = crs_smeplus[~(crs_smeplus['GCIF_NO'].isin(gcifs_have_0['GCIF_NO']))]

#Check
len(gcifs_have_0['GCIF_NO'].drop_duplicates())+len(gcifs_non0['GCIF_NO'].drop_duplicates()) == len(crs_smeplus['GCIF_NO'].drop_duplicates())

True

In [74]:
crs_smeplus_0 = crs_smeplus[crs_smeplus['GCIF_NO'].isin(gcifs_have_0['GCIF_NO'])]
crs_smeplus_non0 = crs_smeplus[crs_smeplus['GCIF_NO'].isin(gcifs_non0['GCIF_NO'])]

#Check
len(crs_smeplus_0)+len(crs_smeplus_non0) == len(crs_smeplus)

True

In [75]:
#TEST CASES
# 1. Multiple NPK, contains 0 : G009118761, G700797640
# 2. Multiple NPK, no 0 : G008665739,G001934074
print(crs_smeplus_0[crs_smeplus_0['GCIF_NO']=='G008665739'])
print(crs_smeplus_non0[crs_smeplus_non0['GCIF_NO']=='G008665739'])

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS]
Index: []
Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS]
Index: []

In [76]:
#CHECK NO DUPLICATES BETWEEN 2 CASE HANDLING
# crs_smeplus_0[crs_smeplus_0.isin(crs_smeplus_non0)].value_counts(dropna=False)
crs_smeplus_non0[crs_smeplus_non0.isin(crs_smeplus_0)].value_counts(dropna=False)

BR_CD  RC_BR_CD  GCIF_NO  PRD_TP  NPK_MAINT  NPK_REFF  AREA  REGION  BRANCH  CLASS  FASILITAS
NaN    NaN       NaN      NaN     NaN        NaN       NaN   NaN     NaN     NaN    NaN          989
Name: count, dtype: int64

In [77]:
#HANDLING CASE 1: GCIFS with 0 NPK
#CASE 1.1 : 0s only G403223647 -> NPK = NPK_REFF
#CASE 1.2 : Multiple NPK, contains 0 : G410127773 (multi NPK) -> remove yang NPK_MAINT = 0 lalu aplikasikan logic non0, 
#           G009118761 & G700797640 (double NPK) -> 
# crs_smeplus_0[crs_smeplus_0['GCIF_NO']=='G700797640']

In [78]:
test_non0_gcifs = crs_smeplus_0[crs_smeplus_0['NPK_MAINT'] != 0]['GCIF_NO'].drop_duplicates()
test_non0 = crs_smeplus_0[crs_smeplus_0['GCIF_NO'].isin(test_non0_gcifs)]
test_0 = crs_smeplus_0[~(crs_smeplus_0['GCIF_NO'].isin(test_non0['GCIF_NO']))]

print(len(test_non0['GCIF_NO'].drop_duplicates()))
print(len(test_non0))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(test_0))

print(len(test_non0['GCIF_NO'].drop_duplicates()) + len(test_0['GCIF_NO'].drop_duplicates()) == len(crs_smeplus_0['GCIF_NO'].drop_duplicates()))
print(len(test_non0)+ len(test_0) == len(crs_smeplus_0))

3
11
0
0
True
True

In [79]:
test_0[test_0['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS]
Index: []

In [80]:
test_0['NPK'] = test_0['NPK_REFF']
test_non0 = test_non0[(test_non0['NPK_MAINT'] != 0)]

#CHECK
print(len(crs_smeplus['GCIF_NO'].drop_duplicates()) == len(test_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(test_non0['GCIF_NO'].drop_duplicates()) +
                                                    len(crs_smeplus_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smeplus['GCIF_NO'].drop_duplicates()) == len(crs_smeplus_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(crs_smeplus_non0['GCIF_NO'].drop_duplicates()))

print(len(crs_smeplus['GCIF_NO'].drop_duplicates()))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(test_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smeplus_non0['GCIF_NO'].drop_duplicates()))
print(len(crs_smeplus_0['GCIF_NO'].drop_duplicates()))

True
True
572
0
3
569
3

In [81]:
crs_smeplus_non0 = pd.concat([crs_smeplus_non0,test_non0], axis=0)
crs_smeplus_non0 = crs_smeplus_non0.sort_values(['GCIF_NO','FASILITAS'])
#CASES: G410127773,G009118761,G700797640,G001934074
#PRIORITAS: PRK > PPB > PB
crs_smeplus_non0[crs_smeplus_non0['GCIF_NO']=='G410127773']

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS]
Index: []

In [82]:
crs_smeplus_non0_final = crs_smeplus_non0.drop_duplicates('GCIF_NO',keep='last')
crs_smeplus_non0_final['NPK'] = crs_smeplus_non0_final['NPK_MAINT']

crs_smeplus_non0_final[crs_smeplus_non0_final['GCIF_NO']=='G410127773']

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2050753870.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crs_smeplus_non0_final['NPK'] = crs_smeplus_non0_final['NPK_MAINT']

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS, NPK]
Index: []

In [83]:
print(len(crs_smeplus['GCIF_NO'].drop_duplicates()) == len(test_0['GCIF_NO'].drop_duplicates()) + 
                                                    len(crs_smeplus_non0_final['GCIF_NO'].drop_duplicates()))

print(len(crs_smeplus['GCIF_NO'].drop_duplicates()))
print(len(test_0['GCIF_NO'].drop_duplicates()))
print(len(crs_smeplus_non0_final['GCIF_NO'].drop_duplicates()))

True
572
0
572

In [84]:
crs_smeplus_clean = pd.concat([test_0,crs_smeplus_non0_final], axis=0)

In [85]:
crs_smeplus_clean[crs_smeplus_clean['NPK_MAINT'].isna()]

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS, NPK]
Index: []

In [86]:
crs_smeplus_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 572 entries, 707 to 246
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      572 non-null    object
 1   RC_BR_CD   572 non-null    object
 2   GCIF_NO    572 non-null    object
 3   PRD_TP     572 non-null    int64
 4   NPK_MAINT  572 non-null    int64
 5   NPK_REFF   572 non-null    int64
 6   AREA       562 non-null    object
 7   REGION     562 non-null    object
 8   BRANCH     562 non-null    object
 9   CLASS      283 non-null    object
 10  FASILITAS  572 non-null    object
 11  NPK        572 non-null    int64
dtypes: int64(4), object(8)
memory usage: 58.1+ KB

### 4.2 Add Area

In [87]:
def area_smeplus_cl(crs):

    if crs['BRANCH'] in ['FATMAWATI','THAMRIN','MT HARYONO']:
        return 'JAKARTA 1A'

    elif crs['BRANCH'] in ['ROXY MAS','ROXY','SUMMITMAS','CEMPAKA MAS']:
        return 'JAKARTA 1B'

    elif crs['BRANCH'] in ['KOTA','KELAPA GADING']:
        return 'JAKARTA 2A'

    elif crs['BRANCH'] in ['EKAJIWA','PLUIT','PURI KENCANA']:
        return 'JAKARTA 2B'

    elif crs['BRANCH'] in ['BANDAR LAMPUNG','BANDAR JAYA','METRO LAMPUNG','BANDAR BENGKULU','TANJUNG KARANG']:
        return 'JAKARTA 2C'

    elif crs['BRANCH'] in ['ALAM SUTRA','SUMMARECON SERPONG','TANGERANG','BOGOR']:
        return 'JAKARTA 3A'

    elif crs['BRANCH'] in ['LIPPO CIKARANG','KARAWANG','BEKASI']:
        return 'JAKARTA 3B'

    elif crs['BRANCH'] in ['KUPANG','DENPASAR','UDAYANA DENPASAR','SUNSET ROAD','MATARAM','JL PEMUDA SURABAYA','MAYJEN SUNGKONO']:
        return 'JATIM A'

    elif crs['BRANCH'] in ['JEMUR ANDAYANI','MALANG','JEMBER','KEDIRI','GRESIK']:
        return 'JATIM B'

    elif crs['BRANCH'] in ['RE MARTADINATA','CIREBON','TASIKMALAYA','GARUT']:
        return 'JAWA BARAT A'

    elif crs['BRANCH'] in ['ASIA AFRIKA','SUKABUMI','KOPO PLAZA']:
        return 'JAWA BARAT B'

    elif crs['BRANCH'] in ['TEGAL','PEKALONGAN','SEMARANG']:
        return 'JAWA TENGAH 1'

    elif crs['BRANCH'] in ['PURWOKERTO','YOGYAKARTA','MAGELANG','SOLO']:
        return 'JAWA TENGAH 2'

    elif crs['BRANCH'] in ['MAKASAR','PALU','KENDARI']:
        return 'SULAWESI'

    elif crs['BRANCH'] in ['MANADO','GORONTALO','JAYAPURA','SORONG','TERNATE','AMBON','MAKASAR']:
        return 'INDONESIA BAG. TIMUR'

    elif crs['BRANCH'] == 'MEDAN':
        return 'SUMATERA UTARA 1'

    elif crs['BRANCH'] in ['PALANG MERAH','RANTAU PRAPAT','KCP THAMRIN']:
        return 'SUMATERA UTARA 2'

    elif crs['BRANCH'] in ['BATAM','PEKANBARU','PADANG']:
        return 'SUMATERA UTARA 3'

    elif crs['BRANCH'] in ['PALEMBANG','JAMBI','MUARA BUNGO']:
        return 'SUMATERA SELATAN'

    elif crs['BRANCH'] in ['PONTIANAK','SAMARINDA']:
        return 'KALIMANTAN A'

    elif crs['BRANCH'] in ['BANJARMASIN','SAMPIT','BALIKPAPAN','SAMARINDA','TARAKAN']:
        return 'KALIMANTAN B'

crs_smeplus_clean['AREA'] = crs_smeplus_clean.apply(area_smeplus_cl, axis=1)

In [88]:
#ERROR CHECKING CRS CL: AREA NA?
crs_smeplus_clean[crs_smeplus_clean['AREA'].isna()][['BRANCH']].value_counts()

BRANCH
SURABAYA                  43
MEDAN BARAT               36
JAWA BARAT 1              23
BALI NUSRA                17
MEDAN UTARA               16
JAWA BARAT 4              12
JAWA BARAT 3              11
SULAWESI                  11
JAWA BARAT 2               8
SIDOARJO                   8
BUMI SERPONG DAMAI         7
INDONESIA BAG. TIMUR       4
BALIKPAPAN & SAMARINDA     2
Name: count, dtype: int64

In [89]:
crs_smeplus_with_area = crs_smeplus_clean.rename(columns = {'BRANCH': 'BRANCH',
                                                         'REGION_2024': 'REGION'
                                                           })

In [90]:
#CHECK: ~600 rows
crs_smeplus_with_area.info()

<class 'pandas.core.frame.DataFrame'>
Index: 572 entries, 707 to 246
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BR_CD      572 non-null    object
 1   RC_BR_CD   572 non-null    object
 2   GCIF_NO    572 non-null    object
 3   PRD_TP     572 non-null    int64
 4   NPK_MAINT  572 non-null    int64
 5   NPK_REFF   572 non-null    int64
 6   AREA       364 non-null    object
 7   REGION     562 non-null    object
 8   BRANCH     562 non-null    object
 9   CLASS      283 non-null    object
 10  FASILITAS  572 non-null    object
 11  NPK        572 non-null    int64
dtypes: int64(4), object(8)
memory usage: 58.1+ KB

## 5. Preprocessing NCL Lending - RSME

In [91]:
crs_smer_ncl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3349 entries, 0 to 3348
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BR_CD          3349 non-null   int64
 1   RC_CD          3349 non-null   int64
 2   RC_BR_CD       3349 non-null   int64
 3   GCIF_NO        3348 non-null   object
 4   CIF_NO         3349 non-null   object
 5   NOTE_NO        2887 non-null   float64
 6   PRD_TP         3314 non-null   object
 7   FCLT_TP        556 non-null    float64
 8   ORG_LMT_AMT    3349 non-null   float64
 9   CURR_LMT_AMT   3349 non-null   float64
 10  BAL            3349 non-null   float64
 11  CURR_INT_RT    3349 non-null   float64
 12  B2B_FLAG       564 non-null    object
 13  CLCT_RTNG_FCL  564 non-null    float64
 14  PASTDUE_DAYS   3349 non-null   int64
 15  TGL_CAIR       3318 non-null   float64
 16  TGL_JT_2       3349 non-null   int64
 17  STATUS         3349 non-null   int64
 18  AGREE_ID       3349 non-null   object
 19  REF_AGREE_ID   3349 non-null   object
 20  NPK_REFF       553 non-null    float64
 21  NPK_MAINT      553 non-null    float64
 22  PRD_SEGMENT    3349 non-null   int64
 23  DIRECT_YN      3349 non-null   object
 24  AREA           3030 non-null   object
 25  REGION         3030 non-null   object
 26  SEGMENT        3349 non-null   object
dtypes: float64(10), int64(7), object(10)
memory usage: 706.6+ KB

### 5.1 Take GCIFS with NCL facilities only from CRS NCL

In [92]:
crs_smer_ncl['NPK_MAINT'] = np.where(crs_smer_ncl['NPK_MAINT'].isna(),
                                0,
                                crs_smer_ncl['NPK_MAINT'])
crs_smer_ncl['NPK_MAINT'] = crs_smer_ncl['NPK_MAINT'].astype('int64')

crs_smer_ncl['NPK_REFF'] = np.where(crs_smer_ncl['NPK_REFF'].isna(),
                                0,
                                crs_smer_ncl['NPK_REFF'])
crs_smer_ncl['NPK_REFF'] = crs_smer_ncl['NPK_REFF'].astype('int64')
# crs_smer_ncl['NPK_MAINT'].value_counts(dropna=False)

In [93]:
#Create list GCIF_NO that exist in crs
crs_GCIF_rsme = crs_smer_with_area['GCIF_NO'].tolist()
#Create NCL data from crs_smer_ncl which not yet included in crs 
ncl_only_crs_smer = crs_smer_ncl[~crs_smer_ncl['GCIF_NO'].isin(crs_GCIF_rsme)]
ncl_only_crs_smer = ncl_only_crs_smer[~ncl_only_crs_smer['GCIF_NO'].isna()]
ncl_only_crs_smer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2150 entries, 1 to 3347
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BR_CD          2150 non-null   int64
 1   RC_CD          2150 non-null   int64
 2   RC_BR_CD       2150 non-null   int64
 3   GCIF_NO        2150 non-null   object
 4   CIF_NO         2150 non-null   object
 5   NOTE_NO        1766 non-null   float64
 6   PRD_TP         2136 non-null   object
 7   FCLT_TP        225 non-null    float64
 8   ORG_LMT_AMT    2150 non-null   float64
 9   CURR_LMT_AMT   2150 non-null   float64
 10  BAL            2150 non-null   float64
 11  CURR_INT_RT    2150 non-null   float64
 12  B2B_FLAG       231 non-null    object
 13  CLCT_RTNG_FCL  231 non-null    float64
 14  PASTDUE_DAYS   2150 non-null   int64
 15  TGL_CAIR       2137 non-null   float64
 16  TGL_JT_2       2150 non-null   int64
 17  STATUS         2150 non-null   int64
 18  AGREE_ID       2150 non-null   object
 19  REF_AGREE_ID   2150 non-null   object
 20  NPK_REFF       2150 non-null   int64
 21  NPK_MAINT      2150 non-null   int64
 22  PRD_SEGMENT    2150 non-null   int64
 23  DIRECT_YN      2150 non-null   object
 24  AREA           1848 non-null   object
 25  REGION         1848 non-null   object
 26  SEGMENT        2150 non-null   object
dtypes: float64(8), int64(9), object(10)
memory usage: 470.3+ KB

### 6.2 Ambil fasilitas terbaru untuk masing-masing GCIF (karena memiliki BRANCH & REGION terbaru)

In [94]:
ncl_only_crs_smer_2 = ncl_only_crs_smer.sort_values('TGL_CAIR',ascending=True)
# ncl_only_crs_2[ncl_only_crs_2['GCIF_NO'] == 'G102618766'][['GCIF_NO','NPK_MAINT','TGL_CAIR']]

In [95]:
#PENDING: PAKE BR_CD YANG MANA? -> sementara order by TGL_CAIR
ncl_only_crs_smer_3 = ncl_only_crs_smer_2.drop_duplicates(['GCIF_NO'],keep='last')
# ncl_only_crs_3[ncl_only_crs_3['GCIF_NO'] == 'G102618766'][['GCIF_NO','NPK_MAINT','TGL_CAIR']]
ncl_only_crs_smer_3[ncl_only_crs_smer_3['GCIF_NO'].duplicated(keep=False)][['GCIF_NO','NPK_MAINT','TGL_CAIR']]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT, TGL_CAIR]
Index: []

### 6.3 Handling GCIF dengan Multi NPK

In [96]:
#CHECK FOR MULTI NPK GCIFS
ncl_only_crs_smer_3[(ncl_only_crs_smer_3['GCIF_NO'].duplicated(keep=False)) & ~(ncl_only_crs_smer_3['NPK_MAINT'].duplicated(keep=False))].sort_values('GCIF_NO')[['GCIF_NO','NPK_MAINT']]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT]
Index: []

In [97]:
ncl_only_crs_smer_3['BRANCH'] = crs_smer['AREA']

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3137964832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ncl_only_crs_smer_3['BRANCH'] = crs_smer['AREA']

In [98]:
ncl_only_crs_smer_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 605 entries, 2477 to 3347
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BR_CD          605 non-null    int64
 1   RC_CD          605 non-null    int64
 2   RC_BR_CD       605 non-null    int64
 3   GCIF_NO        605 non-null    object
 4   CIF_NO         605 non-null    object
 5   NOTE_NO        572 non-null    float64
 6   PRD_TP         595 non-null    object
 7   FCLT_TP        91 non-null     float64
 8   ORG_LMT_AMT    605 non-null    float64
 9   CURR_LMT_AMT   605 non-null    float64
 10  BAL            605 non-null    float64
 11  CURR_INT_RT    605 non-null    float64
 12  B2B_FLAG       93 non-null     object
 13  CLCT_RTNG_FCL  93 non-null     float64
 14  PASTDUE_DAYS   605 non-null    int64
 15  TGL_CAIR       595 non-null    float64
 16  TGL_JT_2       605 non-null    int64
 17  STATUS         605 non-null    int64
 18  AGREE_ID       605 non-null    object
 19  REF_AGREE_ID   605 non-null    object
 20  NPK_REFF       605 non-null    int64
 21  NPK_MAINT      605 non-null    int64
 22  PRD_SEGMENT    605 non-null    int64
 23  DIRECT_YN      605 non-null    object
 24  AREA           476 non-null    object
 25  REGION         476 non-null    object
 26  SEGMENT        605 non-null    object
 27  BRANCH         562 non-null    object
dtypes: float64(8), int64(9), object(11)
memory usage: 137.1+ KB

In [99]:
ncl_only_crs_smer_3 = ncl_only_crs_smer_3[['GCIF_NO','NPK_MAINT','NPK_REFF', 'REGION','BRANCH']]
ncl_only_crs_smer_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 605 entries, 2477 to 3347
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    605 non-null    object
 1   NPK_MAINT  605 non-null    int64
 2   NPK_REFF   605 non-null    int64
 3   REGION     476 non-null    object
 4   BRANCH     562 non-null    object
dtypes: int64(2), object(3)
memory usage: 28.4+ KB

In [100]:
### 6.4 Use Cust List from CRS NCL, Branch Area Mapping from XPOSE
xpose['BR_CD'] = xpose['BR_CD'].fillna(0)
xpose['BR_CD'] = xpose['BR_CD'].astype('int64')
xpose_rsme_with_area = xpose[['GCIF_NO','BR_CD','NOTE_DT']].merge(branch_map[['BRANCH CODE','AREA','REGION']], 
                                left_on=['BR_CD'],right_on=['BRANCH CODE'],how='left')
xpose_rsme_with_area = xpose_rsme_with_area[~xpose_rsme_with_area['AREA'].isna()]

xpose_rsme_with_area = xpose_rsme_with_area.sort_values('NOTE_DT',ascending=True)
xpose_rsme_with_area = xpose_rsme_with_area.drop_duplicates(['GCIF_NO'],keep='last')

xpose_rsme_with_area = xpose_rsme_with_area.drop_duplicates()
xpose_rsme_with_area = xpose_rsme_with_area[['GCIF_NO','AREA','REGION']]
xpose_rsme_with_area.info()

ncl_rsme = ncl_only_crs_smer_3[['GCIF_NO','NPK_MAINT','NPK_REFF']].merge(xpose_rsme_with_area, on = 'GCIF_NO', how ='left')
ncl_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16420 entries, 941001 to 74176
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  16419 non-null  object
 1   AREA     16420 non-null  object
 2   REGION   16420 non-null  object
dtypes: object(3)
memory usage: 513.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    605 non-null    object
 1   NPK_MAINT  605 non-null    int64
 2   NPK_REFF   605 non-null    int64
 3   AREA       203 non-null    object
 4   REGION     203 non-null    object
dtypes: int64(2), object(3)
memory usage: 23.8+ KB

In [101]:
# #Manual adjustment
# ncl_rsme['AREA'] = np.where(ncl_rsme['NPK_MAINT'] == 39739,"JAWA BARAT 1",ncl_rsme['AREA'])
# ncl_rsme['AREA'] = np.where(ncl_rsme['NPK_MAINT'] == 40549,"BEKASI",ncl_rsme['AREA'])
# ncl_rsme['AREA'] = np.where(ncl_rsme['NPK_MAINT'] == 34262,"TANGERANG",ncl_rsme['AREA'])
# ncl_rsme['AREA'] = np.where(ncl_rsme['NPK_MAINT'] == 42242,"PONTIANAK 2",ncl_rsme['AREA'])
# ncl_rsme['AREA'] = np.where(ncl_rsme['NPK_MAINT'] == 36131,"MT HARYONO",ncl_rsme['AREA'])

# ncl_rsme['REGION'] = np.where(ncl_rsme['NPK_MAINT'] == 39739,"JAWA BARAT",ncl_rsme['REGION'])
# ncl_rsme['REGION'] = np.where(ncl_rsme['NPK_MAINT'] == 40549,"JAKARTA 3",ncl_rsme['REGION'])
# ncl_rsme['REGION'] = np.where(ncl_rsme['NPK_MAINT'] == 34262,"JAKARTA 3",ncl_rsme['REGION'])
# ncl_rsme['REGION'] = np.where(ncl_rsme['NPK_MAINT'] == 42242,"KALIMANTAN",ncl_rsme['REGION'])
# ncl_rsme['REGION'] = np.where(ncl_rsme['NPK_MAINT'] == 36131,"JAKARTA 1",ncl_rsme['REGION'])

## 7. Preprocessing NCL Lending - SME+

### 7.1 Take GCIFs with NCL facilities only from CRS NCL

In [102]:
crs_smeplus_ncl['NPK_MAINT'] = np.where(crs_smeplus_ncl['NPK_MAINT'].isna(),
                                0,
                                crs_smeplus_ncl['NPK_MAINT'])
crs_smeplus_ncl['NPK_MAINT'] = crs_smeplus_ncl['NPK_MAINT'].astype('int64')

crs_smeplus_ncl['NPK_REFF'] = np.where(crs_smeplus_ncl['NPK_REFF'].isna(),
                                0,
                                crs_smeplus_ncl['NPK_REFF'])
crs_smeplus_ncl['NPK_REFF'] = crs_smeplus_ncl['NPK_REFF'].astype('int64')
# crs_smeplus_ncl['NPK_MAINT'].value_counts(dropna=False)

In [103]:
#Create list GCIF_NO that exist in crs
crs_GCIF_smeplus = crs_smeplus_with_area['GCIF_NO'].tolist()
#Create NCL data from crs_smeplus_ncl which not yet included in crs 
ncl_only_crs_smeplus = crs_smeplus_ncl[~crs_smeplus_ncl['GCIF_NO'].isin(crs_GCIF_smeplus)]
ncl_only_crs_smeplus = ncl_only_crs_smeplus[~ncl_only_crs_smeplus['GCIF_NO'].isna()]
ncl_only_crs_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 11 to 152
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BR_CD          27 non-null     int64
 1   RC_CD          27 non-null     int64
 2   RC_BR_CD       27 non-null     int64
 3   GCIF_NO        27 non-null     object
 4   CIF_NO         27 non-null     int64
 5   NOTE_NO        27 non-null     int64
 6   PRD_TP         27 non-null     int64
 7   FCLT_TP        27 non-null     int64
 8   ORG_LMT_AMT    27 non-null     float64
 9   CURR_LMT_AMT   27 non-null     float64
 10  BAL            27 non-null     float64
 11  CURR_INT_RT    27 non-null     int64
 12  B2B_FLAG       27 non-null     object
 13  CLCT_RTNG_FCL  27 non-null     int64
 14  PASTDUE_DAYS   27 non-null     int64
 15  TGL_CAIR       27 non-null     int64
 16  TGL_JT_2       27 non-null     int64
 17  STATUS         27 non-null     int64
 18  AGREE_ID       27 non-null     object
 19  REF_AGREE_ID   27 non-null     object
 20  NPK_REFF       27 non-null     int64
 21  NPK_MAINT      27 non-null     int64
 22  PRD_SEGMENT    27 non-null     int64
 23  DIRECT_YN      27 non-null     object
 24  AREA           27 non-null     object
 25  REGION         27 non-null     object
 26  SEGMENT        27 non-null     object
dtypes: float64(3), int64(16), object(8)
memory usage: 5.9+ KB

### 7.2 Ambil fasilitas terbaru untuk masing-masing GCIF (karena memiliki BRANCH & REGION terbaru)

In [104]:
ncl_only_crs_smeplus_2 = ncl_only_crs_smeplus.sort_values('TGL_CAIR',ascending=True)
# ncl_only_crs_2[ncl_only_crs_2['GCIF_NO'] == 'G102618766'][['GCIF_NO','NPK_MAINT','TGL_CAIR']]

In [105]:
#PENDING: PAKE BR_CD YANG MANA? -> sementara order by TGL_CAIR
ncl_only_crs_smeplus_3 = ncl_only_crs_smeplus_2.drop_duplicates(['GCIF_NO'],keep='last')
# ncl_only_crs_3[ncl_only_crs_3['GCIF_NO'] == 'G102618766'][['GCIF_NO','NPK_MAINT','TGL_CAIR']]
ncl_only_crs_smeplus_3[ncl_only_crs_smeplus_3['GCIF_NO'].duplicated(keep=False)][['GCIF_NO','NPK_MAINT','TGL_CAIR']]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT, TGL_CAIR]
Index: []

### 7.3 Handling GCIF dengan Multi NPK

In [106]:
ncl_only_crs_smeplus_3[(ncl_only_crs_smeplus_3['GCIF_NO'].duplicated(keep=False)) & ~(ncl_only_crs_smeplus_3['NPK_MAINT'].duplicated(keep=False))].sort_values('GCIF_NO')[['GCIF_NO','NPK_MAINT']]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT]
Index: []

In [107]:
ncl_only_crs_smeplus_3.head()

,BR_CD,RC_CD,RC_BR_CD,GCIF_NO,CIF_NO,NOTE_NO,PRD_TP,FCLT_TP,ORG_LMT_AMT,CURR_LMT_AMT,BAL,CURR_INT_RT,B2B_FLAG,CLCT_RTNG_FCL,PASTDUE_DAYS,TGL_CAIR,TGL_JT_2,STATUS,AGREE_ID,REF_AGREE_ID,NPK_REFF,NPK_MAINT,PRD_SEGMENT,DIRECT_YN,AREA,REGION,SEGMENT
50,57,814,814057,G402146567,3716724,58803,547,1,"15,500,000,000.0","15,500,000,000.0","13,960,000,000.0",0,N,1,0,20080311,20261031,1,CL16IDR05700037167240005880399999,CL16IDR05700037167240005880399999,40369,42805,20300,N,INDONESIA BAG. TIMUR,SULAWESI & IBT,SME+
134,286,305,305286,G600564041,3048381,8889806,500,1,"400,000.0","400,000.0",0.0,0,N,1,0,20201112,20261112,1,CL16IDR28600030483810888980699999,CL16USD28600030483810888980699999,39913,38059,20300,N,JAWA BARAT 1,JAWA BARAT,SME+
128,265,123,123265,G310004502,13057221,10201,547,1,"12,500,000,000.0","15,000,000,000.0","14,350,000,000.0",0,N,1,0,20230303,20260904,1,CL16IDR26500130572210001020199999,CL16IDR26500130572210001020199999,37517,40357,20300,N,PALEMBANG,SUMATERA SELATAN,SME+
90,128,1102,1102128,G608999595,12116136,20396302,547,1,"1,500,000,000.0","5,000,000,000.0","5,000,000,000.0",0,N,1,0,20230417,20260411,1,CL16IDR12800121161362039630299999,CL16IDR12800121161362039630299999,41112,40447,20300,N,KARAWANG,JAKARTA 3,SME+
57,62,811,811062,G708682901,10881514,103801,547,1,"3,500,000,000.0","7,700,000,000.0","7,300,000,000.0",0,N,1,1,20230725,20260408,1,CL16IDR06200108815140010380199999,CL16IDR06200108815140010380199999,40369,42805,20300,N,INDONESIA BAG. TIMUR,SULAWESI & IBT,SME+

In [108]:
ncl_smeplus = ncl_only_crs_smeplus_3[['GCIF_NO','NPK_MAINT','NPK_REFF']]
ncl_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 50 to 78
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    19 non-null     object
 1   NPK_MAINT  19 non-null     int64
 2   NPK_REFF   19 non-null     int64
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes

### 7.4 Use Cust List from CRS NCL, Branch Area Mapping from XPOSE

In [109]:
crs_smeplus_with_area['LOB'] = 'SME+'
branch_map_smeplus = crs_smeplus_with_area[['BR_CD','AREA','REGION','LOB']].drop_duplicates()
branch_map_smeplus[branch_map_smeplus[['BR_CD','AREA']].duplicated(keep=False)].sort_values('AREA')
branch_map_smeplus['BR_CD'] = pd.to_numeric(branch_map_smeplus['BR_CD'], errors='coerce')
branch_map_smeplus['BR_CD'] = branch_map_smeplus['BR_CD'].fillna(0)
branch_map_smeplus['BR_CD'] = branch_map_smeplus['BR_CD'].astype('int64')

In [110]:
xpose['BR_CD'] = xpose['BR_CD'].fillna(0)
xpose['BR_CD'] = xpose['BR_CD'].astype('int64')
xpose_smeplus_with_area = xpose[['GCIF_NO','BR_CD','NOTE_DT']].merge(branch_map_smeplus[['BR_CD','AREA','REGION']], 
                                on=['BR_CD'],how='left')
xpose_smeplus_with_area = xpose_smeplus_with_area[~xpose_smeplus_with_area['AREA'].isna()]

xpose_smeplus_with_area = xpose_smeplus_with_area.sort_values('NOTE_DT',ascending=True)
xpose_smeplus_with_area = xpose_smeplus_with_area.drop_duplicates(['GCIF_NO'],keep='last')

xpose_smeplus_with_area = xpose_smeplus_with_area.drop_duplicates()
xpose_smeplus_with_area = xpose_smeplus_with_area[['GCIF_NO','AREA','REGION']]
xpose_smeplus_with_area.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14799 entries, 943298 to 74416
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  14798 non-null  object
 1   AREA     14799 non-null  object
 2   REGION   14799 non-null  object
dtypes: object(3)
memory usage: 462.5+ KB

In [111]:
ncl_smeplus = ncl_only_crs_smeplus_3[['GCIF_NO','NPK_MAINT','NPK_REFF']].merge(xpose_rsme_with_area, on = 'GCIF_NO', how ='left')
ncl_smeplus.info()
# #Check: All Areas filled (for cases where NPK MAINT is not available, mapping baseline LM1 ke atas dari Area & Region)
# ncl_smeplus[(ncl_smeplus['AREA'].isna()) | (ncl_smeplus['REGION'].isna())]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    19 non-null     object
 1   NPK_MAINT  19 non-null     int64
 2   NPK_REFF   19 non-null     int64
 3   AREA       19 non-null     object
 4   REGION     19 non-null     object
dtypes: int64(2), object(3)
memory usage: 892.0+ bytes

## 8. Combine CL and NCL, add manual mapping

### 8.1 RSME

In [112]:
ncl_only_crs_smer_3[ncl_only_crs_smer_3['GCIF_NO'].duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT, NPK_REFF, REGION, BRANCH]
Index: []

In [113]:
crs_smer_with_area[crs_smer_with_area['GCIF_NO'].duplicated(keep=False)]

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_REFF, NPK_MAINT, AREA, REGION, BRANCH, CLASS, FASILITAS, NPK_FINAL]
Index: []

In [114]:
cl_rsme = crs_smer_with_area[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION','NPK_REFF']]
#cl_rsme = cl_rsme.rename(columns = {'NPK': 'NPK_MAINT'})

ncl_only_crs_smer_3['SOURCE'] = 'XPOSE'
cl_rsme['SOURCE'] = 'CRS'

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\4252384480.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cl_rsme['SOURCE'] = 'CRS'

### 8.2 SME+

In [115]:
ncl_smeplus[ncl_smeplus['GCIF_NO'].duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT, NPK_REFF, AREA, REGION]
Index: []

In [116]:
crs_smeplus_with_area[crs_smeplus_with_area['GCIF_NO'].duplicated(keep=False)]

Empty DataFrame
Columns: [BR_CD, RC_BR_CD, GCIF_NO, PRD_TP, NPK_MAINT, NPK_REFF, AREA, REGION, BRANCH, CLASS, FASILITAS, NPK, LOB]
Index: []

In [117]:
cl_smeplus = crs_smeplus_with_area[['GCIF_NO', 'NPK', 'AREA', 'REGION','NPK_REFF']]
cl_smeplus = cl_smeplus.rename(columns = {'NPK': 'NPK_MAINT'})

ncl_smeplus['NPK_REFF'] = 0
ncl_smeplus['NPK_REFF'] = ncl_smeplus['NPK_REFF'].astype('int64')
ncl_smeplus = ncl_smeplus.rename(columns = {'BRANCH': 'AREA'})
ncl_smeplus = ncl_smeplus[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION', 'NPK_REFF']]

ncl_smeplus['SOURCE'] = 'XPOSE'
cl_smeplus['SOURCE'] = 'CRS'

### 8.3 Combine

In [118]:
#CHECKPOINT
lending_rsme = pd.concat([cl_rsme,ncl_rsme],axis=0)
lending_smeplus = pd.concat([cl_smeplus,ncl_smeplus],axis=0)

print('RSME')
# print(ncl_rsme.shape)
# print(cl_rsme.shape)
# print(lending_rsme.shape)
print(len(ncl_rsme) + len(cl_rsme) == len(lending_rsme))
# print(lending_rsme.columns)

print('SMEPLUS')
# print(ncl_smeplus.shape)
# print(cl_smeplus.shape)
# print(lending_smeplus.shape)
print(len(ncl_smeplus) + len(cl_smeplus) == len(lending_smeplus))
# print(lending_smeplus.columns)

RSME
True
SMEPLUS
True

In [119]:
#Manual Adjustment - RSME
#Align antara Account Handling dengan Hierarchy nama AREA nya sama, agar semua ke-map ke ASH
lending_rsme['AREA'] = np.where(lending_rsme['AREA'].str.contains('BALI NUSRA'),
                               'BALI NUSRA 1',
                               lending_rsme['AREA'])
lending_rsme['AREA'] = np.where(lending_rsme['AREA'] == 'BANDARLAMPUNG',
                               'BANDAR LAMPUNG',
                               lending_rsme['AREA'])
lending_rsme['AREA'] = np.where(lending_rsme['AREA'].str.contains('JAWA BARAT 3'),
                               'JAWA BARAT 3',
                               lending_rsme['AREA'])
lending_rsme['AREA'] = np.where(lending_rsme['AREA'] == 'ROXY MAS',
                               'ROXY',
                               lending_rsme['AREA'])
lending_rsme['AREA'] = np.where(lending_rsme['AREA'] == 'JUANDA',
                               'KOTA',
                               lending_rsme['AREA'])

#Untuk Pontianak, dibuat mapping by Hierarchy
lending_rsme[~lending_rsme['AREA'].isin(hierarchy_smer['AREA_ASH'])]['AREA'].value_counts(dropna=False).sort_index()

AREA
BALI NUSRA 1                593
BALIKPAPAN                    4
BEKASI                      101
BOGOR                       126
BUMI SERPONG DAMAI           73
JATIM 1                       7
JATIM 2                       6
JATIM 3                       5
JATIM 4                       5
SAMARINDA                     3
SULAWESI SELATAN & BARAT      6
SULAWESI UTARA & IBT          5
Name: count, dtype: int64

In [120]:
#Manual Adjustment - SME+
lending_smeplus['AREA'] = np.where(lending_smeplus['AREA'] == 'JATIM, BALI & NUSRA A',
                               'JATIM A',
                               lending_smeplus['AREA'])
lending_smeplus['AREA'] = np.where(lending_smeplus['AREA'] == 'JATIM, BALI & NUSRA B',
                               'JATIM B',
                               lending_smeplus['AREA'])

### 8.4 Add Manual Mapping

In [121]:
manual_mapping_rsme = manual_mapping[manual_mapping['LoB'] == 'RSME']
manual_mapping_smeplus = manual_mapping[manual_mapping['LoB'] == 'SME+']

In [122]:
manual_mapping_rsme[manual_mapping_rsme['GCIF_NO'].duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, NPK_REFF, NPK_MAINT, LoB]
Index: []

In [123]:
lending_rsme = lending_rsme.merge(manual_mapping_rsme[['GCIF_NO','NPK_REFF','NPK_MAINT']],
                                 on='GCIF_NO',how='left')
lending_rsme['NPK_MAINT'] = np.where(lending_rsme['NPK_MAINT_y'].isna(),
                                     lending_rsme['NPK_MAINT_x'],
                                    lending_rsme['NPK_MAINT_y'])
lending_rsme['NPK_REFF'] = np.where(lending_rsme['NPK_REFF_y'].isna(),
                                     lending_rsme['NPK_REFF_x'],
                                    lending_rsme['NPK_REFF_y'])
lending_rsme = lending_rsme[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION', 'NPK_REFF', 'SOURCE']]
lending_rsme['NPK_MAINT'] = lending_rsme['NPK_MAINT'].astype('int64')
lending_rsme['NPK_REFF'] = lending_rsme['NPK_REFF'].astype('int64')
lending_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    6127 non-null   object
 1   NPK_MAINT  6127 non-null   int64
 2   AREA       6127 non-null   object
 3   REGION     5696 non-null   object
 4   NPK_REFF   6127 non-null   int64
 5   SOURCE     5522 non-null   object
dtypes: int64(2), object(4)
memory usage: 287.3+ KB

In [124]:
lending_smeplus[lending_smeplus['NPK_MAINT'].isna()]

Empty DataFrame
Columns: [GCIF_NO, NPK_MAINT, AREA, REGION, NPK_REFF, SOURCE]
Index: []

In [125]:
lending_smeplus = lending_smeplus.merge(manual_mapping_smeplus[['GCIF_NO','NPK_REFF','NPK_MAINT']],
                                 on='GCIF_NO',how='left')
lending_smeplus['NPK_MAINT'] = np.where(lending_smeplus['NPK_MAINT_y'].isna(),
                                     lending_smeplus['NPK_MAINT_x'],
                                    lending_smeplus['NPK_MAINT_y'])
lending_smeplus['NPK_REFF'] = np.where(lending_smeplus['NPK_REFF_y'].isna(),
                                     lending_smeplus['NPK_REFF_x'],
                                    lending_smeplus['NPK_REFF_y'])
lending_smeplus = lending_smeplus[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION', 'NPK_REFF', 'SOURCE']]
lending_smeplus['NPK_MAINT'] = lending_smeplus['NPK_MAINT'].astype('int64')
lending_smeplus['NPK_REFF'] = lending_smeplus['NPK_REFF'].astype('int64')
#ERROR CHECKING: pastikan (1) semua gaada yang NaN (terutama AREA dan REGION), (2) data type NPK MAINT dan NPK REFF sudah int64
lending_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    591 non-null    object
 1   NPK_MAINT  591 non-null    int64
 2   AREA       383 non-null    object
 3   REGION     581 non-null    object
 4   NPK_REFF   591 non-null    int64
 5   SOURCE     591 non-null    object
dtypes: int64(2), object(4)
memory usage: 27.8+ KB

In [126]:
#ERROR CHECKING: pastikan (1) semua gaada yang NaN (terutama AREA dan REGION), (2) data type NPK MAINT dan NPK REFF sudah int64
#Jml rows ~5900
lending_rsme.info()
#lending_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    6127 non-null   object
 1   NPK_MAINT  6127 non-null   int64
 2   AREA       6127 non-null   object
 3   REGION     5696 non-null   object
 4   NPK_REFF   6127 non-null   int64
 5   SOURCE     5522 non-null   object
dtypes: int64(2), object(4)
memory usage: 287.3+ KB

## 11. BASELINE - RSME

In [127]:
len(lending_rsme)

6127

In [128]:
lending_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    6127 non-null   object
 1   NPK_MAINT  6127 non-null   int64
 2   AREA       6127 non-null   object
 3   REGION     5696 non-null   object
 4   NPK_REFF   6127 non-null   int64
 5   SOURCE     5522 non-null   object
dtypes: int64(2), object(4)
memory usage: 287.3+ KB

In [129]:
lending_rsme[lending_rsme['NPK_REFF']==43269].count()

GCIF_NO      73
NPK_MAINT    73
AREA         73
REGION       73
NPK_REFF     73
SOURCE       72
dtype: int64

In [130]:
lending_rsme_a = lending_rsme.merge(rsme_npk_list,
                                   left_on='NPK_MAINT',
                                   right_on='NPK',
                                   how='left')
lending_rsme_a.columns = ['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION',
       'NPK_REFF', 'SOURCE', 'NPK_by_NPKMAINT', 'NAME_by_NPKMAINT', 'JABATAN_by_NPKMAINT']
lending_rsme_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GCIF_NO              6127 non-null   object
 1   NPK_MAINT            6127 non-null   int64
 2   AREA                 6127 non-null   object
 3   REGION               5696 non-null   object
 4   NPK_REFF             6127 non-null   int64
 5   SOURCE               5522 non-null   object
 6   NPK_by_NPKMAINT      4916 non-null   float64
 7   NAME_by_NPKMAINT     4916 non-null   object
 8   JABATAN_by_NPKMAINT  4916 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 430.9+ KB

In [131]:
lending_rsme_b = lending_rsme_a.merge(rsme_npk_list,
                                   left_on='NPK_REFF',
                                   right_on='NPK',
                                   how='left')
lending_rsme_b.columns = ['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION',
       'NPK_REFF', 'SOURCE', 'NPK_by_NPKMAINT', 'NAME_by_NPKMAINT',
       'JABATAN_by_NPKMAINT', 'NPK_by_NPKREFF', 'NAME_by_NPKREFF', 'JABATAN_by_NPKREFF']
lending_rsme_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GCIF_NO              6127 non-null   object
 1   NPK_MAINT            6127 non-null   int64
 2   AREA                 6127 non-null   object
 3   REGION               5696 non-null   object
 4   NPK_REFF             6127 non-null   int64
 5   SOURCE               5522 non-null   object
 6   NPK_by_NPKMAINT      4916 non-null   float64
 7   NAME_by_NPKMAINT     4916 non-null   object
 8   JABATAN_by_NPKMAINT  4916 non-null   object
 9   NPK_by_NPKREFF       4321 non-null   float64
 10  NAME_by_NPKREFF      4321 non-null   object
 11  JABATAN_by_NPKREFF   4321 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 574.5+ KB

In [132]:
lending_rsme_b[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER       5
                      SME MANAGER             4066
                      NaN                      733
SME MANAGER           RELATIONSHIP OFFICER       4
                      SME MANAGER                5
                      NaN                      103
NaN                   RELATIONSHIP OFFICER       5
                      SME MANAGER              236
                      NaN                      970
Name: count, dtype: int64

### 11.1 RO Baseline

In [133]:
lending_rsme_ro = lending_rsme_b[(lending_rsme_b['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER')
                                       | (lending_rsme_b['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER')]
len(lending_rsme_ro)

4813

In [134]:
lending_rsme_ro[lending_rsme_ro['NPK_REFF']==43269]

,GCIF_NO,NPK_MAINT,AREA,REGION,NPK_REFF,SOURCE,NPK_by_NPKMAINT,NAME_by_NPKMAINT,JABATAN_by_NPKMAINT,NPK_by_NPKREFF,NAME_by_NPKREFF,JABATAN_by_NPKREFF
214,G006603542,40825,SUMMITMAS,JAKARTA 1,43269,CRS,"40,825.0",RICO SIMANUNGKALIT,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
250,G007653215,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
268,G008088569,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
316,G008961062,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
366,G009548165,40825,SUMMITMAS,JAKARTA 1,43269,CRS,"40,825.0",RICO SIMANUNGKALIT,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
...,...,...,...,...,...,...,...,...,...,...,...,...
5180,G907209050,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
5224,G908566128,40825,SUMMITMAS,JAKARTA 1,43269,CRS,"40,825.0",RICO SIMANUNGKALIT,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
5283,G909270027,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
5501,G910618982,43706,SUMMITMAS,JAKARTA 1,43269,CRS,"43,706.0",DOTI RARA RIANTI,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER
6113,G209787688,43071,SUMMITMAS,JAKARTA 1,43269,NaN,"43,071.0",RIZSANIA HENDARWIN,RELATIONSHIP OFFICER,"43,269.0",WAH HENDY,SME MANAGER

In [135]:
lending_rsme_ro['NPK'] = np.where(((lending_rsme_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_rsme_ro['JABATAN_by_NPKREFF'] != 'RELATIONSHIP OFFICER'))
                                    | ((lending_rsme_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_rsme_ro['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER') & (lending_rsme_ro['NPK_by_NPKREFF'] == 0)),
                                    lending_rsme_ro['NPK_by_NPKMAINT'],
                                    lending_rsme_ro['NPK_by_NPKREFF'])
# lending_rsme_ro['NPK'] = np.where(lending_rsme_ro['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER',
#                                            lending_rsme_ro['NPK_by_NPKREFF'],
#                                            lending_rsme_ro['NPK'])
lending_rsme_ro['NPK']=lending_rsme_ro['NPK'].astype('float')
lending_rsme_ro['NPK']=lending_rsme_ro['NPK'].astype('int64')

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3639494547.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_ro['NPK'] = np.where(((lending_rsme_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_rsme_ro['JABATAN_by_NPKREFF'] != 'RELATIONSHIP OFFICER'))
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3639494547.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_ro['NPK']=lending_rsme_ro['NPK'].astype('float')
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3639494547.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_ro['NPK']=lending_rsme_ro['NPK'].astype('int64')

In [136]:
#Add name and jabatan dari final NPK RO
baseline_ro_rsme = lending_rsme_ro.merge(rsme_npk_list,
                                   on='NPK',
                                   how='left')
baseline_ro_rsme = baseline_ro_rsme[['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']]
baseline_ro_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4813 entries, 0 to 4812
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  4813 non-null   object
 1   NPK      4813 non-null   int64
 2   NAMA     4813 non-null   object
 3   JABATAN  4813 non-null   object
 4   AREA     4813 non-null   object
 5   REGION   4788 non-null   object
dtypes: int64(1), object(5)
memory usage: 225.7+ KB

### 11.2 SMEM Baseline

In [137]:
baseline_smem_rsme_hierarchy = baseline_ro_rsme.merge(hierarchy_smer_clean[['NPK_RO','NPK_SMEM','NAME_SMEM']],
                                   left_on='NPK',right_on='NPK_RO',how='left')
len(baseline_smem_rsme_hierarchy) == len(baseline_ro_rsme)

True

In [138]:
hierarchy_smer_clean[hierarchy_smer_clean['NPK_SMEM']==43269]

,REGION_RSH,NPK_RSH,NAME_RSH,NPK_ASH,NAME_ASH,AREA_ASH,NPK_SMEM,NAME_SMEM,NPK_RO,NAME_RO,BRANCH_RO
80,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,43071,RIZSANIA HENDARWIN,KCI SUMMITMAS
81,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,40825,RICO SIMANUNGKALIT,KCI SUMMITMAS
82,JAKARTA 1,38313,DENNY HARTONO,26454,HENDRA PUTRA,SUMMITMAS,43269,WAH HENDY,44131,OLGA ANINDA RESTU,KCI SUMMITMAS

In [139]:
baseline_ro_rsme[baseline_ro_rsme['NAMA']=='OLGA ANINDA RESTU']

Empty DataFrame
Columns: [GCIF_NO, NPK, NAMA, JABATAN, AREA, REGION]
Index: []

In [140]:
baseline_smem_rsme_hierarchy[baseline_smem_rsme_hierarchy['NPK_SMEM']==43269].count()

GCIF_NO      37
NPK          37
NAMA         37
JABATAN      37
AREA         37
REGION       37
NPK_RO       37
NPK_SMEM     37
NAME_SMEM    37
dtype: int64

In [141]:
baseline_smem_rsme_hierarchy[baseline_smem_rsme_hierarchy['NPK']==43269].count()

GCIF_NO      0
NPK          0
NAMA         0
JABATAN      0
AREA         0
REGION       0
NPK_RO       0
NPK_SMEM     0
NAME_SMEM    0
dtype: int64

In [142]:
#Untuk RO yang tidak memiliki ASH dan RSH
baseline_smem_rsme_hierarchy = baseline_smem_rsme_hierarchy[baseline_smem_rsme_hierarchy['NPK_SMEM'] != 0]
baseline_smem_rsme_hierarchy['JABATAN'] = 'SME MANAGER'
baseline_smem_rsme_hierarchy = baseline_smem_rsme_hierarchy[['GCIF_NO', 'NPK_SMEM', 'NAME_SMEM', 'JABATAN','AREA', 'REGION']]
baseline_smem_rsme_hierarchy.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_smem_rsme_hierarchy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4358 entries, 0 to 4812
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  4358 non-null   object
 1   NPK      4358 non-null   int64
 2   NAMA     4358 non-null   object
 3   JABATAN  4358 non-null   object
 4   AREA     4358 non-null   object
 5   REGION   4337 non-null   object
dtypes: int64(1), object(5)
memory usage: 238.3+ KB

In [143]:
lending_rsme_b[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER       5
                      SME MANAGER             4066
                      NaN                      733
SME MANAGER           RELATIONSHIP OFFICER       4
                      SME MANAGER                5
                      NaN                      103
NaN                   RELATIONSHIP OFFICER       5
                      SME MANAGER              236
                      NaN                      970
Name: count, dtype: int64

In [144]:
lending_rsme_smem_mapped = lending_rsme_b[((lending_rsme_b['JABATAN_by_NPKMAINT'] == 'SME MANAGER') & (lending_rsme_b['JABATAN_by_NPKREFF'] != 'RELATIONSHIP OFFICER'))
                                         | ((lending_rsme_b['JABATAN_by_NPKREFF'] == 'SME MANAGER') & (lending_rsme_b['JABATAN_by_NPKMAINT'] != 'RELATIONSHIP OFFICER'))]
# lending_rsme_smem_mapped[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()
len(lending_rsme_smem_mapped)

344

In [145]:
lending_rsme_smem_mapped['NPK'] = np.where(lending_rsme_smem_mapped['JABATAN_by_NPKMAINT'] == 'SME MANAGER',
                                           lending_rsme_smem_mapped['NPK_by_NPKMAINT'],
                                           '0')
lending_rsme_smem_mapped['NPK'] = np.where(lending_rsme_smem_mapped['JABATAN_by_NPKREFF'] == 'SME MANAGER',
                                           lending_rsme_smem_mapped['NPK_by_NPKREFF'],
                                           lending_rsme_smem_mapped['NPK'])
lending_rsme_smem_mapped['NPK'] = lending_rsme_smem_mapped['NPK'].astype('float')
lending_rsme_smem_mapped['NPK'] = lending_rsme_smem_mapped['NPK'].astype('int64')
lending_rsme_smem_mapped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 344 entries, 16 to 6093
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GCIF_NO              344 non-null    object
 1   NPK_MAINT            344 non-null    int64
 2   AREA                 344 non-null    object
 3   REGION               343 non-null    object
 4   NPK_REFF             344 non-null    int64
 5   SOURCE               336 non-null    object
 6   NPK_by_NPKMAINT      108 non-null    float64
 7   NAME_by_NPKMAINT     108 non-null    object
 8   JABATAN_by_NPKMAINT  108 non-null    object
 9   NPK_by_NPKREFF       241 non-null    float64
 10  NAME_by_NPKREFF      241 non-null    object
 11  JABATAN_by_NPKREFF   241 non-null    object
 12  NPK                  344 non-null    int64
dtypes: float64(2), int64(3), object(8)
memory usage: 37.6+ KB

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3681440893.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_smem_mapped['NPK'] = np.where(lending_rsme_smem_mapped['JABATAN_by_NPKMAINT'] == 'SME MANAGER',
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3681440893.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_smem_mapped['NPK'] = np.where(lending_rsme_smem_mapped['JABATAN_by_NPKREFF'] == 'SME MANAGER',
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3681440893.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_smem_mapped['NPK'] = lending_rsme_smem_mapped['NPK'].astype('float')
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3681440893.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_rsme_smem_mapped['NPK'] = lending_rsme_smem_mapped['NPK'].astype('int64')

In [146]:
#Add name and jabatan dari final NPK SMEM
baseline_smem_rsme_npk = lending_rsme_smem_mapped.merge(rsme_npk_list,
                                   on='NPK',
                                   how='left')
baseline_smem_rsme_npk = baseline_smem_rsme_npk[['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']]
baseline_smem_rsme_npk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  344 non-null    object
 1   NPK      344 non-null    int64
 2   NAMA     344 non-null    object
 3   JABATAN  344 non-null    object
 4   AREA     344 non-null    object
 5   REGION   343 non-null    object
dtypes: int64(1), object(5)
memory usage: 16.3+ KB

In [147]:
baseline_smem_rsme = pd.concat([baseline_smem_rsme_npk,baseline_smem_rsme_hierarchy],axis=0)
baseline_smem_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4702 entries, 0 to 4812
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  4702 non-null   object
 1   NPK      4702 non-null   int64
 2   NAMA     4702 non-null   object
 3   JABATAN  4702 non-null   object
 4   AREA     4702 non-null   object
 5   REGION   4680 non-null   object
dtypes: int64(1), object(5)
memory usage: 257.1+ KB

In [148]:
# lending_rsme_unmapped = lending_rsme_b[(lending_rsme_b['JABATAN_by_NPKMAINT'].isna())
#                                        & (lending_rsme_b['JABATAN_by_NPKREFF'].isna())]
# lending_rsme_unmapped[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

### 11.3 Mapping Baseline ASH

In [149]:
lending_rsme_b[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER       5
                      SME MANAGER             4066
                      NaN                      733
SME MANAGER           RELATIONSHIP OFFICER       4
                      SME MANAGER                5
                      NaN                      103
NaN                   RELATIONSHIP OFFICER       5
                      SME MANAGER              236
                      NaN                      970
Name: count, dtype: int64

In [150]:
print(len(lending_rsme))
#Add from lending_rsme_b:
print(len(lending_rsme_b[(lending_rsme_b['JABATAN_by_NPKMAINT'].isna()) & (lending_rsme_b['JABATAN_by_NPKREFF'].isna())]))
#Mapped in SMEM and RO
print(len(baseline_smem_rsme) #Mapped in SMEM (= has SMEM & RO + has SMEM only)
      +len(lending_rsme_b[(lending_rsme_b['JABATAN_by_NPKMAINT'].isna()) & (lending_rsme_b['JABATAN_by_NPKREFF'].isna())]) #Add from lending_rsme_b
      + len(baseline_ro_rsme[~(baseline_ro_rsme['GCIF_NO'].isin(baseline_smem_rsme['GCIF_NO']))])) #Mapped in RO (= has RO only)

6127
970
6127

In [151]:
baseline_ash_rsme_hierarchy_1 = baseline_smem_rsme
baseline_ash_rsme_hierarchy_2 = baseline_ro_rsme[~(baseline_ro_rsme['GCIF_NO'].isin(baseline_smem_rsme['GCIF_NO']))]
baseline_ash_rsme_area = lending_rsme_b[(lending_rsme_b['JABATAN_by_NPKMAINT'].isna()) & (lending_rsme_b['JABATAN_by_NPKREFF'].isna())]
print(len(baseline_ash_rsme_hierarchy_1)+len(baseline_ash_rsme_hierarchy_2)+len(baseline_ash_rsme_area)==len(lending_rsme))

True

In [152]:
baseline_smem_rsme[baseline_smem_rsme['GCIF_NO']=='G907225353']

Empty DataFrame
Columns: [GCIF_NO, NPK, NAMA, JABATAN, AREA, REGION]
Index: []

In [153]:
baseline_ash_rsme_hierarchy_1 = baseline_ash_rsme_hierarchy_1.merge(hierarchy_smer[['NPK_SMEM','NPK_ASH','NAME_ASH']].drop_duplicates(),
                                                                    how='left', left_on='NPK',right_on='NPK_SMEM')
baseline_ash_rsme_hierarchy_1 = baseline_ash_rsme_hierarchy_1[baseline_ash_rsme_hierarchy_1['NPK_ASH'] != 0]
baseline_ash_rsme_hierarchy_1['JABATAN'] = 'AREA SME HEAD'
baseline_ash_rsme_hierarchy_1 = baseline_ash_rsme_hierarchy_1[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN','AREA', 'REGION']]
baseline_ash_rsme_hierarchy_1.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_ash_rsme_hierarchy_1.info()
baseline_ash_rsme_hierarchy_1[baseline_ash_rsme_hierarchy_1['GCIF_NO']=='G907225353']

<class 'pandas.core.frame.DataFrame'>
Index: 4254 entries, 0 to 4701
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  4254 non-null   object
 1   NPK      4254 non-null   int64
 2   NAMA     4254 non-null   object
 3   JABATAN  4254 non-null   object
 4   AREA     4254 non-null   object
 5   REGION   4232 non-null   object
dtypes: int64(1), object(5)
memory usage: 232.6+ KB

Empty DataFrame
Columns: [GCIF_NO, NPK, NAMA, JABATAN, AREA, REGION]
Index: []

In [154]:
baseline_ash_rsme_hierarchy_2 = baseline_ash_rsme_hierarchy_2.merge(hierarchy_smer[['NPK_RO','NPK_ASH','NAME_ASH']].drop_duplicates(),
                                                                    how='left', left_on='NPK',right_on='NPK_RO')
baseline_ash_rsme_hierarchy_2 = baseline_ash_rsme_hierarchy_2[baseline_ash_rsme_hierarchy_2['NPK_ASH'] != 0]
baseline_ash_rsme_hierarchy_2['JABATAN'] = 'AREA SME HEAD'
baseline_ash_rsme_hierarchy_2 = baseline_ash_rsme_hierarchy_2[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN','AREA', 'REGION']]
baseline_ash_rsme_hierarchy_2.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_ash_rsme_hierarchy_2.info()
baseline_ash_rsme_hierarchy_2[baseline_ash_rsme_hierarchy_2['GCIF_NO']=='G000734004']

<class 'pandas.core.frame.DataFrame'>
Index: 453 entries, 0 to 454
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  453 non-null    object
 1   NPK      453 non-null    int64
 2   NAMA     453 non-null    object
 3   JABATAN  453 non-null    object
 4   AREA     453 non-null    object
 5   REGION   449 non-null    object
dtypes: int64(1), object(5)
memory usage: 24.8+ KB

Empty DataFrame
Columns: [GCIF_NO, NPK, NAMA, JABATAN, AREA, REGION]
Index: []

In [155]:
#Scenario 3: Bisa jadi dia punya NPK, tapi NPK dan AREA tidak ada di hierarki -> biarin unmapped dulu aja
#Check
baseline_ash_rsme_area[~baseline_ash_rsme_area['AREA'].isin(hierarchy_smer['AREA_ASH'])]

,GCIF_NO,NPK_MAINT,AREA,REGION,NPK_REFF,SOURCE,NPK_by_NPKMAINT,NAME_by_NPKMAINT,JABATAN_by_NPKMAINT,NPK_by_NPKREFF,NAME_by_NPKREFF,JABATAN_by_NPKREFF
15,G500614979,0,BALI NUSRA 1,NaN,0,CRS,NaN,NaN,NaN,NaN,NaN,NaN
21,EX0000000000,0,BALI NUSRA 1,NaN,0,CRS,NaN,NaN,NaN,NaN,NaN,NaN
23,G408429496,0,BEKASI,JAKARTA 3,0,CRS,NaN,NaN,NaN,NaN,NaN,NaN
26,G208150136,0,BOGOR,JAKARTA 3,0,CRS,NaN,NaN,NaN,NaN,NaN,NaN
1151,G200968733,17730,BALI NUSRA 1,"JATIM, BALI & NUSRA",38198,CRS,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6118,G808947154,0,BALI NUSRA 1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6120,G109280677,0,BALI NUSRA 1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6122,G806392999,0,JATIM 1,"JATIM, BALI & NUSRA",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125,G900683368,0,BALIKPAPAN,KALIMANTAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6126,G502403330,0,BALI NUSRA 1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
baseline_ash_rsme_area = baseline_ash_rsme_area.merge(hierarchy_smer[['AREA_ASH','NPK_ASH','NAME_ASH']].drop_duplicates(),
                                                      left_on='AREA',right_on='AREA_ASH',how='left')
baseline_ash_rsme_area = baseline_ash_rsme_area[~baseline_ash_rsme_area['NPK_ASH'].isna()]
baseline_ash_rsme_area = baseline_ash_rsme_area[baseline_ash_rsme_area['NPK_ASH']!=0]
baseline_ash_rsme_area['JABATAN'] = 'AREA SME HEAD'
baseline_ash_rsme_area = baseline_ash_rsme_area[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN','AREA', 'REGION']]
baseline_ash_rsme_area.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_ash_rsme_area.info()
# baseline_ash_rsme_area[baseline_ash_rsme_area['GCIF_NO']=='G000734004']

<class 'pandas.core.frame.DataFrame'>
Index: 519 entries, 0 to 1190
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  519 non-null    object
 1   NPK      519 non-null    float64
 2   NAMA     519 non-null    object
 3   JABATAN  519 non-null    object
 4   AREA     519 non-null    object
 5   REGION   519 non-null    object
dtypes: float64(1), object(5)
memory usage: 28.4+ KB

In [157]:
baseline_ash_rsme = pd.concat([baseline_ash_rsme_area,baseline_ash_rsme_hierarchy_1, baseline_ash_rsme_hierarchy_2],axis=0)
baseline_ash_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5226 entries, 0 to 454
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  5226 non-null   object
 1   NPK      5226 non-null   float64
 2   NAMA     5226 non-null   object
 3   JABATAN  5226 non-null   object
 4   AREA     5226 non-null   object
 5   REGION   5200 non-null   object
dtypes: float64(1), object(5)
memory usage: 285.8+ KB

In [158]:
# baseline_ash_rsme = lending_rsme.merge(hierarchy_smer_clean[['AREA_ASH','NPK_ASH','NAME_ASH']].drop_duplicates(keep='first'),
#                          left_on='AREA',right_on='AREA_ASH',
#                          how='left')
# baseline_ash_rsme.info()
# baseline_ash_rsme = baseline_ash_rsme[baseline_ash_rsme['NPK_ASH'] != 0]
# baseline_ash_rsme['JABATAN'] = 'AREA SME HEAD'
# baseline_ash_rsme = baseline_ash_rsme[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN', 'AREA', 'REGION']]
# baseline_ash_rsme.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
# baseline_ash_rsme.info()

In [159]:
baseline_ash_rsme_area[baseline_ash_rsme_area['GCIF_NO']=='G208615005']

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION
1189,G208615005,"18,345.0",ANTON HARTONO,AREA SME HEAD,MEDAN BARAT,SUMATERA UTARA

### 11.4 Mapping Baseline RSH

In [160]:
lending_rsme[~lending_rsme['REGION'].isin(hierarchy_smer['REGION_RSH'])]

           GCIF_NO  NPK_MAINT          AREA REGION  NPK_REFF SOURCE
15      G500614979          0  BALI NUSRA 1    NaN         0    CRS
21    EX0000000000          0  BALI NUSRA 1    NaN         0    CRS
228     G007027279      44080  BALI NUSRA 1    NaN     43302    CRS
385     G009654138      38083  BALI NUSRA 1    NaN     22581    CRS
396     G009749847      38950  BALI NUSRA 1    NaN     37442    CRS
...            ...        ...           ...    ...       ...    ...
6115    G500577572          0  BALI NUSRA 1    NaN         0    NaN
6117    G007578701          0  BALI NUSRA 1    NaN         0    NaN
6118    G808947154          0  BALI NUSRA 1    NaN         0    NaN
6120    G109280677          0  BALI NUSRA 1    NaN         0    NaN
6126    G502403330          0  BALI NUSRA 1    NaN         0    NaN

[431 rows x 6 columns]

In [161]:
baseline_rsh_rsme = lending_rsme.merge(hierarchy_smer_clean[['REGION_RSH','NPK_RSH','NAME_RSH']].drop_duplicates(keep='first'),
                         left_on='REGION',right_on='REGION_RSH',
                         how='left')
baseline_rsh_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6991 entries, 0 to 6990
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GCIF_NO     6991 non-null   object
 1   NPK_MAINT   6991 non-null   int64
 2   AREA        6991 non-null   object
 3   REGION      6560 non-null   object
 4   NPK_REFF    6991 non-null   int64
 5   SOURCE      6360 non-null   object
 6   REGION_RSH  6560 non-null   object
 7   NPK_RSH     6560 non-null   float64
 8   NAME_RSH    6560 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 491.7+ KB

In [162]:
baseline_rsh_rsme = baseline_rsh_rsme[baseline_rsh_rsme['NPK_RSH'] != 0]

In [163]:
baseline_rsh_rsme['JABATAN'] = 'REGIONAL SME HEAD'
baseline_rsh_rsme = baseline_rsh_rsme[['GCIF_NO', 'NPK_RSH', 'NAME_RSH', 'JABATAN', 'AREA', 'REGION']]
baseline_rsh_rsme.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_rsh_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6518 entries, 0 to 6990
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  6518 non-null   object
 1   NPK      6087 non-null   float64
 2   NAMA     6087 non-null   object
 3   JABATAN  6518 non-null   object
 4   AREA     6518 non-null   object
 5   REGION   6087 non-null   object
dtypes: float64(1), object(5)
memory usage: 356.5+ KB

### 11.5 Append RO, SMEM, ASH, RSH mapping and add email

In [164]:
baseline_rsme = pd.concat([baseline_ro_rsme,baseline_smem_rsme,baseline_ash_rsme,baseline_rsh_rsme],axis=0)
baseline_rsme['NPK'] = baseline_rsme['NPK'].fillna(0) #PENDING: masih harus fillna?
baseline_rsme['NPK'] = baseline_rsme['NPK'].astype('int64')
len(baseline_rsme)

21259

In [165]:
baseline_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21259 entries, 0 to 6990
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  21259 non-null  object
 1   NPK      21259 non-null  int64
 2   NAMA     20828 non-null  object
 3   JABATAN  21259 non-null  object
 4   AREA     21259 non-null  object
 5   REGION   20755 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.1+ MB

In [166]:
baseline_rsme[baseline_rsme['NPK']==43269].count()

GCIF_NO    37
NPK        37
NAMA       37
JABATAN    37
AREA       37
REGION     37
dtype: int64

In [167]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1221 entries, 0 to 1220
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EMAIL_KARYAWAN    1220 non-null   object
 1   NPK               1221 non-null   int64
 2   NAMA              1221 non-null   object
 3   JABATAN           1219 non-null   object
 4   DEPARTEMEN        1196 non-null   object
 5   ROLE IN UPLINE    1172 non-null   object
 6   Dashboard Access  1134 non-null   object
 7   REGION            99 non-null     object
dtypes: int64(1), object(7)
memory usage: 76.4+ KB

In [168]:
users['NPK'] = users['NPK'].astype('int64')
baseline_rsme_with_email = baseline_rsme.merge(users[['NPK','EMAIL_KARYAWAN']],on='NPK',how='left')
baseline_rsme_with_email.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21259 entries, 0 to 21258
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         21259 non-null  object
 1   NPK             21259 non-null  int64
 2   NAMA            20828 non-null  object
 3   JABATAN         21259 non-null  object
 4   AREA            21259 non-null  object
 5   REGION          20755 non-null  object
 6   EMAIL_KARYAWAN  20138 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.1+ MB

In [169]:
#CHECKPOINT: EMAIL NA?
baseline_rsme_with_email[baseline_rsme_with_email['EMAIL_KARYAWAN'].isna()].drop_duplicates('NPK')

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION,EMAIL_KARYAWAN
49,G001117910,44193,"LAURNAGISCA CITRANING SETYA, S.E",RELATIONSHIP OFFICER,JEMUR ANDAYANI,"JATIM, BALI & NUSRA",NaN
69,G001900877,43713,MARSELY PUTRI RISTANTI,RELATIONSHIP OFFICER,JAWA BARAT 4,JAWA BARAT,NaN
119,G005149703,44185,RESTIAWATI CAHYADI,RELATIONSHIP OFFICER,YOGYAKARTA,JAWA TENGAH,NaN
125,G005580600,44306,WILLI SAPUTRA,RELATIONSHIP OFFICER,ROXY,JAKARTA 1,NaN
141,G006061535,44089,APRIADY RANTETAMPANG,RELATIONSHIP OFFICER,INDONESIA BAG. TIMUR,SULAWESI & IBT,NaN
146,G006163679,44272,JOHAN HENDYANTO SALIM,RELATIONSHIP OFFICER,SURABAYA,"JATIM, BALI & NUSRA",NaN
215,G008457038,44194,NISSYA CHRISTY GINTING,RELATIONSHIP OFFICER,MT HARYONO,JAKARTA 1,NaN
230,G008786881,44230,ELISA HARIANTO,RELATIONSHIP OFFICER,SURABAYA,"JATIM, BALI & NUSRA",NaN
248,G009028739,43791,KELLY RIONA THALIA,RELATIONSHIP OFFICER,PONTIANAK,KALIMANTAN,NaN
333,G009879578,43734,GEORGE WILLIAM DOUGLAS HUTABARAT,RELATIONSHIP OFFICER,CEMPAKA MAS,JAKARTA 1,NaN
363,G010094621,43709,RICKY JOHARI,RELATIONSHIP OFFICER,THAMRIN,JAKARTA 1,NaN
718,G109110106,44154,DANY DARMAWAN,RELATIONSHIP OFFICER,THAMRIN,JAKARTA 1,NaN
832,G110030756,44214,NANCY ADELIA HUSIN,RELATIONSHIP OFFICER,PALEMBANG,SUMATERA SELATAN,NaN
1802,G310208962,44126,CARINA INTAN PERMATASARI,RELATIONSHIP OFFICER,YOGYAKARTA,JAWA TENGAH,NaN
1881,G310989736,44319,"PANDE MADE ADI PRABAWA,S.E",RELATIONSHIP OFFICER,BALI NUSRA 1,"JATIM, BALI & NUSRA",NaN
3812,G710604844,44231,FRIENLY HANDOKO SEJAHTERA SIPAYUNG,RELATIONSHIP OFFICER,EKAJIWA,JAKARTA 2,NaN
4270,G810486894,44209,CHINTIA FEBRIANTI,RELATIONSHIP OFFICER,PALEMBANG,SUMATERA SELATAN,NaN
4690,G910248251,36161,YULIUS BERNADUS MOTOH,RELATIONSHIP OFFICER,SEMARANG,JAWA TENGAH,NaN
5211,G001395672,44229,ASTRIDA ARJUNANI,SME MANAGER,BEKASI,JAKARTA 3,NaN
5286,G005894316,44305,IVAN CHRISTIAN,SME MANAGER,JAWA BARAT 3,JAWA BARAT,NaN
9525,G708553102,44150,ERVANI DEVI NATALIA,AREA SME HEAD,YOGYAKARTA,JAWA TENGAH,NaN
9609,G205084874,35985,VENCE LAPASO,AREA SME HEAD,INDONESIA BAG. TIMUR,SULAWESI & IBT,NaN
14760,G500614979,0,NaN,REGIONAL SME HEAD,BALI NUSRA 1,NaN,NaN

In [170]:
# baseline_rsme_with_email[baseline_rsme_with_email['EMAIL_KARYAWAN'].isna()].drop_duplicates('NPK').to_excel('add_email.xlsx')

In [171]:
hierarchy_smer[hierarchy_smer['AREA_ASH']=='JAWA BARAT 3A']

Empty DataFrame
Columns: [REGION_RSH, NPK_RSH, NAME_RSH, NPK_ASH, NAME_ASH, AREA_ASH, NPK_SMEM, NAME_SMEM, NPK_RO, NAME_RO, BRANCH_RO]
Index: []

In [172]:
#Manual Mapping Email Karyawan yang baru masuk (setelah update Hierarchy)
baseline_rsme_with_email['EMAIL_KARYAWAN'] = np.where(baseline_rsme_with_email['NPK']==38503,
                                                     's.saputra@maybank.co.id',
                                                     baseline_rsme_with_email['EMAIL_KARYAWAN'])

### 11.6 Mapping Baseline RD

In [173]:
baseline_rd_rsme = lending_rsme.merge(users[users['JABATAN']=='REGIONAL DIRECTOR'][['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
                  on='REGION',how='left')
baseline_rd_rsme = baseline_rd_rsme[['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION','EMAIL_KARYAWAN']]
baseline_rd_rsme.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION','EMAIL_KARYAWAN']
baseline_rd_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6127 entries, 0 to 6126
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         6127 non-null   object
 1   NPK             5696 non-null   float64
 2   NAMA            5696 non-null   object
 3   JABATAN         5696 non-null   object
 4   AREA            6127 non-null   object
 5   REGION          5696 non-null   object
 6   EMAIL_KARYAWAN  5696 non-null   object
dtypes: float64(1), object(6)
memory usage: 335.2+ KB

In [174]:
baseline_rd_rsme[baseline_rd_rsme['EMAIL_KARYAWAN'].isna()]

           GCIF_NO  NPK NAMA JABATAN          AREA REGION EMAIL_KARYAWAN
15      G500614979  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
21    EX0000000000  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
228     G007027279  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
385     G009654138  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
396     G009749847  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
...            ...  ...  ...     ...           ...    ...            ...
6115    G500577572  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
6117    G007578701  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
6118    G808947154  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
6120    G109280677  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN
6126    G502403330  NaN  NaN     NaN  BALI NUSRA 1    NaN            NaN

[431 rows x 7 columns]

### 12.7 Mapping Baseline Admin

In [175]:
email_map_admin = pd.read_excel(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Admin.xlsx", sheet_name = 'ADMIN')
tb = pd.read_excel(r"D:\Pricing & Data Analytics\Pricing Non Retail\PDT\Baseline Upline\Admin.xlsx", sheet_name = 'TB')

In [176]:
baseline_admin_rsme = lending_rsme[['GCIF_NO','REGION']].merge(email_map_admin,on='REGION',how='left')
baseline_admin_rsme.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28911 entries, 0 to 28910
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         28911 non-null  object
 1   REGION          28480 non-null  object
 2   NPK             28480 non-null  float64
 3   NAMA            28480 non-null  object
 4   JABATAN         28480 non-null  object
 5   EMAIL_KARYAWAN  28480 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.3+ MB

In [177]:
baseline_admin_rsme[['NAMA']].value_counts(dropna=False).sort_index()

NAMA
AHMAD HUMAEDI                    5696
DIMAS FEBRIATMOKO                5696
IZZA RANNISA                     5696
JESVIKA SARI MELYNA SIHOMBING    5696
SITI AISYAH                      5696
NaN                               431
Name: count, dtype: int64

In [178]:
#CHECKPOINT: ada EMAIL yang NA ga? Kalo ya, berarti baru masuk Hierarchy
baseline_admin_rsme[baseline_admin_rsme['EMAIL_KARYAWAN'].isna()].drop_duplicates('NPK')

       GCIF_NO REGION  NPK NAMA JABATAN EMAIL_KARYAWAN
75  G500614979    NaN  NaN  NaN     NaN            NaN

### 12.8 Mapping Baseline RRB

In [179]:
baseline_rrb_rsme = lending_rsme[['GCIF_NO','REGION']].merge(users[users['JABATAN']=='REGIONAL RETAIL BANKING HEAD'][['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
                                 on='REGION',how='left')
baseline_rrb_rsme = baseline_rrb_rsme[~baseline_rrb_rsme['NPK'].isna()]
baseline_rrb_rsme.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4747 entries, 0 to 6125
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         4747 non-null   object
 1   REGION          4747 non-null   object
 2   NPK             4747 non-null   float64
 3   NAMA            4747 non-null   object
 4   JABATAN         4747 non-null   object
 5   EMAIL_KARYAWAN  4747 non-null   object
dtypes: float64(1), object(5)
memory usage: 259.6+ KB

### 12.9 Combine All Baseline

In [180]:
lending_rsme[lending_rsme['GCIF_NO']=='G306226713']

         GCIF_NO  NPK_MAINT          AREA     REGION  NPK_REFF SOURCE
1816  G306226713      41370  PURI KENCANA  JAKARTA 2     38859    CRS

In [181]:
baseline_rsme_lending = pd.concat([baseline_rsme_with_email, baseline_rd_rsme,baseline_admin_rsme,baseline_rrb_rsme],axis=0)

In [182]:
baseline_rsme_lending.info()
#NOTE: NA AREA = Jabatan ADMIN

<class 'pandas.core.frame.DataFrame'>
Index: 61044 entries, 0 to 6125
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         61044 non-null  object
 1   NPK             60182 non-null  float64
 2   NAMA            59751 non-null  object
 3   JABATAN         60182 non-null  object
 4   AREA            27386 non-null  object
 5   REGION          59678 non-null  object
 6   EMAIL_KARYAWAN  59061 non-null  object
dtypes: float64(1), object(6)
memory usage: 3.7+ MB

In [183]:
#CHECKPOINT: ada EMAIL yang NA ga? Kalo ya, berarti baru masuk Hierarchy
baseline_rsme_lending[baseline_rsme_lending['EMAIL_KARYAWAN'].isna()].drop_duplicates('NPK')

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION,EMAIL_KARYAWAN
49,G001117910,"44,193.0","LAURNAGISCA CITRANING SETYA, S.E",RELATIONSHIP OFFICER,JEMUR ANDAYANI,"JATIM, BALI & NUSRA",NaN
69,G001900877,"43,713.0",MARSELY PUTRI RISTANTI,RELATIONSHIP OFFICER,JAWA BARAT 4,JAWA BARAT,NaN
119,G005149703,"44,185.0",RESTIAWATI CAHYADI,RELATIONSHIP OFFICER,YOGYAKARTA,JAWA TENGAH,NaN
125,G005580600,"44,306.0",WILLI SAPUTRA,RELATIONSHIP OFFICER,ROXY,JAKARTA 1,NaN
141,G006061535,"44,089.0",APRIADY RANTETAMPANG,RELATIONSHIP OFFICER,INDONESIA BAG. TIMUR,SULAWESI & IBT,NaN
146,G006163679,"44,272.0",JOHAN HENDYANTO SALIM,RELATIONSHIP OFFICER,SURABAYA,"JATIM, BALI & NUSRA",NaN
215,G008457038,"44,194.0",NISSYA CHRISTY GINTING,RELATIONSHIP OFFICER,MT HARYONO,JAKARTA 1,NaN
230,G008786881,"44,230.0",ELISA HARIANTO,RELATIONSHIP OFFICER,SURABAYA,"JATIM, BALI & NUSRA",NaN
248,G009028739,"43,791.0",KELLY RIONA THALIA,RELATIONSHIP OFFICER,PONTIANAK,KALIMANTAN,NaN
333,G009879578,"43,734.0",GEORGE WILLIAM DOUGLAS HUTABARAT,RELATIONSHIP OFFICER,CEMPAKA MAS,JAKARTA 1,NaN
363,G010094621,"43,709.0",RICKY JOHARI,RELATIONSHIP OFFICER,THAMRIN,JAKARTA 1,NaN
718,G109110106,"44,154.0",DANY DARMAWAN,RELATIONSHIP OFFICER,THAMRIN,JAKARTA 1,NaN
832,G110030756,"44,214.0",NANCY ADELIA HUSIN,RELATIONSHIP OFFICER,PALEMBANG,SUMATERA SELATAN,NaN
1802,G310208962,"44,126.0",CARINA INTAN PERMATASARI,RELATIONSHIP OFFICER,YOGYAKARTA,JAWA TENGAH,NaN
1881,G310989736,"44,319.0","PANDE MADE ADI PRABAWA,S.E",RELATIONSHIP OFFICER,BALI NUSRA 1,"JATIM, BALI & NUSRA",NaN
3812,G710604844,"44,231.0",FRIENLY HANDOKO SEJAHTERA SIPAYUNG,RELATIONSHIP OFFICER,EKAJIWA,JAKARTA 2,NaN
4270,G810486894,"44,209.0",CHINTIA FEBRIANTI,RELATIONSHIP OFFICER,PALEMBANG,SUMATERA SELATAN,NaN
4690,G910248251,"36,161.0",YULIUS BERNADUS MOTOH,RELATIONSHIP OFFICER,SEMARANG,JAWA TENGAH,NaN
5211,G001395672,"44,229.0",ASTRIDA ARJUNANI,SME MANAGER,BEKASI,JAKARTA 3,NaN
5286,G005894316,"44,305.0",IVAN CHRISTIAN,SME MANAGER,JAWA BARAT 3,JAWA BARAT,NaN
9525,G708553102,"44,150.0",ERVANI DEVI NATALIA,AREA SME HEAD,YOGYAKARTA,JAWA TENGAH,NaN
9609,G205084874,"35,985.0",VENCE LAPASO,AREA SME HEAD,INDONESIA BAG. TIMUR,SULAWESI & IBT,NaN
14760,G500614979,0.0,NaN,REGIONAL SME HEAD,BALI NUSRA 1,NaN,NaN
15,G500614979,NaN,NaN,NaN,BALI NUSRA 1,NaN,NaN

In [184]:
ncl_rsme[ncl_rsme['GCIF_NO']=='G308173806']

        GCIF_NO  NPK_MAINT  NPK_REFF AREA REGION
286  G308173806          0         0  NaN    NaN

## 13. UPLINE - RSME

In [185]:
lending_rsme_1 = lending_rsme[lending_rsme['NPK_MAINT'] != 0]
lending_rsme_2 = lending_rsme[lending_rsme['NPK_MAINT'] == 0]
print(lending_rsme_1.shape)
print(lending_rsme_2.shape)

len(lending_rsme_2) + len(lending_rsme_1) == len(lending_rsme)

(5586, 6)
(541, 6)

True

In [186]:
upline_rsme_1 = lending_rsme_1.merge(hierarchy_smer_clean[['NPK_RO','NAME_RO','BRANCH_RO',
                                                     'NPK_SMEM','NAME_SMEM',
                                                     'NPK_ASH','NAME_ASH','AREA_ASH',
                                                     'NPK_RSH','NAME_RSH','REGION_RSH']].drop_duplicates(),
                         left_on='NPK_MAINT',right_on='NPK_RO',
                         how='left')

upline_rsme_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5586 entries, 0 to 5585
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GCIF_NO     5586 non-null   object
 1   NPK_MAINT   5586 non-null   int64
 2   AREA        5586 non-null   object
 3   REGION      5559 non-null   object
 4   NPK_REFF    5586 non-null   int64
 5   SOURCE      5495 non-null   object
 6   NPK_RO      4804 non-null   float64
 7   NAME_RO     4804 non-null   object
 8   BRANCH_RO   4804 non-null   object
 9   NPK_SMEM    4804 non-null   float64
 10  NAME_SMEM   4804 non-null   object
 11  NPK_ASH     4804 non-null   float64
 12  NAME_ASH    4804 non-null   object
 13  AREA_ASH    4804 non-null   object
 14  NPK_RSH     4804 non-null   float64
 15  NAME_RSH    4804 non-null   object
 16  REGION_RSH  4804 non-null   object
dtypes: float64(4), int64(2), object(11)
memory usage: 742.0+ KB

In [187]:
upline_rsme_3 = upline_rsme_1[upline_rsme_1['NPK_RO'].isna()]

upline_rsme_3 = upline_rsme_3[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION','SOURCE']]
upline_rsme_3 = upline_rsme_3.merge(hierarchy_smer_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates(),
                               left_on='AREA',right_on='AREA_ASH', how='left')

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma di 
upline_rsme_3['NPK_ASH'] = upline_rsme_3['NPK_ASH'].fillna(0) #PENDING: fillna?
upline_rsme_3['NPK_ASH'] = upline_rsme_3['NPK_ASH'].astype('int64')
upline_rsme_3['NPK_RSH'] = upline_rsme_3['NPK_RSH'].fillna(0) #PENDING: fillna?
upline_rsme_3['NPK_RSH'] = upline_rsme_3['NPK_RSH'].astype('int64')

upline_rsme_3['SALES_NAME'] = ''
upline_rsme_3['LINE_MANAGER_1'] = ''
upline_rsme_3['LINE_MANAGER_2'] = upline_rsme_3['NPK_ASH'].astype(str) + ' - ' + upline_rsme_3['NAME_ASH']
upline_rsme_3['LINE_MANAGER_3'] = upline_rsme_3['NPK_RSH'].astype(str) + ' - ' + upline_rsme_3['NAME_RSH']
upline_rsme_3 = upline_rsme_3[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]

upline_rsme_3[upline_rsme_3['GCIF_NO'].duplicated(keep=False)]
#upline_rsme_3[upline_rsme_3.duplicated(keep=False)]

,GCIF_NO,SALES_NAME,LINE_MANAGER_1,LINE_MANAGER_2,LINE_MANAGER_3,AREA,REGION
0,G000729665,,,44150 - ERVANI DEVI NATALIA,20157 - HENDRO,YOGYAKARTA,JAWA TENGAH
1,G000729665,,,0 -,20157 - HENDRO,YOGYAKARTA,JAWA TENGAH
2,G000897876,,,44150 - ERVANI DEVI NATALIA,20157 - HENDRO,YOGYAKARTA,JAWA TENGAH
3,G000897876,,,0 -,20157 - HENDRO,YOGYAKARTA,JAWA TENGAH
4,G000958306,,,35774 - TOMMY SUHERMAN HASIM,43420 - YUDI SASTRA GUNAWAN,PALEMBANG,SUMATERA SELATAN
...,...,...,...,...,...,...,...
1074,G910675172,,,39913 - MARLIN TAYUWIJAYA,0 -,JAWA BARAT 3,JAWA BARAT
1076,G106261803,,,35774 - TOMMY SUHERMAN HASIM,43420 - YUDI SASTRA GUNAWAN,PALEMBANG,SUMATERA SELATAN
1077,G106261803,,,0 -,43420 - YUDI SASTRA GUNAWAN,PALEMBANG,SUMATERA SELATAN
1110,G010918290,,,35774 - TOMMY SUHERMAN HASIM,43420 - YUDI SASTRA GUNAWAN,PALEMBANG,SUMATERA SELATAN
1111,G010918290,,,0 -,43420 - YUDI SASTRA GUNAWAN,PALEMBANG,SUMATERA SELATAN

In [188]:
upline_rsme_1 = upline_rsme_1[~upline_rsme_1['NPK_RO'].isna()]

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma di 
upline_rsme_1['NPK_RO'] = upline_rsme_1['NPK_RO'].astype('int64')
upline_rsme_1['NPK_SMEM'] = upline_rsme_1['NPK_SMEM'].astype('int64')
upline_rsme_1['NPK_ASH'] = upline_rsme_1['NPK_ASH'].astype('int64')
upline_rsme_1['NPK_RSH'] = upline_rsme_1['NPK_RSH'].astype('int64')

upline_rsme_1['SALES_NAME'] = upline_rsme_1['NPK_RO'].astype(str) + ' - ' + upline_rsme_1['NAME_RO']
upline_rsme_1['LINE_MANAGER_1'] = upline_rsme_1['NPK_SMEM'].astype(str) + ' - ' + upline_rsme_1['NAME_SMEM']
upline_rsme_1['LINE_MANAGER_2'] = upline_rsme_1['NPK_ASH'].astype(str) + ' - ' + upline_rsme_1['NAME_ASH']
upline_rsme_1['LINE_MANAGER_3'] = upline_rsme_1['NPK_RSH'].astype(str) + ' - ' + upline_rsme_1['NAME_RSH']
upline_rsme_1 = upline_rsme_1[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]

upline_rsme_1[upline_rsme_1['GCIF_NO'].duplicated(keep=False)]
#upline_rsme_1[upline_rsme_1.duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, SALES_NAME, LINE_MANAGER_1, LINE_MANAGER_2, LINE_MANAGER_3, AREA, REGION]
Index: []

In [189]:
#upline_rsme_1['NPK_RO']=upline_rsme_1['NPK_RO'].fillna(0)
#upline_rsme_1['NPK_RO']=upline_rsme_1['NPK_RO'].astype('int64')
#upline_rsme_1['NPK_SMEM']=upline_rsme_1['NPK_SMEM'].fillna(0)
#upline_rsme_1['NPK_SMEM']=upline_rsme_1['NPK_SMEM'].astype('int64')
#upline_rsme_1['NPK_ASH']=upline_rsme_1['NPK_ASH'].fillna(0)
#upline_rsme_1['NPK_ASH']=upline_rsme_1['NPK_ASH'].astype('int64')
#upline_rsme_1['NPK_RSH']=upline_rsme_1['NPK_RSH'].fillna(0)
#upline_rsme_1['NPK_RSH']=upline_rsme_1['NPK_RSH'].astype('int64')

In [190]:
#CHECKPOINT
print(len(upline_rsme_1))
print(len(upline_rsme_3))
len(upline_rsme_1) + len(upline_rsme_3) == len(lending_rsme_1)

4804
1114

False

In [191]:
lending_rsme_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 541 entries, 0 to 6126
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    541 non-null    object
 1   NPK_MAINT  541 non-null    int64
 2   AREA       541 non-null    object
 3   REGION     137 non-null    object
 4   NPK_REFF   541 non-null    int64
 5   SOURCE     27 non-null     object
dtypes: int64(2), object(4)
memory usage: 29.6+ KB

In [192]:
upline_rsme_2 = lending_rsme_2.merge(hierarchy_smer_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates(),
                               left_on='AREA',right_on='AREA_ASH', how='left')
upline_rsme_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GCIF_NO     577 non-null    object
 1   NPK_MAINT   577 non-null    int64
 2   AREA        577 non-null    object
 3   REGION      173 non-null    object
 4   NPK_REFF    577 non-null    int64
 5   SOURCE      38 non-null     object
 6   AREA_ASH    136 non-null    object
 7   NPK_ASH     136 non-null    float64
 8   NAME_ASH    136 non-null    object
 9   NPK_RSH     136 non-null    float64
 10  NAME_RSH    136 non-null    object
 11  REGION_RSH  136 non-null    object
dtypes: float64(2), int64(2), object(8)
memory usage: 54.2+ KB

In [193]:
upline_rsme_2 = lending_rsme_2.merge(hierarchy_smer_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates(),
                               left_on='AREA',right_on='AREA_ASH', how='left')

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma di 
upline_rsme_2['NPK_ASH'] = upline_rsme_2['NPK_ASH'].fillna(0).astype('int64')
upline_rsme_2['NPK_RSH'] = upline_rsme_2['NPK_RSH'].fillna(0).astype('int64')

upline_rsme_2['SALES_NAME'] = ''
upline_rsme_2['LINE_MANAGER_1'] = ''
upline_rsme_2['LINE_MANAGER_2'] = upline_rsme_2['NPK_ASH'].astype(str) + ' - ' + upline_rsme_2['NAME_ASH']
upline_rsme_2['LINE_MANAGER_3'] = upline_rsme_2['NPK_RSH'].astype(str) + ' - ' + upline_rsme_2['NAME_RSH']
upline_rsme_2 = upline_rsme_2[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]

len(upline_rsme_2)

577

In [194]:
upline_rsme_lending = pd.concat([upline_rsme_1,upline_rsme_2,upline_rsme_3], axis=0)

#Add RD
upline_rsme_lending = upline_rsme_lending.merge(users[users['JABATAN']=='REGIONAL DIRECTOR'][['REGION','NPK','NAMA']],on='REGION',how='left')
upline_rsme_lending['NPK'] = upline_rsme_lending['NPK'].fillna(0).astype('int64')
upline_rsme_lending['LINE_MANAGER_4'] = upline_rsme_lending['NPK'].astype(str) + ' - ' + upline_rsme_lending['NAMA']
upline_rsme_lending = upline_rsme_lending[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4',
                                          'AREA','REGION']]

upline_rsme_lending.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6495 entries, 0 to 6494
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         6495 non-null   object
 1   SALES_NAME      6495 non-null   object
 2   LINE_MANAGER_1  6495 non-null   object
 3   LINE_MANAGER_2  6035 non-null   object
 4   LINE_MANAGER_3  6035 non-null   object
 5   LINE_MANAGER_4  6064 non-null   object
 6   AREA            6495 non-null   object
 7   REGION          6064 non-null   object
dtypes: object(8)
memory usage: 406.1+ KB

In [195]:
upline_rsme_lending['SALES_NAME'] = upline_rsme_lending['SALES_NAME'].fillna("")
upline_rsme_lending['LINE_MANAGER_1'] = upline_rsme_lending['LINE_MANAGER_1'].fillna("")
upline_rsme_lending['LINE_MANAGER_2'] = upline_rsme_lending['LINE_MANAGER_2'].fillna("")
upline_rsme_lending['LINE_MANAGER_3'] = upline_rsme_lending['LINE_MANAGER_3'].fillna("")

upline_rsme_lending['SALES_NAME'] = np.where(upline_rsme_lending['SALES_NAME'] == '0 - ',
                                            "",upline_rsme_lending['SALES_NAME'])
upline_rsme_lending['LINE_MANAGER_1'] = np.where(upline_rsme_lending['LINE_MANAGER_1'] == '0 - ',
                                            "",upline_rsme_lending['LINE_MANAGER_1'])
upline_rsme_lending['LINE_MANAGER_2'] = np.where(upline_rsme_lending['LINE_MANAGER_2'] == '0 - ',
                                            "",upline_rsme_lending['LINE_MANAGER_2'])
upline_rsme_lending['LINE_MANAGER_3'] = np.where(upline_rsme_lending['LINE_MANAGER_3'] == '0 - ',
                                            "",upline_rsme_lending['LINE_MANAGER_3'])

In [196]:
#CHECKPOINT UPLINE
print(len(upline_rsme_1) + len(upline_rsme_3) + len(upline_rsme_2) == len(lending_rsme))
print(len(upline_rsme_lending) == len(lending_rsme))

False
False

In [197]:
print(len(upline_rsme_lending))
print(len(lending_rsme))

6495
6127

In [198]:
upline_rsme_lending[upline_rsme_lending['GCIF_NO']=='G000210070']

,GCIF_NO,SALES_NAME,LINE_MANAGER_1,LINE_MANAGER_2,LINE_MANAGER_3,LINE_MANAGER_4,AREA,REGION
0,G000210070,"42929 - CLARISA JUWANA, SE",35088 - TIMOTI HENDRO,31893 - GUNANTO SUHARTONO,42131 - DEBBY NATALIA,34571 - INDRAJANI HARSONO,SURABAYA,"JATIM, BALI & NUSRA"

In [199]:
upline_rsme_lending[upline_rsme_lending['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

,GCIF_NO,SALES_NAME,LINE_MANAGER_1,LINE_MANAGER_2,LINE_MANAGER_3,LINE_MANAGER_4,AREA,REGION
5381,G000729665,,,44150 - ERVANI DEVI NATALIA,20157 - HENDRO,15671 - DEWI IRAWATI,YOGYAKARTA,JAWA TENGAH
5382,G000729665,,,,20157 - HENDRO,15671 - DEWI IRAWATI,YOGYAKARTA,JAWA TENGAH
5383,G000897876,,,44150 - ERVANI DEVI NATALIA,20157 - HENDRO,15671 - DEWI IRAWATI,YOGYAKARTA,JAWA TENGAH
5384,G000897876,,,,20157 - HENDRO,15671 - DEWI IRAWATI,YOGYAKARTA,JAWA TENGAH
5385,G000958306,,,35774 - TOMMY SUHERMAN HASIM,43420 - YUDI SASTRA GUNAWAN,17239 - SUTARDI,PALEMBANG,SUMATERA SELATAN
...,...,...,...,...,...,...,...,...
6444,G910190248,,,,43420 - YUDI SASTRA GUNAWAN,17239 - SUTARDI,PALEMBANG,SUMATERA SELATAN
6451,G910544790,,,24446 - HENNY YULIANTI OESMAN,,38355 - MUHAMMAD HUSNI HS,JAWA BARAT 2,JAWA BARAT
6452,G910544790,,,39913 - MARLIN TAYUWIJAYA,,38355 - MUHAMMAD HUSNI HS,JAWA BARAT 2,JAWA BARAT
6454,G910675172,,,24446 - HENNY YULIANTI OESMAN,,38355 - MUHAMMAD HUSNI HS,JAWA BARAT 3,JAWA BARAT
6455,G910675172,,,39913 - MARLIN TAYUWIJAYA,,38355 - MUHAMMAD HUSNI HS,JAWA BARAT 3,JAWA BARAT

## 14. BASELINE - SME+

In [200]:
len(lending_smeplus)

591

In [201]:
# lending_smeplus['REGION'] = np.where(lending_smeplus['REGION'].isna(),
#                                     lending_smeplus['AREA'],
#                                     lending_smeplus['REGION'])

In [202]:
lending_smeplus_a = lending_smeplus.merge(ro_list_smeplus,
                                   left_on='NPK_MAINT',
                                   right_on='NPK',
                                   how='left')
lending_smeplus_a.columns = ['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION',
       'NPK_REFF', 'SOURCE', 'NPK_by_NPKMAINT', 'NAME_by_NPKMAINT', 'JABATAN_by_NPKMAINT']
lending_smeplus_a.info()
# lending_smeplus_a[lending_smeplus_a['GCIF_NO']=='G509742367']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GCIF_NO              591 non-null    object
 1   NPK_MAINT            591 non-null    int64
 2   AREA                 383 non-null    object
 3   REGION               581 non-null    object
 4   NPK_REFF             591 non-null    int64
 5   SOURCE               591 non-null    object
 6   NPK_by_NPKMAINT      545 non-null    float64
 7   NAME_by_NPKMAINT     545 non-null    object
 8   JABATAN_by_NPKMAINT  545 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 41.7+ KB

In [203]:
lending_smeplus_b = lending_smeplus_a.merge(ro_list_smeplus,
                                   left_on='NPK_REFF',
                                   right_on='NPK',
                                   how='left')
lending_smeplus_b.columns = ['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION',
       'NPK_REFF', 'SOURCE', 'NPK_by_NPKMAINT', 'NAME_by_NPKMAINT',
       'JABATAN_by_NPKMAINT', 'NPK_by_NPKREFF', 'NAME_by_NPKREFF', 'JABATAN_by_NPKREFF']
lending_smeplus_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GCIF_NO              591 non-null    object
 1   NPK_MAINT            591 non-null    int64
 2   AREA                 383 non-null    object
 3   REGION               581 non-null    object
 4   NPK_REFF             591 non-null    int64
 5   SOURCE               591 non-null    object
 6   NPK_by_NPKMAINT      545 non-null    float64
 7   NAME_by_NPKMAINT     545 non-null    object
 8   JABATAN_by_NPKMAINT  545 non-null    object
 9   NPK_by_NPKREFF       21 non-null     float64
 10  NAME_by_NPKREFF      21 non-null     object
 11  JABATAN_by_NPKREFF   21 non-null     object
dtypes: float64(2), int64(2), object(8)
memory usage: 55.5+ KB

In [204]:
lending_smeplus_b[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER     17
                      NaN                     528
NaN                   RELATIONSHIP OFFICER      4
                      NaN                      42
Name: count, dtype: int64

### 14.1 RO Baseline

In [205]:
lending_smeplus_ro = lending_smeplus_b[(lending_smeplus_b['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER')
                                       | (lending_smeplus_b['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER')]
lending_smeplus_ro[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER     17
                      NaN                     528
NaN                   RELATIONSHIP OFFICER      4
Name: count, dtype: int64

In [206]:
lending_smeplus_ro['NPK'] = np.where(((lending_smeplus_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_smeplus_ro['JABATAN_by_NPKREFF'] != 'RELATIONSHIP OFFICER'))
                                    | ((lending_smeplus_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_smeplus_ro['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER') & (lending_smeplus_ro['NPK_by_NPKREFF'] == 0)),
                                    lending_smeplus_ro['NPK_by_NPKMAINT'],
                                    lending_smeplus_ro['NPK_by_NPKREFF'])
# lending_smeplus_ro['NPK'] = np.where(lending_smeplus_ro['JABATAN_by_NPKREFF'] == 'RELATIONSHIP OFFICER',
#                                            lending_smeplus_ro['NPK_by_NPKREFF'],
#                                            lending_smeplus_ro['NPK'])
lending_smeplus_ro['NPK']=lending_smeplus_ro['NPK'].astype('float')
lending_smeplus_ro['NPK']=lending_smeplus_ro['NPK'].astype('int64')

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\1553864326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_smeplus_ro['NPK'] = np.where(((lending_smeplus_ro['JABATAN_by_NPKMAINT'] == 'RELATIONSHIP OFFICER') & (lending_smeplus_ro['JABATAN_by_NPKREFF'] != 'RELATIONSHIP OFFICER'))
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\1553864326.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_smeplus_ro['NPK']=lending_smeplus_ro['NPK'].astype('float')
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\1553864326.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lending_smeplus_ro['NPK']=lending_smeplus_ro['NPK'].astype('int64')

In [207]:
#Add name and jabatan dari final NPK RO
baseline_ro_smeplus = lending_smeplus_ro.merge(ro_list_smeplus,
                                   on='NPK',
                                   how='left')
baseline_ro_smeplus = baseline_ro_smeplus[['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']]

baseline_ro_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  549 non-null    object
 1   NPK      549 non-null    int64
 2   NAMA     549 non-null    object
 3   JABATAN  549 non-null    object
 4   AREA     357 non-null    object
 5   REGION   539 non-null    object
dtypes: int64(1), object(5)
memory usage: 25.9+ KB

In [208]:
baseline_ro_smeplus = baseline_ro_smeplus[baseline_ro_smeplus['NPK']!=0]

In [209]:
baseline_ro_smeplus[baseline_ro_smeplus['GCIF_NO']=='G803453844']

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION
430,G803453844,43012,DEA GIOVANI,RELATIONSHIP OFFICER,JAKARTA 1A,JAKARTA 1

### 14.2 Mapping Baseline ASH

In [210]:
len(lending_smeplus)

591

In [211]:
lending_smeplus_b[['JABATAN_by_NPKMAINT','JABATAN_by_NPKREFF']].value_counts(dropna=False).sort_index()

JABATAN_by_NPKMAINT   JABATAN_by_NPKREFF
RELATIONSHIP OFFICER  RELATIONSHIP OFFICER     17
                      NaN                     528
NaN                   RELATIONSHIP OFFICER      4
                      NaN                      42
Name: count, dtype: int64

In [212]:
print(len(lending_smeplus))
#Add from lending_smeplus_b:
print(len(lending_smeplus_b[(lending_smeplus_b['JABATAN_by_NPKMAINT'].isna()) & (lending_smeplus_b['JABATAN_by_NPKREFF'].isna())]))
#Mapped in SMEM and RO
print(len(baseline_ro_smeplus) #Mapped in RO
      # +len(lending_smeplus_b[(lending_smeplus_b['JABATAN_by_NPKMAINT'].isna()) & (lending_smeplus_b['JABATAN_by_NPKREFF'].isna())]) #Add from lending_smeplus_b
      + len(lending_smeplus[~(lending_smeplus['GCIF_NO'].isin(baseline_ro_smeplus['GCIF_NO']))])
      ) #Doesn't have RO

591
42
591

In [213]:
baseline_ash_smeplus_hierarchy = baseline_ro_smeplus
baseline_ash_smeplus_area = lending_smeplus[~(lending_smeplus['GCIF_NO'].isin(baseline_ro_smeplus['GCIF_NO']))]
print(len(baseline_ash_smeplus_hierarchy)+len(baseline_ash_smeplus_area)==len(lending_smeplus))

True

In [214]:
baseline_ash_smeplus_hierarchy = baseline_ash_smeplus_hierarchy.merge(hierarchy_smeplus[['NPK_RO','NPK_ASH','NAME_ASH']].drop_duplicates(),
                                                                    how='left', left_on='NPK',right_on='NPK_RO')
baseline_ash_smeplus_hierarchy = baseline_ash_smeplus_hierarchy[baseline_ash_smeplus_hierarchy['NPK_ASH'] != 0]
baseline_ash_smeplus_hierarchy['JABATAN'] = 'AREA SME HEAD'
baseline_ash_smeplus_hierarchy = baseline_ash_smeplus_hierarchy[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN','AREA', 'REGION']]
baseline_ash_smeplus_hierarchy.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_ash_smeplus_hierarchy.info()
baseline_ash_smeplus_hierarchy[baseline_ash_smeplus_hierarchy['GCIF_NO']=='G210122792']

<class 'pandas.core.frame.DataFrame'>
Index: 396 entries, 0 to 545
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  396 non-null    object
 1   NPK      396 non-null    int64
 2   NAMA     396 non-null    object
 3   JABATAN  396 non-null    object
 4   AREA     263 non-null    object
 5   REGION   388 non-null    object
dtypes: int64(1), object(5)
memory usage: 21.7+ KB

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION
119,G210122792,43351,ATHUR ALMANSO SIAGIAN,AREA SME HEAD,JAKARTA 2C,JAKARTA 2

In [215]:
lending_smeplus[lending_smeplus['GCIF_NO']=='G200800944']

        GCIF_NO  NPK_MAINT        AREA     REGION  NPK_REFF SOURCE
101  G200800944       8884  JAKARTA 3B  JAKARTA 3     39838    CRS

In [216]:
hierarchy_smeplus[['AREA_ASH','NPK_ASH','NAME_ASH']]

            AREA_ASH  NPK_ASH  NAME_ASH
0   SUMATERA UTARA 1    40523  KRISTINA
1   SUMATERA UTARA 1    40523  KRISTINA
2   SUMATERA UTARA 1    40523  KRISTINA
3   SUMATERA UTARA 1    40523  KRISTINA
4   SUMATERA UTARA 1    40523  KRISTINA
..               ...      ...       ...
71  SULAWESI & IBT A        0
72  SULAWESI & IBT A        0
73  SULAWESI & IBT A        0
74  SULAWESI & IBT A        0
75  SULAWESI & IBT A        0

[76 rows x 3 columns]

In [217]:
baseline_ash_smeplus_area = baseline_ash_smeplus_area.merge(hierarchy_smeplus[['AREA_ASH','NPK_ASH','NAME_ASH']].drop_duplicates(),
                                                      left_on='AREA',right_on='AREA_ASH',how='left')
baseline_ash_smeplus_area = baseline_ash_smeplus_area[~baseline_ash_smeplus_area['NPK_ASH'].isna()]
baseline_ash_smeplus_area = baseline_ash_smeplus_area[baseline_ash_smeplus_area['NPK_ASH']!=0]
baseline_ash_smeplus_area['JABATAN'] = 'AREA SME HEAD'
baseline_ash_smeplus_area = baseline_ash_smeplus_area[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN','AREA', 'REGION']]
baseline_ash_smeplus_area.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_ash_smeplus_area.info()
# baseline_ash_smeplus_area[baseline_ash_smeplus_area['GCIF_NO']=='G000734004']

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 2 to 41
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  20 non-null     object
 1   NPK      20 non-null     float64
 2   NAMA     20 non-null     object
 3   JABATAN  20 non-null     object
 4   AREA     20 non-null     object
 5   REGION   20 non-null     object
dtypes: float64(1), object(5)
memory usage: 1.1+ KB

In [218]:
baseline_ash_smeplus_area[baseline_ash_smeplus_area['NPK']==0]

Empty DataFrame
Columns: [GCIF_NO, NPK, NAMA, JABATAN, AREA, REGION]
Index: []

In [219]:
baseline_ash_smeplus = pd.concat([baseline_ash_smeplus_area,baseline_ash_smeplus_hierarchy], axis=0)
baseline_ash_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 416 entries, 2 to 545
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  416 non-null    object
 1   NPK      416 non-null    float64
 2   NAMA     416 non-null    object
 3   JABATAN  416 non-null    object
 4   AREA     283 non-null    object
 5   REGION   408 non-null    object
dtypes: float64(1), object(5)
memory usage: 22.8+ KB

In [220]:
# baseline_ash_smeplus = lending_smeplus.merge(hierarchy_smeplus_clean[['AREA_ASH','NPK_ASH','NAME_ASH']].drop_duplicates(keep='first'),
#                          left_on='AREA',right_on='AREA_ASH',
#                          how='left')
# baseline_ash_smeplus.info()
# baseline_ash_smeplus = baseline_ash_smeplus[baseline_ash_smeplus['NPK_ASH'] != 0]
# baseline_ash_smeplus['JABATAN'] = 'AREA SME HEAD'
# baseline_ash_smeplus = baseline_ash_smeplus[['GCIF_NO', 'NPK_ASH', 'NAME_ASH', 'JABATAN', 'AREA', 'REGION']]
# baseline_ash_smeplus.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
# baseline_ash_smeplus.info()

In [221]:
lending_smeplus[~lending_smeplus['REGION'].isin(hierarchy_smeplus['REGION_RSH'])]['REGION'].value_counts(dropna=False)

REGION
NaN    10
Name: count, dtype: int64

In [222]:
# baseline_ash_smeplus['REGION'] = np.where(baseline_ash_smeplus['NPK'] == '39563',
# #                                          'JAKARTA 3',
#                                          baseline_ash_smeplus['REGION'])

### 14.3 Mapping Baseline RSH

In [223]:
baseline_rsh_smeplus = lending_smeplus.merge(hierarchy_smeplus_clean[['REGION_RSH','NPK_RSH','NAME_RSH']].drop_duplicates(keep='first'),
                         left_on='REGION',right_on='REGION_RSH',
                         how='left')
baseline_rsh_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GCIF_NO     591 non-null    object
 1   NPK_MAINT   591 non-null    int64
 2   AREA        383 non-null    object
 3   REGION      581 non-null    object
 4   NPK_REFF    591 non-null    int64
 5   SOURCE      591 non-null    object
 6   REGION_RSH  581 non-null    object
 7   NPK_RSH     581 non-null    float64
 8   NAME_RSH    581 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 41.7+ KB

In [224]:
baseline_rsh_smeplus = baseline_rsh_smeplus[baseline_rsh_smeplus['NPK_RSH'] != 0]

In [225]:
baseline_rsh_smeplus['JABATAN'] = 'REGIONAL SME HEAD'
baseline_rsh_smeplus = baseline_rsh_smeplus[['GCIF_NO', 'NPK_RSH', 'NAME_RSH', 'JABATAN', 'AREA', 'REGION']]
baseline_rsh_smeplus.columns = ['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION']
baseline_rsh_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 405 entries, 2 to 589
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  405 non-null    object
 1   NPK      395 non-null    float64
 2   NAMA     395 non-null    object
 3   JABATAN  405 non-null    object
 4   AREA     251 non-null    object
 5   REGION   395 non-null    object
dtypes: float64(1), object(5)
memory usage: 22.1+ KB

### 14.4 Append RO, SMEM, ASH, RSH mapping and add email

In [226]:
# #Append ALl
# print(baseline_ro_smeplus.columns)
# print(baseline_ash_smeplus.columns)
# print(baseline_rsh_smeplus.columns)

baseline_smeplus = pd.concat([baseline_ro_smeplus,baseline_ash_smeplus,baseline_rsh_smeplus], axis=0)
len(baseline_smeplus)

1367

In [227]:
users['NPK'] = users['NPK'].astype('int64')
baseline_smeplus_with_email = baseline_smeplus.merge(users[['NPK','EMAIL_KARYAWAN']],
                          on='NPK',how='left')
baseline_smeplus_with_email.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1367 entries, 0 to 1366
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         1367 non-null   object
 1   NPK             1357 non-null   float64
 2   NAMA            1357 non-null   object
 3   JABATAN         1367 non-null   object
 4   AREA            888 non-null    object
 5   REGION          1339 non-null   object
 6   EMAIL_KARYAWAN  1289 non-null   object
dtypes: float64(1), object(6)
memory usage: 74.9+ KB

In [228]:
#CHECKPOINT: ada EMAIL yang NA ga? Kalo ya, berarti baru masuk Hierarchy
baseline_smeplus_with_email[baseline_smeplus_with_email['EMAIL_KARYAWAN'].isna()].drop_duplicates('NPK')

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION,EMAIL_KARYAWAN
0,G000576256,"44,183.0",REINALDY TJAHJA,RELATIONSHIP OFFICER,None,JAWA BARAT,NaN
8,G004111704,"44,290.0",MERLINA,RELATIONSHIP OFFICER,JAKARTA 2A,JAKARTA 2,NaN
42,G010327906,"44,112.0",VERA TRIANY,RELATIONSHIP OFFICER,JAKARTA 2A,JAKARTA 2,NaN
43,G010392827,"44,206.0",MURNI OSHIN EVANGELISTA NAPITUPULU,RELATIONSHIP OFFICER,SUMATERA UTARA 3,SUMATERA UTARA,NaN
78,G109682179,"44,303.0",RATNA SAGITA,RELATIONSHIP OFFICER,JAKARTA 2A,JAKARTA 2,NaN
85,G110332657,"44,275.0",KHUN SU,RELATIONSHIP OFFICER,JAKARTA 2C,JAKARTA 2,NaN
106,G208631770,"44,107.0",STEVEN PRATAMA,RELATIONSHIP OFFICER,None,"JATIM, BALI & NUSRA",NaN
139,G300758711,"44,295.0",NOVIANA SORIP,RELATIONSHIP OFFICER,JAKARTA 2B,JAKARTA 2,NaN
549,G110974367,"44,233.0",PUTRI LAUDHA,AREA SME HEAD,JAKARTA 3A,JAKARTA 3,NaN
980,G009088675,NaN,NaN,REGIONAL SME HEAD,None,NaN,NaN

### 14.5 Mapping Baseline RD

In [229]:
users['NPK'] = users['NPK'].astype('int64')
baseline_rd_smeplus = lending_smeplus.merge(users[users['JABATAN']=='REGIONAL DIRECTOR'][['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
                  on='REGION',how='left')
baseline_rd_smeplus = baseline_rd_smeplus[['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION','EMAIL_KARYAWAN']]
len(baseline_rd_smeplus) == len(lending_smeplus)

True

### 14.6 Mapping Baseline Admin

In [230]:
baseline_admin_smeplus = lending_smeplus[['GCIF_NO','REGION']].merge(email_map_admin,on='REGION',how='left')
baseline_admin_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2915 entries, 0 to 2914
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         2915 non-null   object
 1   REGION          2905 non-null   object
 2   NPK             2905 non-null   float64
 3   NAMA            2905 non-null   object
 4   JABATAN         2905 non-null   object
 5   EMAIL_KARYAWAN  2905 non-null   object
dtypes: float64(1), object(5)
memory usage: 136.8+ KB

In [231]:
baseline_admin_smeplus[['NAMA']].value_counts(dropna=False).sort_index()

NAMA
AHMAD HUMAEDI                    581
DIMAS FEBRIATMOKO                581
IZZA RANNISA                     581
JESVIKA SARI MELYNA SIHOMBING    581
SITI AISYAH                      581
NaN                               10
Name: count, dtype: int64

### 14.7 Mapping Baseline RRB

In [232]:
baseline_admin_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2915 entries, 0 to 2914
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         2915 non-null   object
 1   REGION          2905 non-null   object
 2   NPK             2905 non-null   float64
 3   NAMA            2905 non-null   object
 4   JABATAN         2905 non-null   object
 5   EMAIL_KARYAWAN  2905 non-null   object
dtypes: float64(1), object(5)
memory usage: 136.8+ KB

In [233]:
lending_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GCIF_NO    591 non-null    object
 1   NPK_MAINT  591 non-null    int64
 2   AREA       383 non-null    object
 3   REGION     581 non-null    object
 4   NPK_REFF   591 non-null    int64
 5   SOURCE     591 non-null    object
dtypes: int64(2), object(4)
memory usage: 27.8+ KB

In [234]:
baseline_rrb_smeplus = lending_smeplus[['GCIF_NO','REGION']].merge(users[users['JABATAN']=='REGIONAL RETAIL BANKING HEAD'][['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
                                 on='REGION',how='left')
baseline_rrb_smeplus = baseline_rrb_smeplus[~baseline_rrb_smeplus['NPK'].isna()]
baseline_rrb_smeplus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 528 entries, 0 to 590
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         528 non-null    object
 1   REGION          528 non-null    object
 2   NPK             528 non-null    float64
 3   NAMA            528 non-null    object
 4   JABATAN         528 non-null    object
 5   EMAIL_KARYAWAN  528 non-null    object
dtypes: float64(1), object(5)
memory usage: 28.9+ KB

### 14.8 Combine All Baseline

In [235]:
# print(baseline_smeplus_with_email.columns)
# print(baseline_rd_smeplus.columns)
# print(baseline_admin_smeplus.columns)

baseline_smeplus_lending = pd.concat([baseline_smeplus_with_email, baseline_rd_smeplus,
                                      baseline_admin_smeplus,baseline_rrb_smeplus])
baseline_smeplus_lending.info()
#NOTE: NA AREA = Jabatan ADMIN

<class 'pandas.core.frame.DataFrame'>
Index: 5401 entries, 0 to 590
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         5401 non-null   object
 1   NPK             5371 non-null   float64
 2   NAMA            5371 non-null   object
 3   JABATAN         5381 non-null   object
 4   AREA            1271 non-null   object
 5   REGION          5353 non-null   object
 6   EMAIL_KARYAWAN  5303 non-null   object
dtypes: float64(1), object(6)
memory usage: 337.6+ KB

In [236]:
#CHECKPOINT: 
baseline_smeplus_lending[baseline_smeplus_lending['EMAIL_KARYAWAN'].isna()][['NPK','NAMA','JABATAN']].drop_duplicates()

         NPK                                NAMA               JABATAN
0   44,183.0                     REINALDY TJAHJA  RELATIONSHIP OFFICER
8   44,290.0                             MERLINA  RELATIONSHIP OFFICER
42  44,112.0                         VERA TRIANY  RELATIONSHIP OFFICER
43  44,206.0  MURNI OSHIN EVANGELISTA NAPITUPULU  RELATIONSHIP OFFICER
78  44,303.0                        RATNA SAGITA  RELATIONSHIP OFFICER
85  44,275.0                             KHUN SU  RELATIONSHIP OFFICER
106 44,107.0                      STEVEN PRATAMA  RELATIONSHIP OFFICER
139 44,295.0                       NOVIANA SORIP  RELATIONSHIP OFFICER
549 44,233.0                        PUTRI LAUDHA         AREA SME HEAD
980      NaN                                 NaN     REGIONAL SME HEAD
27       NaN                                 NaN                   NaN

In [237]:
# baseline_smeplus_lending = baseline_smeplus_lending[~baseline_smeplus_lending['NPK'].isna()]

In [238]:
baseline_smeplus_lending[baseline_smeplus_lending['GCIF_NO']=='G803453844']

,GCIF_NO,NPK,NAMA,JABATAN,AREA,REGION,EMAIL_KARYAWAN
430,G803453844,"43,012.0",DEA GIOVANI,RELATIONSHIP OFFICER,JAKARTA 1A,JAKARTA 1,dea.giovani2@maybank.co.id
880,G803453844,"40,017.0",MICHAILA LAURENS,AREA SME HEAD,JAKARTA 1A,JAKARTA 1,michaila@maybank.co.id
1286,G803453844,"41,620.0",MARTINUS TOMMY ADE IRAWAN,REGIONAL SME HEAD,JAKARTA 1A,JAKARTA 1,martinus.irawan@maybank.co.id
466,G803453844,"39,717.0",WAN JUSLIAN JOHAN,REGIONAL DIRECTOR,JAKARTA 1A,JAKARTA 1,jwjohan@maybank.co.id
2298,G803453844,"38,810.0",AHMAD HUMAEDI,ADMIN,NaN,JAKARTA 1,a.humaedi@maybank.co.id
2299,G803453844,"38,713.0",DIMAS FEBRIATMOKO,ADMIN,NaN,JAKARTA 1,dfebriatmoko@maybank.co.id
2300,G803453844,"36,690.0",IZZA RANNISA,ADMIN,NaN,JAKARTA 1,izza.r@maybank.co.id
2301,G803453844,"37,500.0",JESVIKA SARI MELYNA SIHOMBING,ADMIN,NaN,JAKARTA 1,jsmsihombing@maybank.co.id
2302,G803453844,"38,440.0",SITI AISYAH,ADMIN,NaN,JAKARTA 1,siti.aisyah@maybank.co.id
466,G803453844,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,NaN,JAKARTA 1,hswinata@maybank.co.id

## 15. UPLINE - SMEPLUS

In [239]:
lending_smeplus_1 = lending_smeplus[lending_smeplus['NPK_MAINT'] != 0]
lending_smeplus_2 = lending_smeplus[lending_smeplus['NPK_MAINT'] == 0]
print(lending_smeplus_1.shape)
print(lending_smeplus_2.shape)

len(lending_smeplus_2) + len(lending_smeplus_1) == len(lending_smeplus)

(591, 6)
(0, 6)

True

In [240]:
upline_smeplus_1 = lending_smeplus_1.merge(hierarchy_smeplus_clean[['NPK_RO','NAME_RO','BRANCH_RO',
                                                    #  'NPK_SMEM','NAME_SMEM',
                                                     'NPK_ASH','NAME_ASH','AREA_ASH',
                                                     'NPK_RSH','NAME_RSH','REGION_RSH']].drop_duplicates(),
                         left_on='NPK_MAINT',right_on='NPK_RO',
                         how='left')
upline_smeplus_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GCIF_NO     591 non-null    object
 1   NPK_MAINT   591 non-null    int64
 2   AREA        383 non-null    object
 3   REGION      581 non-null    object
 4   NPK_REFF    591 non-null    int64
 5   SOURCE      591 non-null    object
 6   NPK_RO      545 non-null    float64
 7   NAME_RO     545 non-null    object
 8   BRANCH_RO   545 non-null    object
 9   NPK_ASH     545 non-null    float64
 10  NAME_ASH    545 non-null    object
 11  AREA_ASH    545 non-null    object
 12  NPK_RSH     545 non-null    float64
 13  NAME_RSH    545 non-null    object
 14  REGION_RSH  545 non-null    object
dtypes: float64(3), int64(2), object(10)
memory usage: 69.4+ KB

In [241]:
lending_smeplus_1[lending_smeplus_1['GCIF_NO']=='G200800944']

        GCIF_NO  NPK_MAINT        AREA     REGION  NPK_REFF SOURCE
101  G200800944       8884  JAKARTA 3B  JAKARTA 3     39838    CRS

In [242]:
upline_smeplus_1[upline_smeplus_1['GCIF_NO']=='G200800944']

,GCIF_NO,NPK_MAINT,AREA,REGION,NPK_REFF,SOURCE,NPK_RO,NAME_RO,BRANCH_RO,NPK_ASH,NAME_ASH,AREA_ASH,NPK_RSH,NAME_RSH,REGION_RSH
101,G200800944,8884,JAKARTA 3B,JAKARTA 3,39838,CRS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [243]:
upline_smeplus_3 = upline_smeplus_1[upline_smeplus_1['NPK_RO'].isna()]
upline_smeplus_3[upline_smeplus_3['GCIF_NO']=='G200800944']

,GCIF_NO,NPK_MAINT,AREA,REGION,NPK_REFF,SOURCE,NPK_RO,NAME_RO,BRANCH_RO,NPK_ASH,NAME_ASH,AREA_ASH,NPK_RSH,NAME_RSH,REGION_RSH
101,G200800944,8884,JAKARTA 3B,JAKARTA 3,39838,CRS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
hierarchy_smeplus_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates()[hierarchy_smeplus_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates()['AREA_ASH']=='JAKARTA 3']

Empty DataFrame
Columns: [AREA_ASH, NPK_ASH, NAME_ASH, NPK_RSH, NAME_RSH, REGION_RSH]
Index: []

In [245]:
upline_smeplus_3 = upline_smeplus_1[upline_smeplus_1['NPK_RO'].isna()]

upline_smeplus_3 = upline_smeplus_3[['GCIF_NO', 'NPK_MAINT', 'AREA', 'REGION','SOURCE']]
upline_smeplus_3 = upline_smeplus_3.merge(hierarchy_smeplus_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates(),
                               left_on='AREA',right_on='AREA_ASH', how='left')

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma di 
upline_smeplus_3['NPK_ASH'] = upline_smeplus_3['NPK_ASH'].fillna(0)
upline_smeplus_3['NPK_ASH'] = upline_smeplus_3['NPK_ASH'].astype('int64')
upline_smeplus_3['NPK_RSH'] = upline_smeplus_3['NPK_ASH'].fillna(0)
upline_smeplus_3['NPK_RSH'] = upline_smeplus_3['NPK_RSH'].astype('int64')

upline_smeplus_3['SALES_NAME'] = ''
upline_smeplus_3['LINE_MANAGER_1'] = ''
upline_smeplus_3['LINE_MANAGER_2'] = upline_smeplus_3['NPK_ASH'].astype(str) + ' - ' + upline_smeplus_3['NAME_ASH']
upline_smeplus_3['LINE_MANAGER_3'] = upline_smeplus_3['NPK_RSH'].astype(str) + ' - ' + upline_smeplus_3['NAME_RSH']
upline_smeplus_3 = upline_smeplus_3[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]
# upline_smeplus_3.head()

upline_smeplus_3[upline_smeplus_3['GCIF_NO'].duplicated(keep=False)]
#upline_smeplus_2[upline_smeplus_2.duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, SALES_NAME, LINE_MANAGER_1, LINE_MANAGER_2, LINE_MANAGER_3, AREA, REGION]
Index: []

In [246]:
upline_smeplus_1 = upline_smeplus_1[~upline_smeplus_1['NPK_RO'].isna()]

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma
upline_smeplus_1['NPK_RO'] = upline_smeplus_1['NPK_RO'].astype('int64')
# upline_smeplus_1['NPK_SMEM'] = np.where(upline_smeplus_1['NPK_SMEM'].isna(),0,upline_smeplus_1['NPK_SMEM'])
# upline_smeplus_1['NPK_SMEM'] = upline_smeplus_1['NPK_SMEM'].astype('int64')
upline_smeplus_1['NPK_ASH'] = upline_smeplus_1['NPK_ASH'].astype('int64')
upline_smeplus_1['NPK_RSH'] = upline_smeplus_1['NPK_RSH'].astype('int64')

upline_smeplus_1['SALES_NAME'] = upline_smeplus_1['NPK_RO'].astype(str) + ' - ' + upline_smeplus_1['NAME_RO']
# upline_smeplus_1['LINE_MANAGER_1'] = upline_smeplus_1['NPK_SMEM'].astype(str) + ' - ' + upline_smeplus_1['NAME_SMEM']
upline_smeplus_1['LINE_MANAGER_1'] = ''
upline_smeplus_1['LINE_MANAGER_2'] = upline_smeplus_1['NPK_ASH'].astype(str) + ' - ' + upline_smeplus_1['NAME_ASH']
upline_smeplus_1['LINE_MANAGER_3'] = upline_smeplus_1['NPK_RSH'].astype(str) + ' - ' + upline_smeplus_1['NAME_RSH']
upline_smeplus_1 = upline_smeplus_1[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]
# upline_smeplus_1.head(20)

upline_smeplus_1[upline_smeplus_1['GCIF_NO'].duplicated(keep=False)]
#upline_smeplus_1[upline_smeplus_1.duplicated(keep=False)]

Empty DataFrame
Columns: [GCIF_NO, SALES_NAME, LINE_MANAGER_1, LINE_MANAGER_2, LINE_MANAGER_3, AREA, REGION]
Index: []

In [247]:
len(upline_smeplus_1) + len(upline_smeplus_3) > len(lending_smeplus_1)

False

In [248]:
len(lending_smeplus_1)

591

In [249]:
print(len(upline_smeplus_1))
print(len(upline_smeplus_3))
len(upline_smeplus_1) + len(upline_smeplus_3) == len(lending_smeplus_1)

545
46

True

In [250]:
upline_smeplus_2 = lending_smeplus_2.merge(hierarchy_smeplus_clean[['AREA_ASH','NPK_ASH','NAME_ASH','NPK_RSH',
                                                     'NAME_RSH','REGION_RSH']].drop_duplicates(),
                               left_on='AREA',right_on='AREA_ASH', how='left')

#Adjust data type kolom-kolom NPK supaya di Upline tidak ada tanda koma di 
upline_smeplus_2['NPK_ASH'] = upline_smeplus_2['NPK_ASH'].fillna(0)
upline_smeplus_2['NPK_RSH'] = upline_smeplus_2['NPK_ASH'].fillna(0)
upline_smeplus_2['NPK_ASH'] = upline_smeplus_2['NPK_ASH'].astype('int64')
upline_smeplus_2['NPK_RSH'] = upline_smeplus_2['NPK_RSH'].astype('int64')

upline_smeplus_2['SALES_NAME'] = ''
upline_smeplus_2['LINE_MANAGER_1'] = ''
upline_smeplus_2['LINE_MANAGER_2'] = upline_smeplus_2['NPK_ASH'].astype(str) + ' - ' + upline_smeplus_2['NAME_ASH']
upline_smeplus_2['LINE_MANAGER_3'] = upline_smeplus_2['NPK_RSH'].astype(str) + ' - ' + upline_smeplus_2['NAME_RSH']
upline_smeplus_2 = upline_smeplus_2[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','AREA','REGION']]
len(upline_smeplus_2)

0

In [251]:
upline_smeplus_lending = pd.concat([upline_smeplus_1,upline_smeplus_2,upline_smeplus_3],axis=0)

#Add RD
upline_smeplus_lending = upline_smeplus_lending.merge(users[users['JABATAN']=='REGIONAL DIRECTOR'][['REGION','NPK','NAMA']],on='REGION',how='left')
#upline_smeplus_lending['NPK'] = upline_smeplus_lending['NPK'].astype('int64')
upline_smeplus_lending['NPK'] = (upline_smeplus_lending['NPK'].fillna(0).astype('int64'))
upline_smeplus_lending['LINE_MANAGER_4'] = upline_smeplus_lending['NPK'].astype(str) + ' - ' + upline_smeplus_lending['NAMA']
upline_smeplus_lending = upline_smeplus_lending[['GCIF_NO','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4',
                                                'AREA','REGION']]
upline_smeplus_lending['LINE_MANAGER_1'] = ''

upline_smeplus_lending.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         591 non-null    object
 1   SALES_NAME      591 non-null    object
 2   LINE_MANAGER_1  591 non-null    object
 3   LINE_MANAGER_2  569 non-null    object
 4   LINE_MANAGER_3  569 non-null    object
 5   LINE_MANAGER_4  581 non-null    object
 6   AREA            383 non-null    object
 7   REGION          581 non-null    object
dtypes: object(8)
memory usage: 37.1+ KB

In [252]:
upline_smeplus_lending['SALES_NAME'] = upline_smeplus_lending['SALES_NAME'].fillna("")
upline_smeplus_lending['LINE_MANAGER_1'] = upline_smeplus_lending['LINE_MANAGER_1'].fillna("")
upline_smeplus_lending['LINE_MANAGER_2'] = upline_smeplus_lending['LINE_MANAGER_2'].fillna("")
upline_smeplus_lending['LINE_MANAGER_3'] = upline_smeplus_lending['LINE_MANAGER_3'].fillna("")

upline_smeplus_lending['SALES_NAME'] = np.where(upline_smeplus_lending['SALES_NAME'] == '0 - ',
                                            "",upline_smeplus_lending['SALES_NAME'])
upline_smeplus_lending['LINE_MANAGER_1'] = np.where(upline_smeplus_lending['LINE_MANAGER_1'] == '0 - ',
                                            "",upline_smeplus_lending['LINE_MANAGER_1'])
upline_smeplus_lending['LINE_MANAGER_2'] = np.where(upline_smeplus_lending['LINE_MANAGER_2'] == '0 - ',
                                            "",upline_smeplus_lending['LINE_MANAGER_2'])
upline_smeplus_lending['LINE_MANAGER_3'] = np.where(upline_smeplus_lending['LINE_MANAGER_3'] == '0 - ',
                                            "",upline_smeplus_lending['LINE_MANAGER_3'])

In [253]:
#CHECKPOINT UPLINE
print(len(upline_smeplus_1) + len(upline_smeplus_3) + len(upline_smeplus_2) == len(lending_smeplus))
print(len(upline_smeplus_lending) == len(lending_smeplus))

True
True

In [254]:
print(len(upline_smeplus_lending))
print(len(lending_smeplus))

591
591

In [255]:
upline_smeplus_lending[upline_smeplus_lending['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

Empty DataFrame
Columns: [GCIF_NO, SALES_NAME, LINE_MANAGER_1, LINE_MANAGER_2, LINE_MANAGER_3, LINE_MANAGER_4, AREA, REGION]
Index: []

In [256]:
upline_smeplus_lending.columns

Index(['GCIF_NO', 'SALES_NAME', 'LINE_MANAGER_1', 'LINE_MANAGER_2',
       'LINE_MANAGER_3', 'LINE_MANAGER_4', 'AREA', 'REGION'],
      dtype='object')

## 16. BASELINE AND UPLINE - BB

In [257]:
acc_handling_bb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   GCIF_NO   1121 non-null   object
 1   REGION    1121 non-null   object
 2   NPK AO    1111 non-null   float64
 3   AO NAME   1113 non-null   object
 4   NPK TL    1113 non-null   float64
 5   TL NAME   1118 non-null   object
 6   NPK RBBH  1121 non-null   int64
 7   RBBH      1121 non-null   object
 8   AREA      1121 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 78.9+ KB

In [258]:
acc_handling_bb.columns = ['GCIF_NO', 'REGION', 'NPK AO', 'AO NAME', 'NPK TL', 'TL NAME',
       'NPK RBBH', 'RBBH', 'AREA']
# acc_handling_bb['REGION'] = ''

acc_handling_bb = acc_handling_bb[['GCIF_NO', 'NPK AO', 'AO NAME', 'NPK TL', 
                            'TL NAME', 'NPK RBBH', 'RBBH', 'AREA', 'REGION']]

In [259]:
acc_handling_bb = acc_handling_bb.drop_duplicates()
acc_handling_bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 503 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   GCIF_NO   503 non-null    object
 1   NPK AO    494 non-null    float64
 2   AO NAME   496 non-null    object
 3   NPK TL    496 non-null    float64
 4   TL NAME   500 non-null    object
 5   NPK RBBH  503 non-null    int64
 6   RBBH      503 non-null    object
 7   AREA      503 non-null    object
 8   REGION    503 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 39.3+ KB

In [260]:
acc_handling_bb[acc_handling_bb['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

,GCIF_NO,NPK AO,AO NAME,NPK TL,TL NAME,NPK RBBH,RBBH,AREA,REGION
897,G009902099,"34,785.0",IRWAN WIMENTA,"34,785.0",IRWAN WIMENTA,38044,SUPIANTO,,SULAWESI & IBT
896,G009902099,NaN,NaN,NaN,PRATIWI PUJILESTARI SUWARDY,38044,SUPIANTO,,SULAWESI & IBT
899,G009902099,"34,785.0",IRWAN WIMENTA,"38,044.0",SUPIANTO,38044,SUPIANTO,,SULAWESI & IBT
320,G010144921,"43,271.0",BILLY EVANS,"19,367.0",LUTVIE AGUNG PURNOMO,27047,YENNY RAHARJO,,"JATIM, BALI & NUSRA"
321,G010144921,NaN,NaN,NaN,NaN,27047,YENNY RAHARJO,,"JATIM, BALI & NUSRA"
394,G206141574,NaN,NaN,NaN,AGUSTIN PRISTIAWATI,27047,YENNY RAHARJO,,"JATIM, BALI & NUSRA"
147,G206141574,"41,267.0",DEVINE KURNIA,"41,825.0",CHARLES AGUSTINUS RUNTU,42102,BENYAMIN HH,,JAKARTA 2
149,G206141574,NaN,OKTAVIANA SAMOSIR,NaN,WENDA PRISCILLA UTARYO,42102,BENYAMIN HH,,JAKARTA 2
787,G305381782,NaN,NaN,NaN,MATHILDA RAHMA BUDI SETIANI,35036,ANITA,,JAWA TENGAH
788,G305381782,"41,301.0",FERRY AKBAR,"35,036.0",ANITA,35036,ANITA,,JAWA TENGAH
858,G402244271,"11,380.0",SAPTA SAUT TULUS HUTABARAT,"41,825.0",CHARLES AGUSTINUS RUNTU,38044,SUPIANTO,,KALIMANTAN
857,G402244271,"34,934.0",ANDHI PURNAMA GIDEON CHANDRA,"14,133.0",ANTON PURWANTO,38044,SUPIANTO,,KALIMANTAN
938,G507687929,"27,383.0",YUDI ERIANTO,"33,142.0",MELINDA AGUSTINE,38018,CATHARINE,,SUMATERA SELATAN
937,G507687929,"33,142.0",MELINDA AGUSTINE,"27,383.0",YUDI ERIANTO,38018,CATHARINE,,SUMATERA SELATAN
936,G507687929,"27,383.0",YUDI ERIANTO,"40,390.0",ANDI,38018,CATHARINE,,SUMATERA SELATAN
229,G509119475,"41,301.0",FERRY AKBAR,"41,825.0",CHARLES AGUSTINUS RUNTU,37795,JANE DERMAWAN,,JAKARTA 2
174,G509119475,NaN,NaN,"20,977.0",NURUL MARDIANA,42102,BENYAMIN HH,,JAKARTA 2
941,G509265765,"27,383.0",YUDI ERIANTO,"33,142.0",MELINDA AGUSTINE,38018,CATHARINE,,SUMATERA SELATAN
940,G509265765,"27,383.0",YUDI ERIANTO,"42,713.0",IRWAN HAMID,38018,CATHARINE,,SUMATERA SELATAN
299,G600841506,"40,654.0",BARI IBNU IBRAHIM,"37,794.0",FENDY ASEAN,37794,FENDY ASEAN,,JAKARTA 3
62,G600841506,"40,654.0",BARI IBNU IBRAHIM,"37,794.0",FENDY ASEAN,37794,FENDY ASEAN,,JAKARTA 1
913,G701524399,NaN,NaN,NaN,NaN,38044,SUPIANTO,,SULAWESI & IBT
914,G701524399,"34,785.0",IRWAN WIMENTA,"38,044.0",SUPIANTO,38044,SUPIANTO,,SULAWESI & IBT

In [261]:
baseline_rm_bb = acc_handling_bb[~acc_handling_bb['NPK AO'].isna()]
baseline_rm_bb = baseline_rm_bb.merge(users[['NPK','NAMA','EMAIL_KARYAWAN']], left_on = 'NPK AO', right_on = 'NPK', how='left')
baseline_rm_bb['JABATAN'] = 'RELATIONSHIP MANAGER'
#CHECKPOINT - BASELINE RM BB for Email NA -> new karyawan, add to PDT NR Users
baseline_rm_bb[baseline_rm_bb['EMAIL_KARYAWAN'].isna()][['NPK AO','AO NAME']].drop_duplicates() 
# baseline_rm_bb = baseline_rm_bb.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'])

      NPK AO                       AO NAME
345 34,934.0  ANDHI PURNAMA GIDEON CHANDRA

In [262]:
baseline_rm_bb = baseline_rm_bb[['GCIF_NO','AREA','REGION','NPK', 'NAMA', 'JABATAN','EMAIL_KARYAWAN']]

In [263]:
baseline_tl_bb = acc_handling_bb[~acc_handling_bb['NPK TL'].isna()].drop(columns = {'NPK AO', 'AO NAME','NPK RBBH','RBBH'})
baseline_tl_bb = baseline_tl_bb.merge(users[['NPK','NAMA','EMAIL_KARYAWAN']], left_on = 'NPK TL', right_on = 'NPK', how='left')
baseline_tl_bb['JABATAN'] = 'TEAM LEADER'
#CHECKPOINT - BASELINE TL BB
baseline_tl_bb[baseline_tl_bb['EMAIL_KARYAWAN'].isna()][['NPK TL','TL NAME']].drop_duplicates() 
# baseline_tl_bb = baseline_tl_bb.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'])

      NPK TL         TL NAME
77  20,977.0  NURUL MARDIANA
347 14,133.0  ANTON PURWANTO
393 40,390.0            ANDI

In [264]:
baseline_tl_bb = baseline_tl_bb[['GCIF_NO','AREA','REGION','NPK', 'NAMA', 'JABATAN', 'EMAIL_KARYAWAN']]

In [265]:
baseline_tl_bb[baseline_tl_bb['NAMA'].isna()]

        GCIF_NO AREA            REGION  NPK NAMA      JABATAN EMAIL_KARYAWAN
77   G509119475              JAKARTA 2  NaN  NaN  TEAM LEADER            NaN
347  G402244271             KALIMANTAN  NaN  NaN  TEAM LEADER            NaN
393  G507687929       SUMATERA SELATAN  NaN  NaN  TEAM LEADER            NaN
398  G509309704       SUMATERA SELATAN  NaN  NaN  TEAM LEADER            NaN

In [266]:
acc_handling_bb['NAMA RBBH'] = np.where(acc_handling_bb['RBBH'] == 'BENYAMIN HH',
                                            'BENYAMIN HENRIE HARYONO', acc_handling_bb['RBBH'])
baseline_rbbh_bb = acc_handling_bb.merge(users[['NPK','NAMA','EMAIL_KARYAWAN']], left_on = 'NPK RBBH', right_on = 'NPK',how = 'left')
baseline_rbbh_bb['JABATAN'] = 'REGIONAL BB HEAD'
baseline_rbbh_bb = baseline_rbbh_bb[['GCIF_NO','AREA','REGION','NPK', 'NAMA', 'JABATAN', 'EMAIL_KARYAWAN']]
# baseline_rbbh_bb = baseline_rbbh_bb.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'])

# baseline_rbbh_bb = baseline_rbbh_bb.rename(columns = {'NPK': 'NPK RBBH', 'NAMA': 'NAMA RBBH', 'EMAIL_KARYAWAN': 'EMAIL RBBH'})
baseline_rbbh_bb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         503 non-null    object
 1   AREA            503 non-null    object
 2   REGION          503 non-null    object
 3   NPK             503 non-null    int64
 4   NAMA            503 non-null    object
 5   JABATAN         503 non-null    object
 6   EMAIL_KARYAWAN  503 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.6+ KB

In [267]:
baseline_admin_bb = acc_handling_bb[['GCIF_NO','AREA','REGION']].merge(email_map_admin,on='REGION',how='left')
baseline_rd_bb = acc_handling_bb[['GCIF_NO','AREA','REGION']].merge(users[users['JABATAN']=='REGIONAL DIRECTOR'][['REGION', 'NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],on='REGION',how='left')
baseline_rrb_bb = acc_handling_bb[['GCIF_NO','AREA','REGION']].merge(users[users['JABATAN']=='REGIONAL RETAIL BANKING HEAD'][['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
                                 on='REGION',how='left')
baseline_rrb_bb = baseline_rrb_bb[~baseline_rrb_bb['EMAIL_KARYAWAN'].isna()] #Ga semua Region punya RRBH
#baseline_tb_bb = acc_handling_bb[['GCIF_NO','AREA','REGION']].merge(tb[['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
#                                 on='REGION',how='left')

In [268]:
baseline_rm_bb['EMAIL_KARYAWAN'] = baseline_rm_bb['EMAIL_KARYAWAN'].astype('str')
baseline_tl_bb['EMAIL_KARYAWAN'] = baseline_tl_bb['EMAIL_KARYAWAN'].astype('str')
baseline_rbbh_bb['EMAIL_KARYAWAN'] = baseline_rbbh_bb['EMAIL_KARYAWAN'].astype('str')
baseline_admin_bb['EMAIL_KARYAWAN'] = baseline_admin_bb['EMAIL_KARYAWAN'].astype('str')
baseline_rd_bb['EMAIL_KARYAWAN'] = baseline_rd_bb['EMAIL_KARYAWAN'].astype('str')
baseline_rrb_bb['EMAIL_KARYAWAN'] = baseline_rrb_bb['EMAIL_KARYAWAN'].astype('str')
#baseline_tb_bb['EMAIL_KARYAWAN'] = baseline_tb_bb['EMAIL_KARYAWAN'].astype('str')

baseline_bb_lending = pd.concat([baseline_rm_bb,baseline_tl_bb, baseline_rbbh_bb, baseline_admin_bb,baseline_rd_bb,baseline_rrb_bb 
                                 #,baseline_tb_bb
                                ],axis=0)
baseline_bb_lending = baseline_bb_lending.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'])

baseline_bb_lending.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4508 entries, 0 to 502
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         4508 non-null   object
 1   AREA            4508 non-null   object
 2   REGION          4508 non-null   object
 3   NPK             4504 non-null   float64
 4   NAMA            4504 non-null   object
 5   JABATAN         4508 non-null   object
 6   EMAIL_KARYAWAN  4508 non-null   object
dtypes: float64(1), object(6)
memory usage: 281.8+ KB

In [269]:
baseline_bb_lending[baseline_bb_lending['NAMA'].isna()]

,GCIF_NO,AREA,REGION,NPK,NAMA,JABATAN,EMAIL_KARYAWAN
345,G402244271,,KALIMANTAN,NaN,NaN,RELATIONSHIP MANAGER,nan
77,G509119475,,JAKARTA 2,NaN,NaN,TEAM LEADER,nan
393,G507687929,,SUMATERA SELATAN,NaN,NaN,TEAM LEADER,nan
398,G509309704,,SUMATERA SELATAN,NaN,NaN,TEAM LEADER,nan

In [270]:
upline_bb_lending = baseline_bb_lending[['GCIF_NO','AREA','REGION']].drop_duplicates()

upline_bb_lending = upline_bb_lending.merge(baseline_rm_bb[['GCIF_NO','NPK','NAMA']], on = 'GCIF_NO', how = 'left')
upline_bb_lending['NPK'] = upline_bb_lending['NPK'].fillna(0)
upline_bb_lending['SALES_NAME'] = upline_bb_lending['NPK'].astype('int64').astype(str) + ' - ' + upline_bb_lending['NAMA']
upline_bb_lending = upline_bb_lending[['GCIF_NO','AREA','REGION','SALES_NAME']]

upline_bb_lending['LINE_MANAGER_1'] = ''

upline_bb_lending = upline_bb_lending.merge(baseline_tl_bb[['GCIF_NO','NPK','NAMA']], on = 'GCIF_NO', how = 'left')
upline_bb_lending['NPK'] = upline_bb_lending['NPK'].fillna(0)
upline_bb_lending['LINE_MANAGER_2'] = upline_bb_lending['NPK'].astype('int64').astype(str) + ' - ' + upline_bb_lending['NAMA']
upline_bb_lending = upline_bb_lending[['GCIF_NO','AREA','REGION','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2']]

upline_bb_lending = upline_bb_lending.merge(baseline_rbbh_bb[['GCIF_NO','NPK','NAMA']], on = 'GCIF_NO', how = 'left')
upline_bb_lending['NPK'] = upline_bb_lending['NPK'].fillna(0)
upline_bb_lending['LINE_MANAGER_3'] = upline_bb_lending['NPK'].astype('int64').astype(str) + ' - ' + upline_bb_lending['NAMA']
upline_bb_lending = upline_bb_lending[['GCIF_NO','AREA','REGION','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3']]

upline_bb_lending = upline_bb_lending.merge(baseline_rd_bb[['GCIF_NO','NPK','NAMA']], on = 'GCIF_NO', how = 'left')
upline_bb_lending['NPK'] = upline_bb_lending['NPK'].fillna(0)
upline_bb_lending['LINE_MANAGER_4'] = upline_bb_lending['NPK'].astype('int64').astype(str) + ' - ' + upline_bb_lending['NAMA']
upline_bb_lending = upline_bb_lending[['GCIF_NO','AREA','REGION','SALES_NAME','LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']]

upline_bb_lending = upline_bb_lending.drop_duplicates()
upline_bb_lending.info()

<class 'pandas.core.frame.DataFrame'>
Index: 513 entries, 0 to 684
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GCIF_NO         513 non-null    object
 1   AREA            513 non-null    object
 2   REGION          513 non-null    object
 3   SALES_NAME      509 non-null    object
 4   LINE_MANAGER_1  513 non-null    object
 5   LINE_MANAGER_2  505 non-null    object
 6   LINE_MANAGER_3  513 non-null    object
 7   LINE_MANAGER_4  513 non-null    object
dtypes: object(8)
memory usage: 36.1+ KB

In [271]:
#CHECKPOINT BB
upline_bb_lending[upline_bb_lending['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

,GCIF_NO,AREA,REGION,SALES_NAME,LINE_MANAGER_1,LINE_MANAGER_2,LINE_MANAGER_3,LINE_MANAGER_4
415,G009902099,,SULAWESI & IBT,34785 - IRWAN WIMENTA,,34785 - IRWAN WIMENTA,38044 - SUPIANTO,37418 - HASVAN MURPHY
424,G009902099,,SULAWESI & IBT,34785 - IRWAN WIMENTA,,38044 - SUPIANTO,38044 - SUPIANTO,37418 - HASVAN MURPHY
679,G206141574,,"JATIM, BALI & NUSRA",41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,27047 - YENNY RAHARJO,41184 - OSBIE OSMAN
673,G206141574,,"JATIM, BALI & NUSRA",41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,42102 - ANDIKA PERDANA PUTRA,41184 - OSBIE OSMAN
87,G206141574,,JAKARTA 2,41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,27047 - YENNY RAHARJO,34571 - INDRAJANI HARSONO
675,G206141574,,"JATIM, BALI & NUSRA",41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,42102 - ANDIKA PERDANA PUTRA,34571 - INDRAJANI HARSONO
681,G206141574,,"JATIM, BALI & NUSRA",41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,27047 - YENNY RAHARJO,34571 - INDRAJANI HARSONO
85,G206141574,,JAKARTA 2,41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,27047 - YENNY RAHARJO,41184 - OSBIE OSMAN
79,G206141574,,JAKARTA 2,41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,42102 - ANDIKA PERDANA PUTRA,41184 - OSBIE OSMAN
81,G206141574,,JAKARTA 2,41267 - DEVINE KURNIA,,41825 - CHARLES AGUSTINUS RUNTU,42102 - ANDIKA PERDANA PUTRA,34571 - INDRAJANI HARSONO
392,G402244271,,KALIMANTAN,11380 - SAPTA SAUT TULUS HUTABARAT,,41825 - CHARLES AGUSTINUS RUNTU,38044 - SUPIANTO,35486 - YULLI SUMARGO
388,G402244271,,KALIMANTAN,11380 - SAPTA SAUT TULUS HUTABARAT,,NaN,38044 - SUPIANTO,35486 - YULLI SUMARGO
380,G402244271,,KALIMANTAN,NaN,,NaN,38044 - SUPIANTO,35486 - YULLI SUMARGO
384,G402244271,,KALIMANTAN,NaN,,41825 - CHARLES AGUSTINUS RUNTU,38044 - SUPIANTO,35486 - YULLI SUMARGO
477,G507687929,,SUMATERA SELATAN,27383 - YUDI ERIANTO,,NaN,38018 - CATHARINE,17239 - SUTARDI
486,G507687929,,SUMATERA SELATAN,27383 - YUDI ERIANTO,,27383 - YUDI ERIANTO,38018 - CATHARINE,17239 - SUTARDI
495,G507687929,,SUMATERA SELATAN,27383 - YUDI ERIANTO,,33142 - MELINDA AGUSTINE,38018 - CATHARINE,17239 - SUTARDI
504,G507687929,,SUMATERA SELATAN,33142 - MELINDA AGUSTINE,,NaN,38018 - CATHARINE,17239 - SUTARDI
513,G507687929,,SUMATERA SELATAN,33142 - MELINDA AGUSTINE,,27383 - YUDI ERIANTO,38018 - CATHARINE,17239 - SUTARDI
522,G507687929,,SUMATERA SELATAN,33142 - MELINDA AGUSTINE,,33142 - MELINDA AGUSTINE,38018 - CATHARINE,17239 - SUTARDI
139,G509119475,,JAKARTA 2,41301 - FERRY AKBAR,,41825 - CHARLES AGUSTINUS RUNTU,37795 - JANE DERMAWAN,41184 - OSBIE OSMAN
137,G509119475,,JAKARTA 2,41301 - FERRY AKBAR,,41825 - CHARLES AGUSTINUS RUNTU,42102 - ANDIKA PERDANA PUTRA,41184 - OSBIE OSMAN
135,G509119475,,JAKARTA 2,41301 - FERRY AKBAR,,NaN,37795 - JANE DERMAWAN,41184 - OSBIE OSMAN
133,G509119475,,JAKARTA 2,41301 - FERRY AKBAR,,NaN,42102 - ANDIKA PERDANA PUTRA,41184 - OSBIE OSMAN
558,G509265765,,SUMATERA SELATAN,27383 - YUDI ERIANTO,,42713 - IRWAN HAMID,38018 - CATHARINE,17239 - SUTARDI
562,G509265765,,SUMATERA SELATAN,27383 - YUDI ERIANTO,,33142 - MELINDA AGUSTINE,38018 - CATHARINE,17239 - SUTARDI
26,G600841506,,JAKARTA 1,40654 - BARI IBNU IBRAHIM,,37794 - FENDY ASEAN,37794 - FENDY ASEAN,39717 - WAN JUSLIAN JOHAN
27,G600841506,,JAKARTA 1,40654 - BARI IBNU IBRAHIM,,37794 - FENDY ASEAN,37794 - FENDY ASEAN,9591 - RASUANIR
683,G600841506,,JAKARTA 3,40654 - BARI IBNU IBRAHIM,,37794 - FENDY ASEAN,37794 - FENDY ASEAN,39717 - WAN JUSLIAN JOHAN
684,G600841506,,JAKARTA 3,40654 - BARI IBNU IBRAHIM,,37794 - FENDY ASEAN,37794 - FENDY ASEAN,9591 - RASUANIR

# FUNDING

[back](#back)

In [272]:
current_d_funding = current_d_lending #CHANGE
current_d2_funding = current_d2_lending #CHANGE

In [273]:
baseline_rsme_funding = baseline_funding[baseline_funding['LOB'] == 'SME']
baseline_smeplus_funding = baseline_funding[baseline_funding['LOB'] == 'SME+']
baseline_bb_funding = baseline_funding[baseline_funding['LOB'] == 'BB']

In [274]:
upline_rsme_funding = upline_funding[upline_funding['LOB'] == 'SME']
upline_smeplus_funding = upline_funding[upline_funding['LOB'] == 'SME+']
upline_bb_funding = upline_funding[upline_funding['LOB'] == 'BB']

# COMBINE AND EXPORT

[back](#back)

## 1. RSME

### 1.1 Adjust Columns between Baseline and Upline

In [275]:
#BASELINE ADJUSTMENT
baseline_rsme_lending['BASE_DT'] = current_d_lending
baseline_rsme_lending['Date'] = pd.to_datetime(current_d2_lending)
baseline_rsme_lending['L_F'] = 'LENDING'
baseline_rsme_lending['BRANCH CODE'] = np.nan
baseline_rsme_lending['BRANCH'] = np.nan
baseline_rsme_lending['CIF_NO'] = np.nan
baseline_rsme_lending['LOB'] = 'SME'
baseline_rsme_lending = baseline_rsme_lending[['BASE_DT', 'Date','GCIF_NO', 'CIF_NO','LOB','BRANCH CODE','BRANCH',
                                                'AREA', 'REGION','NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN','L_F']]

baseline_rsme_funding['BASE_DT'] = current_d_funding
baseline_rsme_funding['Date'] = pd.to_datetime(current_d2_funding)
baseline_rsme_funding = baseline_rsme_funding[['BASE_DT', 'Date', 'GCIF_NO', 'CIF_NO','LOB','BRANCH CODE', 'BRANCH', 
                                               'AREA', 'REGION', 'NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN', 'L_F']]

#CHECKPOINT
baseline_rsme_lending.columns == baseline_rsme_funding.columns

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2377823919.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_rsme_funding['BASE_DT'] = current_d_funding
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\2377823919.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_rsme_funding['Date'] = pd.to_datetime(current_d2_funding)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [276]:
#UPLINE ADJUSTMENT
upline_rsme_lending['BASE_DT'] = current_d_lending
upline_rsme_lending['Date'] = pd.to_datetime(current_d2_lending)
upline_rsme_lending['L_F'] = 'LENDING'
upline_rsme_lending['LOB'] = 'SME'
upline_rsme_lending['BRANCH CODE'] = np.nan
upline_rsme_lending['BRANCH'] = np.nan
upline_rsme_lending = upline_rsme_lending[['BASE_DT', 'Date', 'GCIF_NO', 'SALES_NAME', 
                                           'LINE_MANAGER_1', 'LINE_MANAGER_2',
                                           'LINE_MANAGER_3', 'LINE_MANAGER_4',
                                           'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F']]


upline_rsme_funding['BASE_DT'] = current_d_funding
upline_rsme_funding['Date'] = pd.to_datetime(current_d2_funding)
upline_rsme_funding['BRANCH CODE'] = np.nan
# upline_rsme_funding['LINE_MANAGER_3'] = ''
upline_rsme_funding = upline_rsme_funding[['BASE_DT', 'Date', 'GCIF_NO', 'SALES_NAME',
                                           'LINE_MANAGER_1','LINE_MANAGER_2', 
                                           'LINE_MANAGER_3', 'LINE_MANAGER_4',
                                           'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F']]

#CHECKPOINT
baseline_rsme_lending.columns == baseline_rsme_funding.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [277]:
#UPLINE ADJUSTMENT
#upline_rsme_funding = upline_rsme_funding.copy()

#upline_rsme_funding['BASE_DT'] = current_d_funding
#upline_rsme_funding['Date'] = pd.to_datetime(current_d2_funding)
#upline_rsme_funding['LOB'] = 'SME+'
#upline_rsme_funding['L_F'] = 'FUNDING'
#upline_rsme_funding['BRANCH CODE'] = np.nan
#upline_rsme_funding['BRANCH'] = np.nan

#upline_rsme_funding = upline_rsme_funding[[
#    'BASE_DT', 'Date', 'GCIF_NO', 'SALES_NAME',
#    'LINE_MANAGER_1','LINE_MANAGER_2', 
#'LINE_MANAGER_3', 'LINE_MANAGER_4',
#'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F'
#]]

#CHECKPOINT
#upline_rsme_lending.columns == upline_rsme_funding.columns

In [278]:
#baseline_rsme_funding = baseline_rsme_funding.reindex(columns=BASELINE_COLS)
#upline_rsme_funding   = upline_rsme_funding.reindex(columns=UPLINE_COLS)

In [279]:
list(baseline_rsme_lending.columns) == list(baseline_rsme_funding.columns)
list(upline_rsme_lending.columns) == list(upline_rsme_funding.columns)

True

### 1.2 Combine into Final PDT Mapping

In [280]:
#CHECKPOINT: should be the same as jumlah cust di BASE PROD HOLD
gcif_funding_rsme = baseline_rsme_funding[['GCIF_NO','REGION']].drop_duplicates()
len(gcif_funding_rsme)

21942

In [281]:
# #CHECKING RRB DAN CASA SPEC MAPPING
# baseline_rrb_rsme = gcif_funding_rsme.merge(rrb[['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
#                                  on='REGION',how='left')
# baseline_rrb_rsme = baseline_rrb_rsme[~baseline_rrb_rsme['NPK'].isna()]
# baseline_rrb_rsme.info()

# baseline_casa_rsme = gcif_funding_rsme.merge(casa_spec[['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
#                                  on='REGION',how='left')
# baseline_casa_rsme = baseline_casa_rsme[~baseline_casa_rsme['NPK'].isna()]
# baseline_casa_rsme.info()

# baseline_add_rsme = baseline_casa_rsme.append(baseline_rrb_rsme)
# baseline_add_rsme['BASE_DT'] = current_d_funding
# baseline_add_rsme['Date'] = pd.to_datetime(current_d2_funding)
# baseline_add_rsme['BRANCH CODE'] = ''
# baseline_add_rsme['BRANCH'] = ''
# baseline_add_rsme['AREA'] = ''
# baseline_add_rsme['L_F'] = 'FUNDING'

# baseline_add_rsme = baseline_add_rsme[['BASE_DT', 'Date', 'GCIF_NO', 'BRANCH CODE', 'BRANCH', 
#                                                'AREA', 'REGION', 'NPK', 'NAMA', 'JABATAN', 'EMAIL_KARYAWAN', 'L_F']]

# baseline_rsme_funding = baseline_rsme_funding.append(baseline_add_rsme)

In [282]:
#ALL RSME (FOR PDT)
baseline_rsme_pdt = pd.concat([baseline_rsme_lending,baseline_rsme_funding],axis=0)
upline_rsme_pdt = pd.concat([upline_rsme_lending,upline_rsme_funding],axis=0)

In [283]:
#In PDT Dashboards, only show LENDING UPLINE
upline_rsme_pdt_final = upline_rsme_pdt.sort_values('L_F')
upline_rsme_pdt_final = upline_rsme_pdt_final.drop_duplicates('GCIF_NO',keep='last')

#For Regional Directors (can see both Funding and Lending GCIFS), take the FUNDING rows
# (For more complete information of BRANCH))
baseline_rsme_pdt_final = baseline_rsme_pdt.sort_values('L_F')
baseline_rsme_pdt_final = baseline_rsme_pdt_final.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'],keep='first')

In [284]:
#BASELINE TB
baseline_rsme_tb = baseline_rsme_pdt_final.sort_values('L_F')
baseline_rsme_tb = baseline_rsme_tb.drop_duplicates('GCIF_NO',keep='last')
baseline_rsme_tb = baseline_rsme_tb[['GCIF_NO','AREA','REGION']]

#baseline_rsme_tb = baseline_rsme_tb.merge(tb, on = 'REGION', how = 'left')
#baseline_rsme_tb['BASE_DT'] = current_d_lending
#baseline_rsme_tb['Date'] = pd.to_datetime(current_d2_lending)
#baseline_rsme_tb['L_F'] = 'LENDING'
#baseline_rsme_tb['BRANCH CODE'] = np.nan
#baseline_rsme_tb['BRANCH'] = np.nan
#baseline_rsme_tb['CIF_NO'] = np.nan
#baseline_rsme_tb['LOB'] = 'SME'
#baseline_rsme_tb = baseline_rsme_tb[['BASE_DT', 'Date','GCIF_NO', 'CIF_NO','LOB','BRANCH CODE','BRANCH',
#                                                'AREA', 'REGION','NPK', 'NAMA', 
#                                               'JABATAN', 'EMAIL_KARYAWAN','L_F']]

baseline_rsme_tb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16807 entries, 5567 to 0
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  16807 non-null  object
 1   AREA     16807 non-null  object
 2   REGION   6908 non-null   object
dtypes: object(3)
memory usage: 525.2+ KB

In [285]:
#ADD TB USERS INTO PDT BASELINE
#baseline_rsme_pdt_final = pd.concat([baseline_rsme_pdt_final,baseline_rsme_tb],axis=0)

In [286]:
# print(baseline_rsme_pdt_final['NPK'].dtypes)
# print(baseline_rsme_lending['NPK'].dtypes)
# print(baseline_rsme_funding['NPK'].dtypes)

# baseline_rsme_lending['NPK'] = baseline_rsme_lending['NPK'].astype('int64')
# baseline_rsme_funding['NPK'] = baseline_rsme_funding['NPK'].astype('int64')

In [287]:
#PENDING: kenapa jumlah GCIF ga sama dgn Cust List? -> ada nasabah lending yang belum masuk cust list bulan lalu
upline_rsme_pdt_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6127 entries, 0 to 6494
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BASE_DT         6127 non-null   int64
 1   Date            6127 non-null   datetime64[ns]
 2   GCIF_NO         6127 non-null   object
 3   SALES_NAME      6127 non-null   object
 4   LINE_MANAGER_1  6127 non-null   object
 5   LINE_MANAGER_2  6127 non-null   object
 6   LINE_MANAGER_3  6127 non-null   object
 7   LINE_MANAGER_4  5696 non-null   object
 8   LOB             6127 non-null   object
 9   BRANCH CODE     0 non-null      float64
 10  BRANCH          0 non-null      object
 11  AREA            6127 non-null   object
 12  REGION          5696 non-null   object
 13  L_F             6127 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 718.0+ KB

In [288]:
#FINAL CHECKPOINT: 390K ROWS
baseline_rsme_pdt_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 170205 entries, 32759 to 0
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   BASE_DT         170205 non-null  int64
 1   Date            170205 non-null  datetime64[ns]
 2   GCIF_NO         170205 non-null  object
 3   CIF_NO          111018 non-null  float64
 4   LOB             170205 non-null  object
 5   BRANCH CODE     111018 non-null  float64
 6   BRANCH          111018 non-null  object
 7   AREA            137798 non-null  object
 8   REGION          135502 non-null  object
 9   NPK             170192 non-null  float64
 10  NAMA            169777 non-null  object
 11  JABATAN         170192 non-null  object
 12  EMAIL_KARYAWAN  168624 non-null  object
 13  L_F             170205 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(9)
memory usage: 19.5+ MB

In [289]:
#FINAL CHECKPOINT: 26k ROWS
upline_rsme_pdt_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6127 entries, 0 to 6494
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BASE_DT         6127 non-null   int64
 1   Date            6127 non-null   datetime64[ns]
 2   GCIF_NO         6127 non-null   object
 3   SALES_NAME      6127 non-null   object
 4   LINE_MANAGER_1  6127 non-null   object
 5   LINE_MANAGER_2  6127 non-null   object
 6   LINE_MANAGER_3  6127 non-null   object
 7   LINE_MANAGER_4  5696 non-null   object
 8   LOB             6127 non-null   object
 9   BRANCH CODE     0 non-null      float64
 10  BRANCH          0 non-null      object
 11  AREA            6127 non-null   object
 12  REGION          5696 non-null   object
 13  L_F             6127 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 718.0+ KB

In [290]:
baseline_rsme_lending[['NAMA', 'JABATAN']] = baseline_rsme_lending[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
baseline_rsme_lending['EMAIL_KARYAWAN'] = baseline_rsme_lending['EMAIL_KARYAWAN'].str.lower()

baseline_rsme_pdt_final[['NAMA', 'JABATAN']] = baseline_rsme_pdt_final[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
baseline_rsme_pdt_final['EMAIL_KARYAWAN'] = baseline_rsme_pdt_final['EMAIL_KARYAWAN'].str.lower()

upline_rsme_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_rsme_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

upline_rsme_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_rsme_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

In [291]:
## EXPORT - RSME
##LENDING
baseline_rsme_lending.to_csv(save_rsme_baseline_lending, index=False)
# upline_rsme_lending.to_csv(r'Results\UPLINE_LENDING_rsme_240606.csv',
#                         index=False)

##FUNDING
# baseline_rsme_funding.to_csv(r'Results\BASELINE_FUNDING_rsme_240229.csv',
#                           index=False)
# upline_rsme_funding.to_csv(r'Results\UPLINE_FUNDING_rsme_240229.csv',
#                         index=False)

##ALL (PDT)
baseline_rsme_pdt_final.to_csv(save_rsme_baseline, index=False)
upline_rsme_pdt_final.to_csv(save_rsme_upline, index=False)

## 2. SME+

### 2.1 Adjust Columns between Baseline and Upline

In [292]:
#CHECKPOINT
print(len(baseline_smeplus_lending)) #8000 rows
print(len(upline_smeplus_lending)) #640 rows

5401
591

In [293]:
print(baseline_smeplus_lending.columns)
print(baseline_smeplus_funding.columns)

Index(['GCIF_NO', 'NPK', 'NAMA', 'JABATAN', 'AREA', 'REGION',
       'EMAIL_KARYAWAN'],
      dtype='object')
Index(['GCIF_NO', 'CIF_NO', 'LOB', 'BRANCH', 'AREA', 'REGION', 'NPK', 'NAMA',
       'JABATAN', 'EMAIL_KARYAWAN', 'BRANCH CODE', 'L_F'],
      dtype='object')

In [294]:
#BASELINE ADJUSTMENT
baseline_smeplus_lending['BASE_DT'] = current_d_lending
baseline_smeplus_lending['Date'] = pd.to_datetime(current_d2_lending)
baseline_smeplus_lending['L_F'] = 'LENDING'
baseline_smeplus_lending['BRANCH CODE'] = np.nan
baseline_smeplus_lending['BRANCH'] = np.nan
baseline_smeplus_lending['CIF_NO'] = np.nan
baseline_smeplus_lending['LOB'] = 'SME+'
baseline_smeplus_lending = baseline_smeplus_lending[['BASE_DT', 'Date','GCIF_NO', 'CIF_NO','LOB','BRANCH CODE','BRANCH',
                                                'AREA', 'REGION','NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN','L_F']]

baseline_smeplus_funding['BASE_DT'] = current_d_funding
baseline_smeplus_funding['Date'] = pd.to_datetime(current_d2_funding)
baseline_smeplus_funding = baseline_smeplus_funding[['BASE_DT', 'Date', 'GCIF_NO', 'CIF_NO','LOB','BRANCH CODE', 'BRANCH', 
                                               'AREA', 'REGION', 'NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN', 'L_F']]

#CHECKPOINT
baseline_smeplus_lending.columns == baseline_smeplus_funding.columns

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3672913194.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_smeplus_funding['BASE_DT'] = current_d_funding
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\3672913194.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_smeplus_funding['Date'] = pd.to_datetime(current_d2_funding)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [295]:
#UPLINE ADJUSTMENT
upline_smeplus_lending['BASE_DT'] = current_d_lending
upline_smeplus_lending['Date'] = pd.to_datetime(current_d2_lending)
upline_smeplus_lending['L_F'] = 'LENDING'
upline_smeplus_lending['LOB'] = 'SME+'
upline_smeplus_lending['BRANCH CODE'] = np.nan
upline_smeplus_lending['BRANCH'] = np.nan
upline_smeplus_lending = upline_smeplus_lending[['BASE_DT', 'Date', 'GCIF_NO', 'SALES_NAME', 
                                           'LINE_MANAGER_1', 'LINE_MANAGER_2',
                                           'LINE_MANAGER_3', 'LINE_MANAGER_4',
                                           'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F']]

upline_smeplus_funding['BASE_DT'] = current_d_funding
upline_smeplus_funding['Date'] = pd.to_datetime(current_d2_funding)
upline_smeplus_funding['BRANCH CODE'] = np.nan
# upline_smeplus_funding['LINE_MANAGER_3'] = ''
upline_smeplus_funding = upline_smeplus_funding[['BASE_DT', 'Date', 'GCIF_NO', 'SALES_NAME',
                                           'LINE_MANAGER_1','LINE_MANAGER_2', 
                                           'LINE_MANAGER_3', 'LINE_MANAGER_4',
                                           'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F']]

#CHECKPOINT
baseline_smeplus_lending.columns == baseline_smeplus_funding.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

### 2.2 Combine into Final PDT Mapping

In [296]:
len(baseline_smeplus_funding)

9958

In [297]:
#CHECKPOINT: should be the same as jumlah cust di Cust List SME+

gcif_funding_smeplus = baseline_smeplus_funding[['GCIF_NO','REGION']].drop_duplicates()
len(gcif_funding_smeplus)

1962

In [298]:
# baseline_rrb_smeplus = gcif_funding_smeplus.merge(rrb[['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
#                                  on='REGION',how='left')
# baseline_rrb_smeplus = baseline_rrb_smeplus[~baseline_rrb_smeplus['NPK'].isna()]

# baseline_rrb_smeplus.info()

# baseline_casa_smeplus = gcif_funding_smeplus.merge(casa_spec[['REGION','NPK','NAMA','JABATAN','EMAIL_KARYAWAN']],
#                                  on='REGION',how='left')
# baseline_casa_smeplus = baseline_casa_smeplus[~baseline_casa_smeplus['NPK'].isna()]
# baseline_casa_smeplus.info()

# baseline_add_smeplus = baseline_casa_smeplus.append(baseline_rrb_smeplus)
# baseline_add_smeplus['BASE_DT'] = current_d_funding
# baseline_add_smeplus['Date'] = pd.to_datetime(current_d2_funding)
# baseline_add_smeplus['BRANCH CODE'] = ''
# baseline_add_smeplus['BRANCH'] = ''
# baseline_add_smeplus['AREA'] = ''
# baseline_add_smeplus['L_F'] = 'FUNDING'

# baseline_add_smeplus = baseline_add_smeplus[['BASE_DT', 'Date', 'GCIF_NO', 'BRANCH CODE', 'BRANCH', 
#                                                'AREA', 'REGION', 'NPK', 'NAMA', 'JABATAN', 'EMAIL_KARYAWAN', 'L_F']]
# baseline_smeplus_funding = baseline_smeplus_funding.append(baseline_add_smeplus)

In [299]:
baseline_smeplus_funding[baseline_smeplus_funding['NPK'].isna()]

Empty DataFrame
Columns: [BASE_DT, Date, GCIF_NO, CIF_NO, LOB, BRANCH CODE, BRANCH, AREA, REGION, NPK, NAMA, JABATAN, EMAIL_KARYAWAN, L_F]
Index: []

In [300]:
#ALL SME+ (FOR PDT)
baseline_smeplus_pdt = pd.concat([baseline_smeplus_lending,baseline_smeplus_funding],axis=0)
upline_smeplus_pdt = pd.concat([upline_smeplus_lending,upline_smeplus_funding],axis=0)

In [301]:
#In PDT Dashboards, only show LENDING UPLINE
upline_smeplus_pdt_final = upline_smeplus_pdt.sort_values('L_F')
upline_smeplus_pdt_final = upline_smeplus_pdt_final.drop_duplicates('GCIF_NO',keep='last')

#For Regional Directors (can see both Funding and Lending GCIFS), take the FUNDING rows
# (For more complete information of BRANCH))
baseline_smeplus_pdt_final = baseline_smeplus_pdt.sort_values('L_F')
baseline_smeplus_pdt_final = baseline_smeplus_pdt_final.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'],keep='first')

In [302]:
#BASELINE TB
baseline_smeplus_tb = baseline_smeplus_pdt_final.sort_values('L_F')
baseline_smeplus_tb = baseline_smeplus_tb.drop_duplicates('GCIF_NO',keep='last')
baseline_smeplus_tb = baseline_smeplus_tb[['GCIF_NO','AREA','REGION']]

#baseline_smeplus_tb = baseline_smeplus_tb.merge(tb, on = 'REGION', how = 'left')
#baseline_smeplus_tb['BASE_DT'] = current_d_lending
#baseline_smeplus_tb['Date'] = pd.to_datetime(current_d2_lending)
#baseline_smeplus_tb['L_F'] = 'LENDING'
#baseline_smeplus_tb['BRANCH CODE'] = np.nan
#baseline_smeplus_tb['BRANCH'] = np.nan
#baseline_smeplus_tb['CIF_NO'] = np.nan
#baseline_smeplus_tb['LOB'] = 'SME+'
#baseline_smeplus_tb = baseline_smeplus_tb[['BASE_DT', 'Date','GCIF_NO', 'CIF_NO','LOB','BRANCH CODE','BRANCH',
#                                                'AREA', 'REGION','NPK', 'NAMA', 
#                                               'JABATAN', 'EMAIL_KARYAWAN','L_F']]

baseline_smeplus_tb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1547 entries, 6204 to 0
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GCIF_NO  1547 non-null   object
 1   AREA     1338 non-null   object
 2   REGION   696 non-null    object
dtypes: object(3)
memory usage: 48.3+ KB

In [303]:
#ADD TB USERS INTO PDT BASELINE
baseline_smeplus_pdt_final = pd.concat([baseline_smeplus_pdt_final,baseline_smeplus_tb],axis=0)

In [304]:
#PENDING: kenapa jumlah GCIF ga sama dgn Cust List? -> ada nasabah lending yang belum masuk cust list bulan lalu
#FINAL CHECKPOINT: 1900 ROWS
upline_smeplus_pdt_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BASE_DT         591 non-null    int64
 1   Date            591 non-null    datetime64[ns]
 2   GCIF_NO         591 non-null    object
 3   SALES_NAME      591 non-null    object
 4   LINE_MANAGER_1  591 non-null    object
 5   LINE_MANAGER_2  591 non-null    object
 6   LINE_MANAGER_3  591 non-null    object
 7   LINE_MANAGER_4  581 non-null    object
 8   LOB             591 non-null    object
 9   BRANCH CODE     0 non-null      float64
 10  BRANCH          0 non-null      object
 11  AREA            383 non-null    object
 12  REGION          581 non-null    object
 13  L_F             591 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 69.3+ KB

In [305]:
#FINAL CHECKPOINT: 28.8k ROWS
baseline_smeplus_pdt_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16712 entries, 33944 to 0
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BASE_DT         15165 non-null  float64
 1   Date            15165 non-null  datetime64[ns]
 2   GCIF_NO         16712 non-null  object
 3   CIF_NO          9933 non-null   float64
 4   LOB             15165 non-null  object
 5   BRANCH CODE     9933 non-null   float64
 6   BRANCH          9933 non-null   object
 7   AREA            12524 non-null  object
 8   REGION          12768 non-null  object
 9   NPK             15155 non-null  float64
 10  NAMA            15155 non-null  object
 11  JABATAN         15155 non-null  object
 12  EMAIL_KARYAWAN  15037 non-null  object
 13  L_F             15165 non-null  object
dtypes: datetime64[ns](1), float64(4), object(9)
memory usage: 1.9+ MB

In [306]:
baseline_smeplus_pdt_final = baseline_smeplus_pdt_final[~baseline_smeplus_pdt_final['NPK'].isna()]

In [307]:
upline_smeplus_pdt_final[upline_smeplus_pdt_final['GCIF_NO'].duplicated(keep=False)].sort_values('GCIF_NO')

Empty DataFrame
Columns: [BASE_DT, Date, GCIF_NO, SALES_NAME, LINE_MANAGER_1, LINE_MANAGER_2, LINE_MANAGER_3, LINE_MANAGER_4, LOB, BRANCH CODE, BRANCH, AREA, REGION, L_F]
Index: []

In [308]:
baseline_smeplus_lending[['NAMA', 'JABATAN']] = baseline_smeplus_lending[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
baseline_smeplus_lending['EMAIL_KARYAWAN'] = baseline_smeplus_lending['EMAIL_KARYAWAN'].str.lower()

baseline_smeplus_pdt_final[['NAMA', 'JABATAN']] = baseline_smeplus_pdt_final[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
baseline_smeplus_pdt_final['EMAIL_KARYAWAN'] = baseline_smeplus_pdt_final['EMAIL_KARYAWAN'].str.lower()

upline_smeplus_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_smeplus_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

upline_smeplus_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_smeplus_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

In [309]:
cl_smeplus[cl_smeplus['GCIF_NO']=='G000576256']

        GCIF_NO  NPK_MAINT  AREA      REGION  NPK_REFF SOURCE
707  G000576256      44183  None  JAWA BARAT     39913    CRS

In [310]:
baseline_smeplus_pdt_final[baseline_smeplus_pdt_final[['GCIF_NO','NPK']].duplicated(keep=False)].sort_values('GCIF_NO')

,BASE_DT,Date,GCIF_NO,CIF_NO,LOB,BRANCH CODE,BRANCH,AREA,REGION,NPK,NAMA,JABATAN,EMAIL_KARYAWAN,L_F
582,"20,260,326.0",2026-03-26,G106150592,NaN,SME+,NaN,NaN,NaN,JAWA BARAT,"38,694.0",MOHAMMAD ARYA PAHLEVI MAAROEF,REGIONAL RETAIL BANKING HEAD,mapmaaroef@maybank.co.id,LENDING
55387,"20,260,326.0",2026-03-26,G106150592,"9,516,899.0",SME+,0.0,KCI TASIKMALAYA,JAWA BARAT 4,NaN,"38,694.0",MOHAMMAD ARYA PAHLEVI MAAROEF,REGIONAL RETAIL BANKING HEAD,mapmaaroef@maybank.co.id,FUNDING
78,"20,260,326.0",2026-03-26,G109106575,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
49589,"20,260,326.0",2026-03-26,G109106575,"12,208,229.0",SME+,0.0,KCI JEMUR ANDAYANI,JATIM 3,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
52625,"20,260,326.0",2026-03-26,G210364162,"13,416,471.0",SME+,0.0,KCP CENTRAL PARK,ROXY,NaN,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,FUNDING
138,"20,260,326.0",2026-03-26,G210364162,NaN,SME+,NaN,NaN,NaN,JAKARTA 1,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,LENDING
57690,"20,260,326.0",2026-03-26,G210445821,"13,479,550.0",SME+,0.0,KCS CIREBON,JAWA BARAT 4,NaN,"38,694.0",MOHAMMAD ARYA PAHLEVI MAAROEF,REGIONAL RETAIL BANKING HEAD,mapmaaroef@maybank.co.id,FUNDING
139,"20,260,326.0",2026-03-26,G210445821,NaN,SME+,NaN,NaN,NaN,JAWA BARAT,"38,694.0",MOHAMMAD ARYA PAHLEVI MAAROEF,REGIONAL RETAIL BANKING HEAD,mapmaaroef@maybank.co.id,LENDING
59205,"20,260,326.0",2026-03-26,G310805056,"13,827,503.0",SME+,0.0,KCI DENPASAR,BALI NUSRA,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
217,"20,260,326.0",2026-03-26,G310805056,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
52018,"20,260,326.0",2026-03-26,G409901279,"12,953,917.0",SME+,0.0,KCP KETAPANG INDAH,JUANDA,NaN,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,FUNDING
256,"20,260,326.0",2026-03-26,G409901279,NaN,SME+,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING
54349,"20,260,326.0",2026-03-26,G503069627,"6,815,030.0",SME+,0.0,KCI SURABAYA,JATIM 1,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
280,"20,260,326.0",2026-03-26,G503069627,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
282,"20,260,326.0",2026-03-26,G504326232,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
54578,"20,260,326.0",2026-03-26,G504326232,"7,901,181.0",SME+,0.0,KCI MAYJEN SUNGKONO,JATIM 2,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
58677,"20,260,326.0",2026-03-26,G510281462,"13,329,908.0",SME+,0.0,KCI MAYJEN SUNGKONO,JATIM 2,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
321,"20,260,326.0",2026-03-26,G510281462,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
59134,"20,260,326.0",2026-03-26,G510716376,"13,738,411.0",SME+,0.0,KCP SS3,SUMMITMAS,NaN,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,FUNDING
329,"20,260,326.0",2026-03-26,G510716376,NaN,SME+,NaN,NaN,NaN,JAKARTA 1,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,LENDING
56701,"20,260,326.0",2026-03-26,G608954830,"12,079,000.0",SME+,0.0,KCI MEDAN,MEDAN BARAT,NaN,"7,026.0",ERLIN,REGIONAL RETAIL BANKING HEAD,erlin@maybank.co.id,FUNDING
348,"20,260,326.0",2026-03-26,G608954830,NaN,SME+,NaN,NaN,NaN,SUMATERA UTARA,"7,026.0",ERLIN,REGIONAL RETAIL BANKING HEAD,erlin@maybank.co.id,LENDING
354,"20,260,326.0",2026-03-26,G609401567,NaN,SME+,NaN,NaN,NaN,JAKARTA 1,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,LENDING
49764,"20,260,326.0",2026-03-26,G609401567,"11,790,117.0",SME+,0.0,KCP SS3,SUMMITMAS,NaN,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,FUNDING
52117,"20,260,326.0",2026-03-26,G609953401,"13,003,837.0",SME+,0.0,KCP KETAPANG INDAH,JUANDA,NaN,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,FUNDING
365,"20,260,326.0",2026-03-26,G609953401,NaN,SME+,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING
48385,"20,260,326.0",2026-03-26,G704268770,"7,850,890.0",SME+,0.0,KCP SUNTER PARADISE,CEMPAKA MAS,NaN,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,FUNDING
585,"20,260,326.0",2026-03-26,G704268770,NaN,SME+,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING
49590,"20,260,326.0",2026-03-26,G809103419,"12,208,594.0",SME+,0.0,KCI MALANG,JATIM 1,NaN,"37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,FUNDING
587,"20,260,326.0",2026-03-26,G809103419,NaN,SME+,NaN,NaN,NaN,"JATIM, BALI & NUSRA","37,282.0",NANCY ESTER MARIA,REGIONAL RETAIL BANKING HEAD,nancy@maybank.co.id,LENDING
580,"20,260,326.0",2026-03-26,G810386045,NaN,SME+,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING
57465,"20,260,326.0",2026-03-26,G810386045,"13,422,240.0",SME+,0.0,KCP PANGERAN JAYAKARTA,EKAJIWA,NaN,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,FUNDING
51093,"20,260,326.0",2026-03-26,G909415036,"12,492,320.0",SME+,0.0,KCP TAMAN PALEM,PURI KENCANA,NaN,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,FUNDING
548,"20,260,326.0",2026-03-26,G909415036,NaN,SME+,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING
570,"20,260,326.0",2026-03-26,G910641026,NaN,SME+,NaN,NaN,NaN,JAKARTA 1,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,LENDING
58985,"20,260,326.0",2026-03-26,G910641026,"13,663,941.0",SME+,0.0,KCP GRAHA IRAMA,MT HARYONO,NaN,"22,502.0",HARRY SUMA WINATA,REGIONAL RETAIL BANKING HEAD,hswinata@maybank.co.id,FUNDING

In [311]:
upline_smeplus_pdt_final['SALES_NAME'] = np.where(upline_smeplus_pdt_final['SALES_NAME'].isna(),
                                                 '',
                                                 upline_smeplus_pdt_final['SALES_NAME'])

In [312]:
#EXPORT - SME+
##LENDING
baseline_smeplus_lending.to_csv(save_smeplus_baseline_lending, index=False)
# upline_smeplus_lending.to_csv(r'Results\UPLINE_LENDING_SMEPlus_240606.csv',
#                         index=False)

##FUNDING
# baseline_smeplus_funding.to_csv(r'Results\BASELINE_FUNDING_SMEPlus_240229.csv',
#                           index=False)
# upline_smeplus_funding.to_csv(r'Results\UPLINE_FUNDING_SMEPlus_240229.csv',
#                         index=False)

##ALL (PDT)
baseline_smeplus_pdt_final.to_csv(save_smeplus_baseline, index=False)
upline_smeplus_pdt_final.to_csv(save_smeplus_upline, index=False)

## 3. BB

### 3.1 Adjust Columns between Baseline and Upline

In [313]:
current_m_lending4

'2025-10-09'

In [314]:
#BASELINE ADJUSTMENT
baseline_bb_lending['BASE_DT'] = current_m_lending3
baseline_bb_lending['Date'] = pd.to_datetime(current_m_lending4)
baseline_bb_lending['L_F'] = 'LENDING'
baseline_bb_lending['BRANCH CODE'] = np.nan
baseline_bb_lending['BRANCH'] = np.nan
baseline_bb_lending['CIF_NO'] = np.nan
baseline_bb_lending['LOB'] = 'BB'
baseline_bb_lending = baseline_bb_lending[['BASE_DT', 'Date','GCIF_NO', 'CIF_NO','LOB','BRANCH CODE','BRANCH',
                                                'AREA', 'REGION','NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN','L_F']]

baseline_bb_funding['BASE_DT'] = current_d_funding
baseline_bb_funding['Date'] = pd.to_datetime(current_d2_funding)
baseline_bb_funding = baseline_bb_funding[['BASE_DT', 'Date', 'GCIF_NO', 'CIF_NO','LOB','BRANCH CODE', 'BRANCH', 
                                               'AREA', 'REGION', 'NPK', 'NAMA', 
                                               'JABATAN', 'EMAIL_KARYAWAN', 'L_F']]

C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\1485397928.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_bb_funding['BASE_DT'] = current_d_funding
C:\Users\JS37500\AppData\Local\Temp\ipykernel_9848\1485397928.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_bb_funding['Date'] = pd.to_datetime(current_d2_funding)

In [315]:
#UPLINE ADJUSTMENT
UPLINE_COLS = [
    'BASE_DT','Date','GCIF_NO','SALES_NAME',
    'LINE_MANAGER_1','LINE_MANAGER_2',
    'LINE_MANAGER_3','LINE_MANAGER_4',
    'LOB','BRANCH CODE','BRANCH','AREA','REGION','L_F'
]

upline_bb_funding = (
    upline_bb_funding
    .assign(
        BASE_DT=current_d_funding,
        Date=pd.to_datetime(current_d2_funding),
        LOB='SME',
        L_F='FUNDING'
    )
    .reindex(columns=UPLINE_COLS)
)

### 3.2 Combine into Final PDT Mapping

In [316]:
#CHECKPOINT: should be the same as jumlah cust di BASE PROD HOLD (BB: ~4)
gcif_funding_bb = baseline_bb_funding[['GCIF_NO','REGION']].drop_duplicates()
len(gcif_funding_bb)

4692

In [317]:
#ALL BB (FOR PDT)
baseline_bb_pdt = pd.concat([baseline_bb_lending,baseline_bb_funding],axis=0)
upline_bb_pdt = pd.concat([upline_bb_lending,upline_bb_funding],axis=0)

In [318]:
#In PDT Dashboards, only show LENDING UPLINE
upline_bb_pdt_final = upline_bb_pdt.sort_values('L_F')
upline_bb_pdt_final = upline_bb_pdt_final.drop_duplicates('GCIF_NO',keep='last')

#For Regional Directors (can see both Funding and Lending GCIFS), take the FUNDING rows
# (For more complete information of BRANCH))
baseline_bb_pdt_final = baseline_bb_pdt.sort_values('L_F')
baseline_bb_pdt_final = baseline_bb_pdt_final.drop_duplicates(['GCIF_NO','EMAIL_KARYAWAN'],keep='first')

In [319]:
baseline_bb_lending[['NAMA', 'JABATAN']] = baseline_bb_lending[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
#Comment biar bisa
# baseline_bb_lending['EMAIL_KARYAWAN'] = baseline_bb_lending['EMAIL_KARYAWAN'].str.lower()

baseline_bb_pdt_final[['NAMA', 'JABATAN']] = baseline_bb_pdt_final[['NAMA', 'JABATAN']].astype(str).apply(lambda col: col.str.upper())
# baseline_bb_pdt_final['EMAIL_KARYAWAN'] = baseline_bb_pdt_final['EMAIL_KARYAWAN'].str.lower()

upline_bb_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_bb_lending[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

upline_bb_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']] = upline_bb_pdt_final[['SALES_NAME', 'LINE_MANAGER_1','LINE_MANAGER_2','LINE_MANAGER_3','LINE_MANAGER_4']].astype(str).apply(lambda col: col.str.upper())

In [320]:
# EXPORT - BB (UNCOMMENT MONTHLY)

##LENDING
baseline_bb_lending.to_csv(save_bb_baseline_lending, index=False)
# upline_bb_lending.to_csv(r'Results\UPLINE_LENDING_bb_240606.csv',
#                         index=False)

##FUNDING
# baseline_bb_funding.to_csv(r'Results\BASELINE_FUNDING_bb_240229.csv',
#                           index=False)
# upline_bb_funding.to_csv(r'Results\UPLINE_FUNDING_bb_240229.csv',
#                         index=False)

##ALL (PDT)
baseline_bb_pdt_final.to_csv(save_bb_baseline, index=False)
upline_bb_pdt_final.to_csv(save_bb_upline, index=False)

In [321]:
baseline_bb_lending[baseline_bb_lending['NAMA'].str.contains('RENITA')]

,BASE_DT,Date,GCIF_NO,CIF_NO,LOB,BRANCH CODE,BRANCH,AREA,REGION,NPK,NAMA,JABATAN,EMAIL_KARYAWAN,L_F
35,250731,2025-10-09,G005481353,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
40,250731,2025-10-09,G201153384,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
43,250731,2025-10-09,G306907387,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
45,250731,2025-10-09,G310162789,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
47,250731,2025-10-09,G504235342,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
48,250731,2025-10-09,G709799621,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
50,250731,2025-10-09,G808656516,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
51,250731,2025-10-09,G900723248,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
52,250731,2025-10-09,G906164959,NaN,BB,NaN,NaN,,JAKARTA 1,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
113,250731,2025-10-09,G710163874,NaN,BB,NaN,NaN,,JAKARTA 2,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING
115,250731,2025-10-09,G805868288,NaN,BB,NaN,NaN,,JAKARTA 2,"37,834.0",RENITA ANGELLA S,RELATIONSHIP MANAGER,rangella@maybank.co.id,LENDING

In [322]:
print(f"This whole process took {(time.time()-start_time)//60} minutes and {(time.time()-start_time)%60:.2f} seconds")

This whole process took 86.0 minutes and 35.45 seconds

In [323]:
baseline_rsme_pdt_final[baseline_rsme_pdt_final['GCIF_NO']=='G810066134']

,BASE_DT,Date,GCIF_NO,CIF_NO,LOB,BRANCH CODE,BRANCH,AREA,REGION,NPK,NAMA,JABATAN,EMAIL_KARYAWAN,L_F
19928,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"43,420.0",YUDI SASTRA GUNAWAN,REGIONAL SME HEAD,ysgunawan@maybank.co.id,LENDING
19927,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"20,852.0",HENDRY LIE,REGIONAL SME HEAD,hendry_sme@maybank.co.id,LENDING
4854,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"41,184.0",OSBIE OSMAN,REGIONAL DIRECTOR,osbie.osman@maybank.co.id,LENDING
4190,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"30,660.0",ASRI TARADIPA SIHOMBING,RELATIONSHIP OFFICER,atsihombing@maybank.co.id,LENDING
13778,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"38,871.0",MICHAEL JONATHAN SANTOSO,AREA SME HEAD,m.jonathan@maybank.co.id,LENDING
8947,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,KOTA,JAKARTA 2,"26,026.0",GUNEYDY PUTRA,SME MANAGER,gputra@maybank.co.id,LENDING
24158,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"38,440.0",SITI AISYAH,ADMIN,siti.aisyah@maybank.co.id,LENDING
24157,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"37,500.0",JESVIKA SARI MELYNA SIHOMBING,ADMIN,jsmsihombing@maybank.co.id,LENDING
24156,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"36,690.0",IZZA RANNISA,ADMIN,izza.r@maybank.co.id,LENDING
24155,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"38,713.0",DIMAS FEBRIATMOKO,ADMIN,dfebriatmoko@maybank.co.id,LENDING
24154,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"38,810.0",AHMAD HUMAEDI,ADMIN,a.humaedi@maybank.co.id,LENDING
4854,20260326,2026-03-26,G810066134,NaN,SME,NaN,NaN,NaN,JAKARTA 2,"35,653.0",PHANG HENDRI SETIAWAN,REGIONAL RETAIL BANKING HEAD,phang.hendri@maybank.co.id,LENDING

In [324]:
baseline_rsme_pdt_final[baseline_rsme_pdt_final['NAMA'].str.contains('WAH HENDY')].count()

BASE_DT           37
Date              37
GCIF_NO           37
CIF_NO             0
LOB               37
BRANCH CODE        0
BRANCH             0
AREA              37
REGION            37
NPK               37
NAMA              37
JABATAN           37
EMAIL_KARYAWAN    37
L_F               37
dtype: int64